/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface _AITFireProbe (MobileSafariExtras)
- (void)setWebHistoryItemSharedLinkIdentifier:(id)fp8;
- (id)webHistoryItemSharedLinkIdentifier;
- (void)setWebHistoryItemBookmarkID:(unsigned int)fp8;
- (unsigned int)webHistoryItemBookmarkID;
- (void)setSecurityInfo:(id)fp8;
- (id)securityInfo;
@end

