/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface _AITFireProbe (SafariAdditions)
+ (id)mainBookmarkCollection;
- (void)migrateYouTubeBookmarks;
- (id)_uniqueYouTubeBookmarkFolderName;
- (void)_markDuplicateReadingListBookmarkUnread:(id)fp8 updatingController:(id)fp12;
- (void)_startDownloadingIcons;
- (void)receivedBookmarksDidChangeNotification:(id)fp8;
- (BOOL)updateReadingListBookmarkWithID:(unsigned int)fp8 setTitle:(id)fp12 address:(id)fp16 previewText:(id)fp20;
- (BOOL)markReadingListBookmarkWithIDAsRead:(unsigned int)fp8;
- (BOOL)saveReadingListBookmarkWithTitle:(id)fp8 address:(id)fp12 previewText:(id)fp16 thumbnailURL:(id)fp20 siteName:(id)fp24 tabDocument:(id)fp28 didFetchPage:(BOOL)fp32 updateController:(id)fp36;
- (BOOL)saveReadingListBookmarkWithTitle:(id)fp8 address:(id)fp12;
- (void)importBuiltinBookmarks;
- (void)_importFavoritesFolderBuiltinBookmarks;
- (void)_setLastImportedCarrierBookmarkInfo:(id)fp8;
- (id)_lastImportedCarrierBookmarkInfo;
- (void)_importCarrierBookmarksIfNecessaryAsync;
- (void)_importCarrierBookmarksIfNecessary:(id)fp8;
- (void)_importRootFolderBuiltinBookmarks;
- (id)_googleBookmarkDictionary;
- (id)_googleBookmarkAddressForLocale:(id)fp8;
- (void)_importBuiltinBookmarkWithInfo:(id)fp8 intoParent:(unsigned int)fp12 asCarrierBookmark:(BOOL)fp16 ignoringOldDeletedStaticBookmarks:(id)fp20 carrierBookmarkInfo:(id)fp24;
- (id)_builtinBookmarkWithInfo:(id)fp8 carrierBookmark:(BOOL)fp12 carrierBookmarkInfo:(id)fp16;
- (void)_getCarrierBundleBuiltinBookmarkInfoWithCompletion:(id)fp(null);
- (id)_carrierBundleBuiltinBookmarkInfo;
- (id)_builtinFavorites;
- (id)_builtinFavoritesURLForLocale:(id)fp8;
- (id)_fallbackBuiltinFavoritesPath;
- (id)_builtinFavoritesURLForLocaleIdentifier:(id)fp8;
@end

