/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface _AITFireProbe (SafariAnimationUtilities)
+ (void)safari_animate:(BOOL)fp8 usingDefaultTimingWithOptions:(unsigned int)fp12 animations:(id)fp(null) completion:(void)fp16;
+ (void)safari_animate:(BOOL)fp8 withDuration:(double)fp12 delay:(double)fp20 options:(unsigned int)fp28 animations:(id)fp(null) completion:(void)fp32;
+ (void)safari_animate:(BOOL)fp8 withDuration:(double)fp12 animations:(id)fp(null);
@end

