/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface _AITFireProbe (TableViewScrollPositionSaving)
- (BOOL)safari_hasSavedTableViewScrollPosition;
- (BOOL)safari_restoreTableViewScrollPosition;
- (void)safari_saveTableViewScrollPosition;
- (id)_safari_tableViewScrollPositionKey;
- (id)safari_tableViewScrollPositionSaveIdentifier;
- (id)safari_tableViewForScrollPositionSaving;
@end

