/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface _AITFireProbe (UITableViewCellExtras)
- (void)safari_setLinkedPageTitle:(id)fp8 URL:(id)fp12;
- (void)safari_setLinkedPageTitle:(id)fp8 URL:(id)fp12 simplificationOptions:(unsigned int)fp16;
- (id)initTransparentCellWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
@end

