/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol _UINavigationInteractiveTransitionBaseDelegate <NSObject>
- (id)gestureRecognizerForInteractiveTransition:(id)fp8 WithTarget:(id)fp12 action:(SEL)fp16;
- (BOOL)interactiveTransition:(id)fp8 gestureRecognizer:(id)fp12 shouldReceiveTouch:(id)fp16;
- (BOOL)interactiveTransition:(id)fp8 gestureRecognizer:(id)fp12 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp16;
- (BOOL)shouldBeginInteractiveTransition:(id)fp8;
- (void)startInteractiveTransition:(id)fp8;
@end

