/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UIActivityItemsSource-Protocol.h"

@class BrowserPrintPageRenderer, NSData, NSURL, UIPrintInfo;

@interface ActionPanelActivityItemsSource : _AITFireProbe <UIActivityItemsSource>
{
    BrowserPrintPageRenderer *_printRenderer;
    UIPrintInfo *_printInfo;
    NSData *_imageOnlyDocumentData;
    NSURL *_urlToShare;
}

- (id)activityViewController:(id)fp8 thumbnailImageForActivityType:(id)fp12 suggestedSize:(struct CGSize)fp16;
- (id)activityViewController:(id)fp8 subjectForActivityType:(id)fp12;
- (id)activityViewController:(id)fp8 itemsForActivityType:(id)fp12;
- (id)activityViewControllerPlaceholderItems:(id)fp8;
- (id)_activityItemsForActivityType:(id)fp8;
- (id)_customActivities;
- (void)dealloc;

@end

