/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "AddBookmarkNavigationControllerDelegate-Protocol.h"

@class AddBookmarkNavigationController;

@interface AddBookmarkUIActivity : _AITFireProbe <AddBookmarkNavigationControllerDelegate>
{
    AddBookmarkNavigationController *_bookmarkNavController;
}

- (void)addBookmarkNavController:(id)fp8 didFinishWithResult:(BOOL)fp12;
- (void)activityDidFinish:(BOOL)fp8;
- (id)_embeddedActivityViewController;
- (id)activityViewController;
- (void)prepareWithActivityItems:(id)fp8;
- (BOOL)canPerformWithActivityItems:(id)fp8;
- (id)_beforeActivity;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;

@end

