/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "CompletionListDelegate-Protocol.h"
#import "RotatablePopoverControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class BookmarksBarView, CompletionList, CompletionTableView, CompletionTableViewController, EllipsedTextFadeView, EllipsedTextView, FadeView, NSString, ProgressView, ReloadImageView, SearchEngineInfo, TabBar, UIImageView, UILabel, UINavigationButton, UIResponder, UISnapshotView, UIView, UnifiedField;

@interface AddressView : _AITFireProbe <RotatablePopoverControllerDelegate, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, CompletionListDelegate>
{
    UIImageView *_gradientImageView;
    UIImageView *_bottomShadowView;
    ReloadImageView *_reloadImageView;
    UnifiedField *_addressTextField;
    NSString *_addressText;
    BOOL _addressTextIsSearch;
    UIResponder *_responderForEditingWithoutFirstResponder;
    ProgressView *_progressView;
    UIView *_urlClipperView;
    EllipsedTextView *_ellipsedTextView;
    EllipsedTextFadeView *_ellipsedTextFadeView;
    UIView *_bookmarkBarClipperView;
    UIImageView *_dividerView;
    BookmarksBarView *_bookmarksBarView;
    TabBar *_tabBar;
    UILabel *_titleTextView;
    struct CGSize _titleTextSize;
    UIImageView *_lockView;
    NSString *_evOrganizationName;
    NSString *_pageTitle;
    UIView *_titleTextViewContainer;
    NSString *_titleAfterCoalescedUpdate;
    UINavigationButton *_cancelButton;
    FadeView *_fadeView;
    CompletionTableViewController *_completionTableViewController;
    CompletionTableView *_completionTable;
    CompletionList *_completionList;
    BOOL _shouldShowCompletions;
    BOOL _networkIsReachable;
    SearchEngineInfo *_currentSearchEngine;
    NSString *_searchCountKey;
    unsigned int _isAnimating:1;
    unsigned int _isEditing:1;
    unsigned int _isShowingBookmarksBar:1;
    unsigned int _suppressTextFieldDidEndEditingResponse:1;
    UISnapshotView *_snapshotView;
    UIView *_blankSectionHeaderView;
    SEL _outstandingDidStopSelector;
    BOOL _progressStalled;
    BOOL _usesPrivateBrowsingStyle;
    float _addressFieldLeftInset;
}

+ (BOOL)alwaysShowBookmarksBar;
+ (void)setAlwaysShowBookmarksBar:(BOOL)fp8;
+ (double)hideDelay;
+ (BOOL)_showsTitle;
- (float)addressFieldLeftInset;
- (void)setAddressFieldLeftInset:(float)fp8;
- (void)setUsesPrivateBrowsingStyle:(BOOL)fp8;
- (void)updateReaderButton;
- (void)_layoutClipperViewAndEllipsedTextView;
- (void)_animateInWithSnapshotDidEnd;
- (id)snapshotView;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (void)adjustCompletionTableForKeyboardChange:(id)fp8 animated:(BOOL)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)inputAccessoryView;
- (BOOL)_activeTabIsBlankDocument;
- (int)_sectionIndexForFindOnThisPage;
- (BOOL)keyboardInputShouldDelete:(id)fp8;
- (BOOL)keyboardInput:(id)fp8 shouldInsertText:(id)fp12 isMarkedText:(BOOL)fp16;
- (void)_clearAddressTextFieldWithKeyboardInput:(id)fp8;
- (void)_pushUndoActionName:(id)fp8;
- (void)textFieldClearButtonPressed:(id)fp8;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (void)didMoveToSuperview;
- (void)setIsAnimating:(BOOL)fp8;
- (BOOL)isAnimating;
- (void)willHideProgress;
- (void)willShowProgress;
- (void)setEVOrganizationName:(id)fp8;
- (id)lockView;
- (id)titleTextView;
- (id)evOrganizationName;
- (id)title;
- (void)setTitle:(id)fp8 forceUpdate:(BOOL)fp12;
- (void)updateTitleTextViewForCoalescedUpdate;
- (id)progressView;
- (id)ellipsedTextView;
- (id)reloadImageView;
- (void)setProgress:(float)fp8 forceUpdate:(BOOL)fp12;
- (void)setProgressStalled:(BOOL)fp8;
- (void)_updateReloadImageViewWithForcedUpdate:(BOOL)fp8;
- (void)searchWithSearchString:(id)fp8;
- (void)search;
- (void)_completedEditingAddressWithText:(id)fp8;
- (void)goToURL;
- (BOOL)isEditing;
- (void)browserControllerWillEndEnteringURL;
- (void)cancel;
- (void)transitionAwayFromEditingTextField:(id)fp8;
- (void)focusAddressField;
- (void)_ellipsedTextViewWasClicked;
- (void)transitionToEditingTextField:(id)fp8;
- (struct CGRect)_editingFrame;
- (void)_prepareTitleForAnimatedAlignmentChange;
- (void)_didFinishAnimatingToStopEditing;
- (void)willSuspend;
- (void)updateBookmarksBar;
- (void)cleanUpBookmarksBar;
- (void)hideBookmarksBar;
- (void)showBookmarksBar;
- (void)prepareToShowBookmarksBar;
- (void)_didFinishAnimatingToEditURL;
- (id)_colorForBookmarksBarTitles;
- (void)_adjustClipperViewAndEllipsedTextViewForEditing:(BOOL)fp8 textField:(id)fp12;
- (void)_layoutEllipsedTextViewForProgressViewFrame:(struct CGRect)fp8;
- (BOOL)_shouldDoURLSlideAnimation;
- (float)_addressWidthIncludingScheme:(BOOL)fp8;
- (void)_createButtons;
- (void)_cancelMouseExit;
- (void)_cancelMouseEnter;
- (void)_cancelMouseUpOutside;
- (void)_cancelMouseDown;
- (void)_swapInTextEditingView:(BOOL)fp8 andGiveFocus:(BOOL)fp12;
- (void)_updateAddressTextFieldText;
- (void)_setAddressTextFieldText:(id)fp8;
- (void)_updateFieldBackgroundStylesForEditing:(BOOL)fp8 textField:(id)fp12;
- (void)_createAddressTextFieldIfNecessary;
- (id)unifiedField:(id)fp8 topHitForText:(id)fp12;
- (BOOL)unifiedField:(id)fp8 shouldWaitForTopHitForText:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithSearch:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithAddress:(id)fp12;
- (BOOL)isFindOnPageSupported;
- (void)_addressTextDidChangeFromTyping;
- (void)_updateCompletions;
- (void)completionList:(id)fp8 topHitDidBecomeReadyForString:(id)fp12;
- (void)completionListDidUpdate:(id)fp8;
- (void)clearURLCompletionList;
- (void)hideCompletionTableIfItIsBeingShown;
- (void)_hideCompletions;
- (void)popoverController:(id)fp8 willPresentAfterRotationToInterfaceOrientation:(int)fp12;
- (void)_showCompletions;
- (void)_reloadCompletionTableAndAdjustPopover;
- (BOOL)_completionTableIsVisible;
- (struct CGRect)_presentationRectForCompletionPopover;
- (void)_adjustClipperViewAndEllipsedTextViewAfterAnimateInOrOut;
- (void)_readerButtonClicked;
- (void)_reloadImageViewClicked;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)dealloc;
- (void)setTabBar:(id)fp8;
- (void)_networkReachabilityChanged:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)_setTitleText:(id)fp8;
- (void)updateUIWithForcedUpdate:(BOOL)fp8;
- (id)_currentSearchQuery;
- (void)updateEllipsedTextView;
- (void)_layoutAddressTextField;
- (void)_layoutAddressTextFieldForProgressViewBounds:(struct CGRect)fp8;
- (void)_updateURLClipperViewFrameForReloadButtonRegionWidth:(float)fp8;
- (struct CGRect)_addressFrameInProgressViewBounds:(struct CGRect)fp8;
- (id)_colorForEVOrganizationNameInTitle;
- (id)_colorForNormalPageTitle;
- (void)updateSearchEngine;
- (void)_initSearchEngineIfNeeded;
- (void)layoutSubviews;
- (void)setBounds:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)_updateTabBarBackgroundOffset;
- (void)_layoutEllipsedTextFadeViewForEditing:(BOOL)fp8 textField:(id)fp12;
- (void)_layoutEllipsedTextFadeViewShowingAdjustment:(BOOL)fp8;
- (void)_layoutCancelButtonForEditing:(BOOL)fp8 beforeAnimation:(BOOL)fp12;
- (void)_layoutReloadButtonForProgressViewFrame:(struct CGRect)fp8 forEditing:(BOOL)fp24 textField:(id)fp28;
- (void)_layoutTitleView;
- (void)_setTitleFrame:(struct CGRect)fp8;
- (void)_updateLockViewImage;
- (void)_updateLockViewPosition;
- (void)_layoutCompletionTable;
- (void)_setUpTargetViewForCompletionTable;
- (float)_reloadButtonRegionWidthWhenEditingTextField:(id)fp8;
- (float)_reloadButtonRegionWidth;
- (float)_rightSideButtonsRegionWidth;
- (id)_textFieldForEditing;
- (struct CGRect)_frameForUnifiedFieldInProgressViewFrame:(struct CGRect)fp8;
- (struct CGRect)_frameForProgressViewWithFocus:(BOOL)fp8;
- (float)_fieldPaddingTop;
- (float)_fieldWidth;
- (struct CGRect)_fieldRect;
- (void)browserControllerDidEndRotating;
- (void)browserControllerDidStartRotating;
- (BOOL)_isShowingProgress;
- (float)progress;
- (id)tabBar;
- (float)editingHeight;
- (float)defaultHeight;
- (float)_heightWithoutBars;

@end

