/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "WebClipDelegate-Protocol.h"
#import "WebClipViewControllerDelegate-Protocol.h"

@class UINavigationController, UIWebClip, WebClipViewController;

@interface AddToHomeScreenUIActivity : _AITFireProbe <WebClipDelegate, WebClipViewControllerDelegate>
{
    UINavigationController *_wrappingNavigationController;
    WebClipViewController *_webClipViewController;
    UIWebClip *_webClip;
    BOOL _waitingForSnapshot;
}

- (void)_updateImageFromActiveTabDocument;
- (void)_createWebClip;
- (void)webClip:(id)fp8 startupLandscapeImageRequestDidFinishWithImage:(id)fp12;
- (void)webClip:(id)fp8 startupImageRequestDidFinishWithImage:(id)fp12;
- (void)webClip:(id)fp8 iconRequestDidFinishWithImage:(id)fp12 precomposed:(BOOL)fp16;
- (void)webClipViewController:(id)fp8 didFinishWithResult:(BOOL)fp12;
- (void)activityDidFinish:(BOOL)fp8;
- (id)_embeddedActivityViewController;
- (id)activityViewController;
- (void)prepareWithActivityItems:(id)fp8;
- (BOOL)canPerformWithActivityItems:(id)fp8;
- (id)_beforeActivity;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;
- (id)init;

@end

