/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface AppBundleURLProtocol : _AITFireProbe
{
}

+ (BOOL)requestIsCacheEquivalent:(id)fp8 toRequest:(id)fp12;
+ (id)canonicalRequestForRequest:(id)fp8;
+ (BOOL)canInitWithRequest:(id)fp8;
+ (id)URLForResourceAtPath:(id)fp8;
+ (id)URLScheme;
+ (void)registerProtocol;
+ (void)initialize;
- (void)stopLoading;
- (void)startLoading;
- (void)_sendDataToClient:(id)fp8 forURL:(id)fp12;
- (void)_sendURLErrorToClient:(int)fp8 forURL:(id)fp12;
- (void)_sendURLErrorToClient:(int)fp8 withUserInfo:(id)fp12;

@end

