/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PopoverSizingTableViewController.h"

@class NSArray;

@interface BackForwardTableViewController : PopoverSizingTableViewController
{
    BOOL _reversesListOrder;
    id <BackForwardTableViewControllerDelegate> _delegate;
    NSArray *_backForwardList;
}

- (void)setReversesListOrder:(BOOL)fp8;
- (BOOL)reversesListOrder;
- (id)backForwardList;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (void)loadView;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)indexForIndexPath:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setBackForwardList:(id)fp8;

@end

