/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BackForwardTableViewControllerDelegate-Protocol.h"
#import "BrowserPanel-Protocol.h"

@class BackForwardTableViewController;

@interface BackForwardNavigationController : _AITFireProbe <BrowserPanel, BackForwardTableViewControllerDelegate>
{
    BackForwardTableViewController *_tableViewController;
    int _savedStatusBarStyle;
}

- (struct CGSize)preferredContentSize;
- (BOOL)shouldShowButtonBar;
- (id)toolbarItems;
- (BOOL)ignoresPrivateBrowsingStyle;
- (int)pausesPages;
- (int)panelType;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (id)rotatingFooterView;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)backForwardTableViewController:(id)fp8 didSelectWebHistoryItem:(id)fp12;
- (void)setReversesListOrder:(BOOL)fp8;
- (BOOL)reversesListOrder;
- (void)setBackForwardList:(id)fp8;
- (id)backForwardList;
- (void)done;
- (void)dealloc;
- (id)init;

@end

