/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PopoverSizingTableViewController.h"

#import "BookmarksPanelStateRestoring-Protocol.h"

@class WebBookmark, WebBookmarkCollection, WebBookmarkList;

@interface BookmarksTableViewController : PopoverSizingTableViewController <BookmarksPanelStateRestoring>
{
    WebBookmarkCollection *_collection;
    WebBookmarkList *_bookmarkList;
    WebBookmark *_favoritesFolder;
    unsigned int _skipOffset;
    float _restoredScrollPosition;
    BOOL _useTransparentCells;
    WebBookmark *_folder;
    id <BookmarksTableViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)folder;
- (id)selectedBookmarks;
- (id)collectionType;
- (void)restoreScrollPosition:(float)fp8;
- (float)currentScrollPosition;
- (BOOL)restoreStateWithDictionary:(id)fp8;
- (id)currentStateDictionary;
- (void)setScrollViewScrollsToTop:(BOOL)fp8;
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (id)tableView:(id)fp8 targetIndexPathForMoveFromRowAtIndexPath:(id)fp12 toProposedIndexPath:(id)fp16;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (BOOL)tableView:(id)fp8 canMoveRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_updateTableViewCellsTextStyleForEditing:(BOOL)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)_pushInfoViewControllerForBookmark:(id)fp8;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)_tableViewCellForBookmark:(id)fp8;
- (id)_grayedOutHistoryFolderIcon;
- (id)_grayedOutFavoriteFolderIcon;
- (id)_tintedImageNamed:(id)fp8;
- (id)bookmarksTableViewCellWithReuseIdentifier:(id)fp8;
- (id)_bookmarkAtIndexPath:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)_collectionForRowAtIndexPath:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)loadView;
- (id)bookmarksNavigationController;
- (void)dealloc;
- (void)setFolder:(id)fp8;
- (unsigned int)folderID;
- (void)reloadBookmarks;
- (void)_recreateBookmarkLists;
- (BOOL)_inRootFolder;
- (id)initWithFolder:(id)fp8 inCollection:(id)fp12 skipOffset:(unsigned int)fp16;
- (id)initWithFolder:(id)fp8 inCollection:(id)fp12;

@end

