/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface BookmarksTableView : _AITFireProbe
{
    struct UIEdgeInsets _visibleBoundsInsets;
}

- (void)setVisibleBoundsInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)visibleBoundsInsets;
- (struct CGRect)_visibleBounds;

@end

