/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BookmarkFavoritesViewControllerDelegate <NSObject>
- (struct UIEdgeInsets)contentInsetForFavoritesViewController:(id)fp8;
- (void)didTapOutsideBookmarkFavoritesViewController:(id)fp8;
- (void)bookmarkFavoritesViewController:(id)fp8 didSelectFolder:(id)fp12;
- (void)bookmarkFavoritesViewController:(id)fp8 didSelectNavigationDestination:(id)fp12;
@end

