/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class BookmarkTextEntryTableViewCell, NSString;

@interface BookmarkTextEntryTableViewController : _AITFireProbe
{
    id <BookmarkTextEntryTableViewControllerDelegate> _delegate;
    NSString *_initialText;
    int _autocapitalizationType;
    int _autocorrectionType;
    BookmarkTextEntryTableViewCell *_textEntryCell;
}

- (void)_returnWasPressedInTextField:(id)fp8;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)loadView;
- (id)initWithBookmarkInfoViewField:(int)fp8 text:(id)fp12 autocapitalizationType:(int)fp16 autocorrectionType:(int)fp20 delegate:(id)fp24;

@end

