/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class SiteIconView, UILabel, UIView, WebBookmark;

@interface BookmarkFavoriteView : _AITFireProbe
{
    SiteIconView *_iconView;
    UIView *_iconTouchHighlightView;
    UILabel *_titleLabel;
    BOOL _grabbed;
    WebBookmark *_bookmark;
    float _maximumLabelHangingIndent;
}

+ (struct CGSize)defaultSize;
+ (void)_getTitleLabelHeight:(float *)fp8 firstBaselineOffset:(float *)fp12 lastBaselineOffset:(float *)fp16;
+ (id)_adjustedLabelFontForPreferredContentSize;
- (float)maximumLabelHangingIndent;
- (BOOL)isGrabbed;
- (id)bookmark;
- (void)setMaximumLabelHangingIndent:(float)fp8;
- (struct CGPoint)iconCenter;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setGrabbed:(BOOL)fp8;
- (void)_unhighlight:(id)fp8;
- (void)_highlight:(id)fp8;
- (id)displayedBookmarkIcon;
- (void)setBookmark:(id)fp8 icon:(id)fp12;
- (void)setBookmark:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;

@end

