/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BookmarksTableViewControllerDelegate <NSObject>
- (struct UIEdgeInsets)separatorInsetForBookmarksTableViewController:(id)fp8;
- (struct UIEdgeInsets)visibleBoundsInsetsForBookmarksTableViewController:(id)fp8;
- (struct UIEdgeInsets)contentInsetForBookmarksTableViewController:(id)fp8;
- (void)bookmarksTableViewController:(id)fp8 didSelectNavigationDestination:(id)fp12;
@end

