/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "ViewReuseManagerDelegate-Protocol.h"

@class BookmarkFavoriteView, NSCache, NSMutableArray, NSTimer, UILongPressGestureRecognizer, UIScrollView, UITapGestureRecognizer, UIView, ViewReuseManager;

@interface BookmarkFavoritesGridView : _AITFireProbe <UIGestureRecognizerDelegate, UIScrollViewDelegate, ViewReuseManagerDelegate>
{
    NSMutableArray *_bookmarks;
    UIScrollView *_scrollView;
    ViewReuseManager *_reuseManager;
    BOOL _suppressLayoutOnScroll;
    float _rowHeight;
    UITapGestureRecognizer *_tapOutsideRecognizer;
    UILongPressGestureRecognizer *_reorderLongpressRecognizer;
    NSTimer *_reorderTimer;
    struct CGPoint _reorderTimerStartingLocation;
    unsigned int _grabbedFavoriteOriginalIndex;
    unsigned int _grabbedFavoritePreviousIndex;
    BookmarkFavoriteView *_grabbedFavoriteView;
    struct CGPoint _grabbedFavoriteOffset;
    NSCache *_iconsCache;
    BOOL _allowsReordering;
    int _interfaceOrientation;
    id <BookmarkFavoritesGridViewDelegate> _delegate;
    UIView *_contentView;
}

- (id)contentView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAllowsReordering:(BOOL)fp8;
- (BOOL)allowsReordering;
- (void)setInterfaceOrientation:(int)fp8;
- (int)interfaceOrientation;
- (void)scrollViewDidScrollToTop:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)viewReuseManager:(id)fp8 prepareView:(id)fp12 toRepresentObjectAtIndex:(unsigned int)fp16;
- (void)viewReuseManager:(id)fp8 willRecycleView:(id)fp12;
- (void)_replaceBookmarkForBookmarkFavoriteView:(id)fp8 newBookmark:(id)fp12;
- (void)_updateFavoriteViews;
- (int)_firstVisibleBookmarkIndex;
- (id)_favoriteViews;
- (void)setScrollViewScrollsToTop:(BOOL)fp8;
- (void)_favoriteViewTapped:(id)fp8;
- (void)_tapOutsideRecognized:(id)fp8;
- (void)_reorderRecognized:(id)fp8;
- (void)_reorderTimerDidFire:(id)fp8;
- (void)_clearReorderTimer;
- (void)_startReorderTimer;
- (unsigned int)_indexForFavoriteDroppedAtPoint:(struct CGPoint)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (id)favoriteAtPoint:(struct CGPoint)fp8;
- (struct CGSize)_contentSize;
- (float)_cellHorizontalPaddingForCellWidth:(float)fp8;
- (unsigned int)_numberOfRowsForCellWidth:(float)fp8;
- (unsigned int)_numberOfFavoritesPerRowForCellWidth:(float)fp8;
- (float)_horizontalSpaceBetweenFavorites;
- (void)_layoutFavoriteViewsAnimated;
- (void)layoutSubviews;
- (struct CGRect)frameForFavoriteAtIndex:(unsigned int)fp8;
- (float)_rowHeight;
- (void)resetScrollPosition;
- (struct UIEdgeInsets)contentInset;
- (void)setContentInset:(struct UIEdgeInsets)fp8;
- (BOOL)isEmpty;
- (id)bookmarks;
- (void)setBookmarks:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)_dimmingColor;

@end

