/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BookmarkFavoritesGridViewDelegate-Protocol.h"

@class WebBookmarkCollection, WebBookmarkList;

@interface BookmarkFavoritesViewController : _AITFireProbe <BookmarkFavoritesGridViewDelegate>
{
    WebBookmarkCollection *_collection;
    WebBookmarkList *_favoritesList;
    BOOL _showWhitelistFavorites;
    id <BookmarkFavoritesViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)bookmarkFavoritesGridView:(id)fp8 didReorderBookmarkFromIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (BOOL)bookmarkFavoritesGridViewShouldReorderBookmarks:(id)fp8;
- (void)didTapOutsideBookmarkFavoritesGridView:(id)fp8;
- (void)bookmarkFavoritesGridView:(id)fp8 didSelectBookmark:(id)fp12;
- (void)setScrollViewScrollsToTop:(BOOL)fp8;
- (void)_contentSizeCategoryDidChange;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)loadFavoritesList;
- (void)_receivedBookmarksFolderContentChangedNotification:(id)fp8;
- (void)_receivedBookmarksReloadOrSepcialFolderChangeNotification:(id)fp8;
- (id)_bookmarkFavoritesGridView;
- (id)bookmarksNavigationController;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithBookmarksCollection:(id)fp8 showWhiteListFavorites:(BOOL)fp12;

@end

