/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BookmarkFavoritesGridViewDelegate <NSObject>
- (void)bookmarkFavoritesGridView:(id)fp8 didReorderBookmarkFromIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (BOOL)bookmarkFavoritesGridViewShouldReorderBookmarks:(id)fp8;
- (void)didTapOutsideBookmarkFavoritesGridView:(id)fp8;
- (void)bookmarkFavoritesGridView:(id)fp8 didSelectBookmark:(id)fp12;
@end

