/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BookmarksNavigationControllerDelegate-Protocol.h"
#import "RotatablePopoverControllerDelegate-Protocol.h"

@class BookmarksNavigationController, NSMutableArray, UIButton, WebBookmark;

@interface BookmarksBarView : _AITFireProbe <BookmarksNavigationControllerDelegate, RotatablePopoverControllerDelegate>
{
    NSMutableArray *_bookmarkBarLabels;
    unsigned int _bookmarkBarID;
    UIButton *_moreBookmarksButton;
    WebBookmark *_moreBookmarksParent;
    unsigned int _moreBookmarksOffset;
    UIButton *_buttonUsedToShowNavigationController;
    BOOL _isShowingNavigationController;
    BookmarksNavigationController *_bookmarksNavigationController;
    BOOL _usesLightControls;
    id <BookmarksBarViewDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)usesLightControls;
- (void)bookmarksNavigationControllerDidReload:(id)fp8;
- (void)bookmarksNavigationControllerReloadDidFail:(id)fp8;
- (id)containingBookmarkForNavigationController:(id)fp8;
- (void)bookmarksNavigationController:(id)fp8 didSelectNavigationDestination:(id)fp12;
- (void)closeBrowserPanel:(id)fp8;
- (void)didHideBrowserPanel:(id)fp8;
- (void)willHideBrowserPanel:(id)fp8;
- (void)didShowBrowserPanel:(id)fp8;
- (void)willShowBrowserPanel:(id)fp8;
- (id)browserPanel;
- (void)dealloc;
- (void)setUsesLightControls:(BOOL)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)_receivedBookmarksChangedNotification:(id)fp8;
- (void)_reloadBookmarkLabels;
- (void)_createAllLabelButtons;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)popoverController:(id)fp8 willPresentAfterRotationToInterfaceOrientation:(int)fp12;
- (void)_dismissCurrentBookmarksPopover;
- (void)_buttonTapped:(id)fp8;
- (void)_clearBookmarksNavigationController;
- (void)_setButtonUsedToShowNavigationController:(id)fp8;

@end

