/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BookmarkTextEntryTableViewControllerDelegate-Protocol.h"
#import "FolderPickerViewControllerDelegate-Protocol.h"
#import "SiteIconDownloadRequestDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BookmarkTextEntryTableViewCell, NSObject<BookmarkInfoViewControllerDelegate>, SiteIconDownloadRequest, SiteIconView, UITableViewCell, WebBookmark, WebBookmarkCollection;

@interface BookmarkInfoViewController : _AITFireProbe <FolderPickerViewControllerDelegate, BookmarkTextEntryTableViewControllerDelegate, UITableViewDataSource, UITableViewDelegate, SiteIconDownloadRequestDelegate>
{
    WebBookmarkCollection *_collection;
    WebBookmark *_parentBookmark;
    BOOL _addingBookmark;
    BOOL _saveWhenDismissed;
    BookmarkTextEntryTableViewCell *_titleCell;
    BookmarkTextEntryTableViewCell *_addressCell;
    UITableViewCell *_folderCell;
    SiteIconView *_iconImageView;
    SiteIconDownloadRequest *_iconDownloadRequest;
    int _editingField;
    BOOL _didSelectFolder;
    NSObject<BookmarkInfoViewControllerDelegate> *_delegate;
    WebBookmark *_bookmark;
}

- (id)bookmark;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)siteIconDownloadRequestDidFail:(id)fp8;
- (void)siteIconDownloadRequest:(id)fp8 didComputeIconKeyColor:(id)fp12;
- (void)siteIconDownloadRequest:(id)fp8 didLoadIconData:(id)fp12;
- (void)_cancelIconDownloadRequestIfNeeded;
- (void)viewWillLayoutSubviews;
- (struct CGSize)preferredContentSize;
- (struct CGSize)contentSizeForViewInPopoverView;
- (void)dealloc;
- (void)bookmarkTextEntryTableViewController:(id)fp8 dismissedWithText:(id)fp12;
- (void)folderPicker:(id)fp8 pickedFolder:(id)fp12 withSelectedCell:(id)fp16;
- (void)_removeActionsForTextFields;
- (void)_addActionsForTextFields;
- (void)_valuesChanged;
- (BOOL)isEditingField;
- (void)_showFolderPicker;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (void)_editField:(int)fp8;
- (BOOL)canSaveChanges;
- (void)_updateSaveButton;
- (void)saveChanges;
- (void)setParent:(id)fp8;
- (void)setBookmark:(id)fp8;
- (void)_updateCellValues;
- (void)_updateBookmarkIcon;
- (void)_updateIconViewFrame;
- (struct CGPoint)_centerForIconView;
- (void)_reloadData;
- (void)_updateParentFolderCell;
- (BOOL)titleCellHasText;
- (void)_bookmarksDidReload;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (id)_titleCell;
- (BOOL)shouldShowButtonBar;
- (void)loadView;
- (void)_createCellsIfNeeded;
- (void)_returnWasPressedInTextField:(id)fp8;
- (void)_cancel;
- (void)_saveButtonPressed;
- (id)initWithBookmark:(id)fp8 inCollection:(id)fp12 addingBookmark:(BOOL)fp16;

@end

