/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserPanelDelegate-Protocol.h"

@protocol BookmarksNavigationControllerDelegate <BrowserPanelDelegate>
- (id)browserPanel;
- (void)bookmarksNavigationController:(id)fp8 didSelectNavigationDestination:(id)fp12;
@end

