/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface BookmarksTableViewCellLayoutManager : _AITFireProbe
{
}

+ (id)sharedManager;
- (void)layoutSubviewsOfCell:(id)fp8;
- (struct CGRect)accessoryEndingRectForCell:(id)fp8 forNewEditingState:(BOOL)fp12 showingDeleteConfirmation:(BOOL)fp16;
- (struct CGRect)accessoryStartingRectForCell:(id)fp8 forNewEditingState:(BOOL)fp12 showingDeleteConfirmation:(BOOL)fp16;
- (struct CGRect)textRectForCell:(id)fp8;

@end

