/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface BrowserControllerScrollView : _AITFireProbe
{
    struct UIEdgeInsets _hitTestInsets;
}

- (void)setHitTestInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)hitTestInsets;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;

@end

