/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class CatalogViewController, NSArray;

@interface BrowserRootViewController : _AITFireProbe
{
    NSArray *_keyCommands;
    int _preferredStatusBarStyle;
    int _lastKnownOrientation;
    CatalogViewController *_catalogViewController;
}

- (id)catalogViewController;
- (void)setLastKnownOrientation:(int)fp8;
- (int)lastKnownOrientation;
- (void)_closeActiveTabKeyPressed;
- (void)_newTabKeyPressed;
- (void)_focusAddressFieldKeyPressed;
- (void)_navigateForwardKeyPressed;
- (void)_navigateBackKeyPressed;
- (void)_stopLoadingKeyPressed;
- (void)_reloadKeyPressed;
- (id)keyCommands;
- (void)setCatalogViewController:(id)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)_getRotationContentSettings:(CDAnonymousStruct1 *)fp8;
- (id)rotatingFooterView;
- (id)rotatingHeaderView;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)canBecomeFirstResponder;
- (void)setPreferredStatusBarStyle:(int)fp8;
- (int)preferredStatusBarStyle;
- (void)dealloc;
- (id)init;

@end

