/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BrowserPanelDelegate <NSObject>
- (void)closeBrowserPanel:(id)fp8;
- (void)didHideBrowserPanel:(id)fp8;
- (void)willHideBrowserPanel:(id)fp8;
- (void)didShowBrowserPanel:(id)fp8;
- (void)willShowBrowserPanel:(id)fp8;
@end

