/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class BrowserICSPreviewPanel, UIBarButtonItem;

@interface BrowserICSPreviewPanelNavController : _AITFireProbe
{
    UIBarButtonItem *_doneBarButtonItem;
    UIBarButtonItem *_activitiesBarButtonItem;
    BrowserICSPreviewPanel *_icsPanel;
    BOOL _closeBrowserPanelAlreadyCalled;
}

- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (void)_updateNavigationBarItems;
- (void)_ensureRightBarButtonItemsIncludesDoneItem:(id)fp8;
- (void)_ensureLeftBarButtonItemsIncludesDoneItem:(id)fp8;
- (void)_ensureLeftBarButtonItemsIncludesActivitiesItem:(id)fp8;
- (id)_doneBarButonItem;
- (id)_activtyBarButtonItem;
- (void)setCloseBrowserPanelAlreadyCalled:(BOOL)fp8;
- (void)setOwningPanel:(id)fp8;
- (void)dealloc;

@end

