/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BrowserPanel-Protocol.h"
#import "RotatablePopoverControllerDelegate-Protocol.h"

@class BrowserICSPreviewPanelNavController, EKICSPreviewController, NSString, OpenInOtherAppActivityViewController, RotatablePopoverController;

@interface BrowserICSPreviewPanel : _AITFireProbe <RotatablePopoverControllerDelegate, BrowserPanel>
{
    OpenInOtherAppActivityViewController *_activityViewController;
    BrowserICSPreviewPanelNavController *_wrappingNavController;
    RotatablePopoverController *_activityPopover;
    EKICSPreviewController *_icsController;
    NSString *_filePath;
}

- (void)popoverControllerDidDismissPopover:(id)fp8;
- (BOOL)shouldHideOnSuspend;
- (int)pausesPages;
- (BOOL)ignoresPrivateBrowsingStyle;
- (int)panelType;
- (id)viewController;
- (void)_done:(id)fp8;
- (void)_openInOtherAppsButtonPressed:(id)fp8;
- (id)activityViewController;
- (void)dealloc;
- (id)initWithFilePath:(id)fp8;

@end

