/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol CatalogViewControllerDelegate <NSObject>
- (void)catalogViewControllerDidEndEditing:(id)fp8;
- (void)catalogViewControllerDidBeginEditing:(id)fp8;
- (void)catalogViewController:(id)fp8 completionItem:(id)fp12 wasAcceptedForString:(id)fp16;
- (void)catalogViewController:(id)fp8 didSelectFindOnPageWithHighlighter:(id)fp12;
- (void)catalogViewController:(id)fp8 mightSelectCompletionItem:(id)fp12 forString:(id)fp16;
- (void)catalogViewController:(id)fp8 didSelectSearch:(id)fp12;
- (void)catalogViewController:(id)fp8 didSelectAddress:(id)fp12;
@end

