/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "CompletionListDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UnifiedFieldDelegate-Protocol.h"

@class BookmarksNavigationController, CompletionList, NavigationBar, PrivateBrowsingToolbar, UITableView, UnifiedField, WBSBookmarkAndHistoryCompletionMatch;

@interface CatalogViewController : _AITFireProbe <CompletionListDelegate, UITableViewDataSource, UITableViewDelegate, UnifiedFieldDelegate>
{
    id <CatalogViewControllerDelegate> _delegate;
    BookmarksNavigationController *_bookmarksNavigationController;
    UnifiedField *_textField;
    CompletionList *_completionList;
    UITableView *_completionTable;
    PrivateBrowsingToolbar *_privateBrowsingToolbar;
    WBSBookmarkAndHistoryCompletionMatch *_lastTopHitMatch;
    unsigned int _lastTopHitMatchLength;
    BOOL _showingCompletions;
    NavigationBar *_navigationBar;
    float _bottomInset;
}

- (BOOL)isShowingCompletions;
- (float)bottomInset;
- (id)navigationBar;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)unifiedField:(id)fp8 topHitForText:(id)fp12;
- (BOOL)unifiedField:(id)fp8 shouldWaitForTopHitForText:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithSearch:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithAddress:(id)fp12;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)_completionItemAtIndexPath:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)completionList:(id)fp8 topHitDidBecomeReadyForString:(id)fp12;
- (void)_logTopHitWasChosen:(BOOL)fp8;
- (void)completionListDidUpdate:(id)fp8;
- (void)setBottomInset:(float)fp8;
- (void)setNavigationBar:(id)fp8;
- (void)_textFieldEditingChanged;
- (void)setShowingCompletions:(BOOL)fp8;
- (void)_setTextField:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)resetFavorites;
- (void)loadFavoritesList;
- (id)favoritesView;
- (void)updateBackgroundColor;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 bookmarksNavigationController:(id)fp12;

@end

