/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct ArticleFinderJSController;

struct BinaryPropertyListObjectStream {
    void **_field1;
};

struct CATransform3D {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
};

struct CGColor;

struct CGContext;

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct NSDictionary {
    Class _field1;
};

struct OpaqueJSContext;

struct OpaqueJSValue;

struct OwnPtr<ArticleFinderJSController> {
    struct ArticleFinderJSController *_field1;
};

struct ReaderController {
    id _field1;
    struct SString _field2;
    _Bool _field3;
    _Bool _field4;
    struct OwnPtr<ArticleFinderJSController> _field5;
    id _field6;
    struct SString _field7;
    _Bool _field8;
    id _field9;
    id _field10;
    id _field11;
};

struct ReaderJSController {
    void **_field1;
    struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> _field2;
    struct OpaqueJSValue *_field3;
    struct OpaqueJSContext *_field4;
    id _field5;
    struct ReaderController *_field6;
    struct OwnPtr<ArticleFinderJSController> _field7;
    int _field8;
    struct RetainPtr<NSDictionary> _field9;
};

struct RetainPtr<NSDictionary> {
    struct NSDictionary *_field1;
};

struct RetainPtr<const __CFString *> {
    struct __CFString *_field1;
};

struct SString {
    struct RetainPtr<const __CFString *> _field1;
};

struct UIEdgeInsets {
    float top;
    float left;
    float bottom;
    float right;
};

struct UIOffset {
    float _field1;
    float _field2;
};

struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> {
    struct OpaqueJSValue **_field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct Vector<int, 0, WTF::CrashOnOverflow> {
    int *m_buffer;
    unsigned int m_capacity;
    unsigned int m_size;
};

struct _CFURLConnection;

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct _WBUNetworkDataUsage {
    unsigned long long rawBytesSent;
    unsigned long long rawBytesReceived;
    unsigned long long cellularBytesSent;
    unsigned long long cellularBytesReceived;
};

struct __CFDateFormatter;

struct __CFLocale;

struct __CFString;

struct __CTFramesetter;

struct __GSEvent;

struct __sFILE {
    char *_field1;
    int _field2;
    int _field3;
    short _field4;
    short _field5;
    struct __sbuf _field6;
    int _field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    struct __sbuf _field13;
    struct __sFILEX *_field14;
    int _field15;
    unsigned char _field16[3];
    unsigned char _field17[1];
    struct __sbuf _field18;
    int _field19;
    long long _field20;
};

struct __sFILEX;

struct __sbuf {
    char *_field1;
    int _field2;
};

struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[40];
};

typedef struct {
    char _field1;
    char _field2;
    char _field3;
    char _field4;
    float _field5;
    int _field6;
} CDAnonymousStruct1;

typedef struct {
    int nodes;
    int bytes;
} CDAnonymousStruct2;

