/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UITableView, _UIContentUnavailableView;

@interface CloudTabViewController : _AITFireProbe <UITableViewDataSource, UITableViewDelegate>
{
    id <CloudTabViewControllerDelegate> _delegate;
    NSArray *_devices;
    _UIContentUnavailableView *_contentUnavailableView;
    UITableView *_tableView;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)safari_tableViewScrollPositionSaveIdentifier;
- (id)safari_tableViewForScrollPositionSaving;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)_tabForIndexPath:(id)fp8;
- (void)_reloadDevicesAndTable;
- (void)_loadDevices;
- (struct CGSize)preferredContentSize;
- (void)_updatePopoverSize;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)_adjustTableViewInsetsForOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)_clearExplanationView;
- (void)_setupExplanationView;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

