/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSArray, NSDate, NSString;

@interface CloudTabDevice : _AITFireProbe
{
    NSString *_name;
    NSString *_UUID;
    NSArray *_tabs;
    NSDate *_lastModified;
}

- (id)lastModified;
- (id)tabs;
- (id)UUID;
- (id)name;
- (id)description;
- (void)dealloc;
- (id)_initWithDictionary:(id)fp8 UUID:(id)fp12;

@end

