/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class CloudTab, UIView;

@interface CloudTabItemView : _AITFireProbe
{
    UIView *_separatorView;
    CloudTab *_cloudTab;
}

+ (float)defaultHeight;
- (id)cloudTab;
- (void)setHighlighted:(BOOL)fp8;
- (void)setCloudTab:(id)fp8;
- (void)setShowsSeparator:(BOOL)fp8;
- (BOOL)showsSeparator;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

