/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class CloudTab;

@interface CloudTabCompletionMatch : _AITFireProbe
{
    CloudTab *_cloudTab;
}

+ (int)matchLocationForString:(id)fp8 inCloudTab:(id)fp12;
- (id)cloudTab;
- (id)title;
- (id)userVisibleURLString;
- (id)originalURLString;
- (void)dealloc;
- (id)initWithCloudTab:(id)fp8 matchLocation:(int)fp12;

@end

