/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImageView, UILabel, UIView;

@interface CloudTabHeaderView : _AITFireProbe
{
    UILabel *_label;
    UIImageView *_icon;
    UIView *_separatorView;
}

+ (float)defaultHeight;
- (void)setText:(id)fp8;
- (id)text;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

