/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSMutableArray, NSMutableDictionary;

@interface CompletionProvider : _AITFireProbe
{
    NSMutableDictionary *_completionsByString;
    NSMutableArray *_completedStringsInPruneOrder;
    BOOL _failing;
    BOOL _inCompletionsForString;
    id <CompletionProviderDelegate> _delegate;
}

- (BOOL)isFailing;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (unsigned int)maximumCachedCompletionCount;
- (void)fail;
- (void)setCompletions:(id)fp8 forString:(id)fp12;
- (void)clearCachedCompletions;
- (void)_pruneCachedCompletions;
- (void)setStringToComplete:(id)fp8;
- (id)completionsForString:(id)fp8;
- (void)dealloc;
- (id)init;

@end

