/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UITableViewHeaderFooterView;

@interface CompletionTableView : _AITFireProbe
{
    UITableViewHeaderFooterView *_findOnPageHeader;
    float _keyboardOverlap;
    BOOL _specialHeadersEnabled;
}

- (void)setBounds:(struct CGRect)fp8;
- (void)setFindOnPageHeaderTitle:(id)fp8;
- (void)setSpecialHeadersEnabled:(BOOL)fp8;
- (void)updateKeyboardOverlap:(float)fp8 animated:(BOOL)fp12;
- (void)_updateHeaderFrames;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 style:(int)fp24;

@end

