/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface CompletionPopoverBackground : _AITFireProbe
{
}

+ (struct UIEdgeInsets)contentViewInsets;
+ (float)arrowHeight;
+ (float)arrowBase;
- (struct CGSize)_shadowOffset;
- (float)_shadowOpacity;
- (void)setArrowDirection:(unsigned int)fp8;
- (unsigned int)arrowDirection;
- (void)setArrowOffset:(float)fp8;
- (float)arrowOffset;
- (id)initWithFrame:(struct CGRect)fp8;

@end

