/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UITextField;

@interface CompletionTableViewController : _AITFireProbe
{
    id <UITableViewDelegate><UITableViewDataSource> _dataSourceAndDelegateForTableView;
    UITextField *_targetView;
}

- (void)setTargetView:(id)fp8;
- (id)targetView;
- (void)setDataSourceAndDelegateForTableView:(id)fp8;
- (id)dataSourceAndDelegateForTableView;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (struct CGSize)contentSizeForViewInPopoverView;
- (void)viewDidLoad;
- (void)dealloc;

@end

