/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSArray, NSString;

@interface CompletionListGroup : _AITFireProbe
{
    NSString *_title;
    NSArray *_completions;
}

- (id)completions;
- (id)title;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 completions:(id)fp12;

@end

