/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class ContinuousReadingItem, UIImageView, UILabel, UIView;

@interface ContinuousReadingBannerView : _AITFireProbe
{
    UIView *_topHairline;
    UIView *_bottomHairline;
    ContinuousReadingItem *_continuousReadingItem;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_extraTitleLabel;
    UIImageView *_imageView;
}

+ (id)makeHairlineSeparator;
- (void)setImageView:(id)fp8;
- (void)setExtraTitleLabel:(id)fp8;
- (void)setSubtitleLabel:(id)fp8;
- (void)setTitleLabel:(id)fp8;
- (id)continuousReadingItem;
- (float)_textBaseline;
- (BOOL)_hasExtraLine;
- (float)_bannerHeight;
- (void)_updateImage;
- (void)_setUpImage;
- (struct CGSize)_scaledImageSize;
- (void)_updateLabels;
- (id)_bottomHairline;
- (id)_topHairline;
- (id)imageView;
- (id)extraTitleLabel;
- (id)subtitleLabel;
- (id)titleLabel;
- (id)image;
- (void)setImage:(id)fp8;
- (id)extraTitleInfo;
- (void)setExtraTitleInfo:(id)fp8;
- (id)subtitle;
- (void)setSubtitle:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)dealloc;
- (id)initWithContinuousReadingItem:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

