/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class ContinuousReadingBannerView, ContinuousReadingItem, UILabel, UIView;

@interface ContinuousReadingPreviewView : _AITFireProbe
{
    ContinuousReadingItem *_continuousReadingItem;
    UIView *_contentView;
    ContinuousReadingBannerView *_bannerView;
    UIView *_headerView;
    UIView *_contentBackgroundView;
    UILabel *_headerLabel;
}

- (void)setHeaderLabel:(id)fp8;
- (void)setContentBackgroundView:(id)fp8;
- (id)contentBackgroundView;
- (void)setHeaderView:(id)fp8;
- (void)setBannerView:(id)fp8;
- (id)contentView;
- (id)continuousReadingItem;
- (void)_layOutContentView;
- (void)_layOutHeader;
- (void)layoutSubviews;
- (id)headerLabel;
- (id)bannerView;
- (id)headerView;
- (void)setContentView:(id)fp8;
- (float)rubberBandingHeight;
- (float)headerHeight;
- (void)dealloc;
- (id)initWithContinuousReadingItem:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

