/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class ContinuousReadingItem, WBSAutomaticReadingListItem;

@interface ContinuousReadingController : _AITFireProbe
{
    unsigned int _activeDocumentBookmarkID;
    WBSAutomaticReadingListItem *_activeDocumentAutomaticItem;
    ContinuousReadingItem *_currentContinuousItem;
    ContinuousReadingItem *_nextContinuousItem;
    BOOL _unreadReadingListItemsOnly;
}

- (void)setUnreadReadingListItemsOnly:(BOOL)fp8;
- (BOOL)unreadReadingListItemsOnly;
- (id)_nextAutomaticReadingListItem;
- (id)_readingListItemAtIndex:(unsigned int)fp8;
- (void)_updateCachedCurrentAndNextItems;
- (void)_clearCachedCurrentAndNextItems;
- (id)_tabDocument;
- (id)nextReadingListItem;
- (id)currentReadingListItem;
- (void)dealloc;

@end

