/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class WBSAutomaticReadingListItem, WebBookmark;

@interface ContinuousReadingItem : _AITFireProbe
{
    WebBookmark *_readingListBookmark;
    WBSAutomaticReadingListItem *_automaticReadingListItem;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
+ (id)itemWithAutomaticReadingListItem:(id)fp8;
+ (id)itemWithReadingListItem:(id)fp8;
- (id)automaticReadingListItem;
- (void)_setReadingListBookmark:(id)fp8;
- (id)readingListBookmark;
- (void)_readingListItemDidUpdate:(id)fp8;
- (id)_initWithAutomaticReadingListItem:(id)fp8;
- (id)_initWithReadingListItem:(id)fp8;
- (id)_siteNameForReadingListItem;
- (id)extraTitleInfo;
- (BOOL)wantsTopBanner;
- (id)subtitle;
- (id)URL;
- (id)previewText;
- (id)title;
- (int)type;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;

@end

