/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImage;

@interface CrossfadingImageView : _AITFireProbe
{
    UIImage *_fromImage;
    UIImage *_toImage;
    float _progress;
}

- (float)progress;
- (id)toImage;
- (id)fromImage;
- (void)setProgress:(float)fp8;
- (void)setToImage:(id)fp8;
- (void)setFromImage:(id)fp8;
- (void)_updateCrossfade;

@end

