/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DynamicBarAnimatorDelegate <NSObject>
- (BOOL)dynamicBarAnimator:(id)fp8 canHideBarsByDraggingWithOffset:(float)fp12;
@end

