/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class CADisplayLink;

@interface DynamicBarAnimator : _AITFireProbe
{
    float _topBarHeightForState[2];
    float _bottomBarOffsetForState[2];
    BOOL _dragging;
    CADisplayLink *_displayLink;
    float _targetTopBarHeight;
    float _unroundedTopBarHeight;
    float _lastUnroundedTopBarHeight;
    BOOL _didHideBarsByMoving;
    BOOL _didHideOrShowBarsExplicitly;
    float _lastOffset;
    int _state;
    float _topBarHeight;
    float _bottomBarOffset;
    id _target;
    SEL _action;
    float _minimumTopBarHeight;
    float _maximumBottomBarOffset;
    id <DynamicBarAnimatorDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (float)maximumBottomBarOffset;
- (float)minimumTopBarHeight;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (void)setTarget:(id)fp8;
- (id)target;
- (float)bottomBarOffset;
- (float)topBarHeight;
- (int)state;
- (void)setMaximumBottomBarOffset:(float)fp8;
- (void)setMinimumTopBarHeight:(float)fp8;
- (void)setBottomBarOffset:(float)fp8 forState:(int)fp12;
- (void)setTopBarHeight:(float)fp8 forState:(int)fp12;
- (void)endDraggingWithTargetOffset:(float)fp8 velocity:(float)fp12;
- (void)updateDraggingWithOffset:(float)fp8;
- (void)beginDraggingWithOffset:(float)fp8;
- (void)_updateDisplayLink;
- (void)_displayLinkFired:(id)fp8;
- (float)_constrainTopBarHeight:(float)fp8;
- (BOOL)canTransitionToState:(int)fp8;
- (int)targetState;
- (void)_updateOutputs;
- (float)_topBarHeightForBottomBarOffset:(float)fp8;
- (float)_bottomBarOffsetForTopBarHeight:(float)fp8;
- (void)_transitionToSteadyState;
- (void)attemptTransitionToState:(int)fp8 animated:(BOOL)fp12;
- (void)_moveBarsWithDelta:(float)fp8;
- (void)dealloc;
- (id)init;

@end

