/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface EditableTableViewCellLayoutManager : _AITFireProbe
{
}

+ (id)sharedLayoutManager;
- (id)editableTextFieldForCell:(id)fp8;
- (void)layoutSubviewsOfCell:(id)fp8;

@end

