/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class EllipsedTextViewURLSchemeView, NSString, UIColor;

@interface EllipsedTextView : _AITFireProbe
{
    id _delegate;
    BOOL _truncatesURLScheme;
    UIColor *_textColor;
    EllipsedTextViewURLSchemeView *_schemeView;
    float _fadeAdjustment;
    NSString *_text;
}

+ (float)placeholderWidth;
+ (id)placeholderColor;
+ (id)placeholderText;
+ (id)defaultAddressColor;
+ (float)offsetForSchemeInAddressString:(id)fp8;
+ (id)urlFont;
- (void)drawRect:(struct CGRect)fp8;
- (void)setText:(id)fp8;
- (id)textColor;
- (void)setTextColor:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)schemeView;
- (BOOL)truncatesURLScheme;
- (void)setTruncatesURLScheme:(BOOL)fp8;
- (void)browserControllerDidEndRotating;
- (void)browserControllerDidStartRotating;
- (void)setFadeAdjustment:(float)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setNeedsDisplay;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

