/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class EllipsedTextView, NSString;

@interface EllipsedTextViewURLSchemeView : _AITFireProbe
{
    EllipsedTextView *_parentEllipsedTextView;
    NSString *_URLString;
}

- (void)drawRect:(struct CGRect)fp8;
- (void)setTextFromURLString:(id)fp8;
- (void)dealloc;
- (void)setParentEllipsedTextView:(id)fp8;

@end

