/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSString, UIImage;

@interface EmptyCollectionLabel : _AITFireProbe
{
    NSString *_text;
    struct __CTFramesetter *_framesetter;
    struct CGSize _textSizePortrait;
    struct CGSize _textSizeLandscape;
    UIImage *_replacementImage;
    unsigned int _replacementLocation;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (struct CGSize)sizeForOrientation:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8 text:(id)fp24 font:(id)fp28 replacingString:(id)fp32 withImage:(id)fp36;

@end

