/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface FadeView : _AITFireProbe
{
    id _target;
    SEL _action;
}

- (void)setAction:(SEL)fp8;
- (SEL)action;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (id)initWithFrame:(struct CGRect)fp8;

@end

