/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "CompletionItem-Protocol.h"

@class NSString;

@interface FindOnPageCompletionItem : _AITFireProbe <CompletionItem>
{
    id <UIWebFindOnPageHighlighter> _highlighter;
    NSString *_string;
    unsigned int _numberOfMatches;
}

- (unsigned int)numberOfMatches;
- (void)auditAcceptedCompletionWithRank:(unsigned int)fp8;
- (void)acceptCompletionWithSearchAction:(id)fp(null) goToURLAction:(void)fp8 findOnPageAction:(id)fp(null);
- (void)configureCompletionTableViewCell:(id)fp8;
- (id)completionTableViewCell;
- (id)completionTableViewCellReuseIdentifier;
- (void)dealloc;
- (id)initWithString:(id)fp8 numberOfMatches:(unsigned int)fp12 highlighter:(id)fp16;

@end

