/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BrowserPanel-Protocol.h"
#import "UIKeyInput-Protocol.h"

@class NSArray, UIActivityIndicatorView, UIBarButtonItem, UILabel;

@interface FindOnPagePanel : _AITFireProbe <BrowserPanel, UIKeyInput>
{
    BOOL _requiresKeyboard;
    NSArray *_toolbarItems;
    UILabel *_currentResultLabel;
    UIBarButtonItem *_previousButtonItem;
    UIBarButtonItem *_nextButtonItem;
    UIActivityIndicatorView *_indicatorView;
    BOOL _useActivityView;
    id <UIWebFindOnPageHighlighter> _highlighter;
}

- (BOOL)useActivityView;
- (void)setHighlighter:(id)fp8;
- (id)highlighter;
- (void)setUseActivityView:(BOOL)fp8;
- (void)dealloc;
- (void)deleteBackward;
- (void)insertText:(id)fp8;
- (BOOL)hasText;
- (BOOL)canBecomeFirstResponder;
- (void)setRequiresKeyboard:(BOOL)fp8;
- (BOOL)_requiresKeyboardWhenFirstResponder;
- (void)updateUI;
- (id)findTextField;
- (id)inputAccessoryView;
- (id)toolbarItems;
- (void)_nextTapped:(id)fp8;
- (void)_previousTapped:(id)fp8;
- (void)_done;
- (BOOL)shouldShowToolbarInFullscreen;
- (BOOL)shouldHideOnSuspend;
- (BOOL)ignoresPrivateBrowsingStyle;
- (int)pausesPages;
- (int)panelType;
- (id)_currentResultLabel;
- (BOOL)_willShowActivityIndicator;
- (id)initWithHighlighter:(id)fp8;

@end

