/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionProvider.h"

@interface FindOnPageCompletionProvider : CompletionProvider
{
    id <UIWebFindOnPageHighlighter> _highlighter;
}

- (id)highlighter;
- (void)setStringToComplete:(id)fp8;
- (id)completionsForString:(id)fp8;
- (void)dealloc;
- (id)initWithHighlighter:(id)fp8;

@end

