/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol FolderPickerViewControllerDelegate
- (void)folderPicker:(id)fp8 pickedFolder:(id)fp12 withSelectedCell:(id)fp16;
@end

