/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PopoverSizingTableViewController.h"

@class NSArray, NSSet, WebBookmark, WebBookmarkCollection;

@interface FolderPickerViewController : PopoverSizingTableViewController
{
    id <FolderPickerViewControllerDelegate> _delegate;
    WebBookmarkCollection *_collection;
    NSSet *_hiddenFolderIdentifiers;
    WebBookmark *_parentBookmark;
    NSArray *_bookmarkFolders;
    int _selectedFolderIndex;
}

- (float)minimumHeightInPopoverView;
- (void)_bookmarksDidReload;
- (void)_bookmarksChanged;
- (id)_bookmarkFolders;
- (void)willShowForParentBookmark:(id)fp8 hiddenFolderIdentifiers:(id)fp12;
- (void)_cancel;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)_tintedFavoritesFolderIcon;
- (id)_tintedFolderIcon;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)loadView;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 bookmarkCollection:(id)fp12;

@end

