/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PageLoadTestRunner.h"

@class NSString;

@interface FormAutoFillTestRunner : PageLoadTestRunner
{
    NSString *_testsDirectory;
    NSString *_scratchDirectory;
}

- (void)setScratchDirectory:(id)fp8;
- (id)scratchDirectory;
- (id)testsDirectory;
- (void)finishedTestPage:(id)fp8;
- (id)_descriptiveNameForPage:(id)fp8;
- (void)_compareActualContent:(id)fp8 toExpectedContentForPage:(id)fp12;
- (void)dealloc;
- (void)setTestsDirectory:(id)fp8;

@end

