/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface HighlightRecognizer : _AITFireProbe
{
    unsigned int _numberOfTouches;
    id _highlightTarget;
    SEL _highlightAction;
}

- (void)setHighlightAction:(SEL)fp8;
- (SEL)highlightAction;
- (void)setHighlightTarget:(id)fp8;
- (id)highlightTarget;
- (void)reset;
- (unsigned int)numberOfTouches;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (id)initWithTarget:(id)fp8 action:(SEL)fp12;

@end

