/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PopoverSizingTableViewController.h"

#import "BookmarksPanelStateRestoring-Protocol.h"
#import "BookmarksToolbarItemProvider-Protocol.h"

@class NSArray, UIBarButtonItem;

@interface HistoryTableViewController : PopoverSizingTableViewController <BookmarksPanelStateRestoring, BookmarksToolbarItemProvider>
{
    NSArray *_browsingSessions;
    UIBarButtonItem *_clearHistoryButton;
    id <HistoryTableViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)safari_tableViewScrollPositionSaveIdentifier;
- (id)collectionType;
- (void)restoreScrollPosition:(float)fp8;
- (float)currentScrollPosition;
- (BOOL)restoreStateWithDictionary:(id)fp8;
- (id)currentStateDictionary;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)_clearHistory;
- (void)updateClearHistoryButtonEnable;
- (id)bookmarksRightBarButtonItem;
- (id)bookmarksNavigationController;
- (void)dealloc;
- (id)init;
- (void)historyChanged:(id)fp8;

@end

