/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSMutableArray, NSString, NSURL;

@interface HistoryItem : _AITFireProbe
{
    NSString *_URLString;
    NSString *_title;
    NSMutableArray *_redirectURLStrings;
    NSMutableArray *_autocompleteTriggers;
    struct Vector<int, 0, WTF::CrashOnOverflow> _dailyVisitCounts;
    struct Vector<int, 0, WTF::CrashOnOverflow> _weeklyVisitCounts;
    NSURL *_URL;
    BOOL _lastVisitWasHTTPNonGet;
    BOOL _lastVisitWasFailure;
    unsigned int _visitCount;
    double _lastVisitedTimeInterval;
}

+ (id)mutationQueue;
+ (void)initialize;
- (BOOL)lastVisitWasFailure;
- (BOOL)lastVisitWasHTTPNonGet;
- (double)lastVisitedTimeInterval;
- (unsigned int)visitCount;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)writeToBinaryPropertyListObjectStream:(struct BinaryPropertyListObjectStream *)fp8;
- (id)stringForUserTypedDomainExpansion;
- (id)_URL;
- (float)topSitesScoreAtTime:(double)fp8;
- (void)mergeAutoCompleteHintsFromItem:(id)fp8;
- (id)copyRedirectURLStrings;
- (void)_addRedirectURLFromMutationQueue:(id)fp8;
- (void)addRedirectURL:(id)fp8;
- (void)redirectedToURL:(id)fp8;
- (void)recordVisitWithTitle:(id)fp8 incrementVisitCount:(BOOL)fp12;
- (void)_collapseDailyVisitsToWeekly;
- (void)_padDailyCountsForNewVisitOnTime:(double)fp8;
- (id)autocompleteTriggers;
- (BOOL)addAutocompleteTrigger:(id)fp8;
- (unsigned long)getWeeklyVisitCountsPtr:(const int **)fp8;
- (unsigned long)getDailyVisitCountsPtr:(const int **)fp8;
- (void)setLastVisitWasFailure:(BOOL)fp8;
- (void)setLastVisitWasHTTPNonGet:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (id)copyTitle;
- (id)title;
- (id)copyURLString;
- (id)URLString;
- (void)dealloc;
- (id)initWithURL:(id)fp8 title:(id)fp12 HTTPNonGet:(BOOL)fp16 failure:(BOOL)fp20;
- (id)initWithDictionaryRepresentation:(id)fp8;

@end

