/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface NavigationBarLabelsContainer : _AITFireProbe
{
    BOOL _shouldAnimateBoundsChanges;
}

- (void)setShouldAnimateBoundsChanges:(BOOL)fp8;
- (BOOL)shouldAnimateBoundsChanges;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;

@end

