/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol NavigationBarDelegate
- (void)navigationBarCancelButtonWasTapped:(id)fp8;
- (void)navigationBarReaderButtonWasTapped:(id)fp8;
- (void)navigationBarBackdropDidApplySettings:(id)fp8;
- (void)navigationBarURLWasTapped:(id)fp8;
- (void)compressedNavigationBarWasTapped:(id)fp8;
@end

