/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NavigationBar;

@interface NavigationBarBackdrop : _AITFireProbe
{
    NavigationBar *_navigationBar;
}

- (void)setNavigationBar:(id)fp8;
- (id)navigationBar;
- (void)applySettings:(id)fp8;

@end

