/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol NavigationSnapshotControllerDelegate
- (BOOL)navigationSnapshotControllerShouldDelaySnapshotForOngoingLoad:(id)fp8;
- (BOOL)navigationSnapshotController:(id)fp8 shouldReceiveTouch:(id)fp12;
- (id)navigationSnapshotControllerDocumentToSnapshot:(id)fp8;
- (void)navigationSnapshotControllerWillUnhideWebContent:(id)fp8;
- (void)navigationSnapshotController:(id)fp8 willNavigateAtEndOfGesture:(BOOL)fp12 toHistoryPosition:(int)fp16;
- (void)navigationSnapshotControllerGestureEnded:(id)fp8 willNavigate:(BOOL)fp12 toHistoryPosition:(int)fp16;
- (void)navigationSnapshotControllerGestureBegan:(id)fp8;
@end

