/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "FluidProgressViewDelegate-Protocol.h"
#import "_UIBasicAnimationFactory-Protocol.h"

@class BrowserToolbar, CrossfadingImageView, DimmingButton, FluidProgressView, NSAttributedString, NavigationBarBackdrop, NavigationBarItem, NavigationBarLabelsContainer, NavigationBarReaderButton, NavigationBarURLButton, UIButton, UIImageView, UILabel, UIView, UnifiedField, _UIBackdropViewSettings;

@interface NavigationBar : _AITFireProbe <_UIBasicAnimationFactory, FluidProgressViewDelegate>
{
    UIButton *_compressedBarButton;
    UIView *_controlsContainer;
    NavigationBarLabelsContainer *_labelsContainer;
    UIView *_labelScalingContainer;
    UILabel *_URLLabel;
    UILabel *_expandedURLLabel;
    float _URLWidth;
    float _URLHeight;
    float _expandedURLWidth;
    float _expandedURLHeight;
    float _offsetOfURLInExpandedURL;
    UIView *_URLContainer;
    UIImageView *_URLFadeOut;
    UIView *_fakeTextFieldSelectionView;
    float _fakeSelectionStartOffset;
    float _fakeSelectionEndOffset;
    UIButton *_fakeClearButton;
    CrossfadingImageView *_searchIndicator;
    CrossfadingImageView *_lockView;
    CrossfadingImageView *_activeURLLabelAccessory;
    float _activeURLLabelAccessorySpacing;
    float _activeURLLabelAccessorySquishedSpacing;
    float _activeURLLabelAccessoryVerticalOffset;
    NavigationBarURLButton *_URLOutline;
    FluidProgressView *_progressView;
    NavigationBarBackdrop *_backdrop;
    UIView *_separator;
    BOOL _lockViewNeedsUpdate;
    NSAttributedString *_attributedTextWhenExpanded;
    NavigationBarReaderButton *_readerButton;
    DimmingButton *_stopButton;
    DimmingButton *_reloadButton;
    UIButton *_cancelButton;
    float _cancelButtonIntrinsicWidth;
    BOOL _usingLightControls;
    BOOL _controlsHidden;
    BOOL _expanded;
    BOOL _usesUnscaledBackdrop;
    BOOL _backdropGroupDisabled;
    BOOL _suppressesBlur;
    NavigationBarItem *_item;
    unsigned int _tintStyle;
    BrowserToolbar *_buttonBar;
    _UIBackdropViewSettings *_customBackdropSettings;
    UnifiedField *_textField;
    id <NavigationBarDelegate> _delegate;
    float _contentUnderStatusBarHeight;
    UIView *_inputAccessoryView;
}

+ (float)separatorHeight;
+ (float)minimumHeight;
+ (float)defaultHeight;
- (void)setInputAccessoryView:(id)fp8;
- (id)inputAccessoryView;
- (BOOL)suppressesBlur;
- (float)contentUnderStatusBarHeight;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)isBackdropGroupDisabled;
- (BOOL)usesUnscaledBackdrop;
- (id)textField;
- (BOOL)isExpanded;
- (id)customBackdropSettings;
- (BOOL)areControlsHidden;
- (id)buttonBar;
- (void)setUsingLightControls:(BOOL)fp8;
- (BOOL)isUsingLightControls;
- (unsigned int)tintStyle;
- (id)item;
- (BOOL)canBecomeFirstResponder;
- (id)_timingFunctionForAnimation;
- (id)_basicAnimationForView:(id)fp8 withKeyPath:(id)fp12;
- (void)_configureStopReloadButtonTintedImages;
- (void)_updateControlTints;
- (void)backdropDidApplySettings:(id)fp8;
- (void)setUpdatesBackdrop:(BOOL)fp8;
- (BOOL)updatesBackdrop;
- (id)_lockImageUsingMiniatureVersion:(BOOL)fp8;
- (id)_lockImageWithTint:(id)fp8 usingMiniatureVersion:(BOOL)fp12;
- (id)_untintedLockImageUsingMiniatureVersion:(BOOL)fp8;
- (id)_EVCertLockAndTextColor;
- (void)_updateURLOutlineColor;
- (void)_updateSeparatorAlpha;
- (void)setBackdropGroupDisabled:(BOOL)fp8;
- (void)setSuppressesBlur:(BOOL)fp8;
- (void)setContentUnderStatusBarHeight:(float)fp8;
- (void)_updateShowsSearchIndicator;
- (void)_updateSearchIndicator;
- (void)_updateTextMetrics;
- (void)_updateTextColor;
- (id)_placeholderColor;
- (void)_updateReaderButtonSelected;
- (void)_updateReaderButtonTint;
- (void)_updateReaderButtonVisibility;
- (void)_updateReaderButtonVisibilityAnimated:(BOOL)fp8 adjustURLLabels:(BOOL)fp12;
- (void)_updateLockIconHasEVCertificateTint;
- (void)_updateShowsLockIcon;
- (void)_updateLockViewIfNeeded;
- (void)_updateActiveURLLabelAccessory;
- (struct CGRect)URLOutlineFrameInNavigationBarSpace;
- (void)setControlsHidden:(BOOL)fp8;
- (void)setExpanded:(BOOL)fp8 textFieldSelectionRange:(struct _NSRange)fp12;
- (void)_updateFakeViews;
- (void)setExpanded:(BOOL)fp8;
- (void)_updateText;
- (id)_expandedURLLabelParagraphStyle;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (float)_textFieldTopMargin;
- (void)_updateTextFieldFrame;
- (float)_minimumXForLabelOfWidth:(float)fp8 centeredInOutlineOfWidth:(float)fp12 leftAlignedToMinimumX:(float)fp16 maximumX:(float)fp20;
- (void)_updateBackdropFrame;
- (void)fluidProgressViewDidShowProgress:(id)fp8;
- (void)fluidProgressViewWillShowProgress:(id)fp8;
- (void)_updateProgressView;
- (void)_updateStopReloadButtonShowsStop;
- (void)_updateStopReloadButtonVisibility;
- (void)_transitionFromView:(id)fp8 toView:(id)fp12 animated:(BOOL)fp16;
- (float)_URLControlsAlpha;
- (float)_squishTransformFactor;
- (void)_cancelButtonTapped:(id)fp8;
- (void)_readerButtonTapped:(id)fp8;
- (void)_URLTapped:(id)fp8;
- (void)_compressedBarTapped;
- (void)_stopButtonPressed;
- (void)_reloadButtonPressed;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)_fadeOutImageWithSize:(struct CGSize)fp8 opaquePoint:(struct CGPoint)fp16 transparentPoint:(struct CGPoint)fp24 leftCapWidth:(float)fp32 topCapWidth:(float)fp36;
- (id)_dimmingButtonWithAction:(SEL)fp8;
- (id)_newNavigationButtonWithImage:(id)fp8 insets:(struct UIEdgeInsets)fp12 action:(SEL)fp28;
- (float)visualHeight;
- (void)setCustomBackdropSettings:(id)fp8;
- (void)setUsesUnscaledBackdrop:(BOOL)fp8;
- (void)setTintStyle:(unsigned int)fp8;
- (void)_updateBackdropStyle;
- (id)_backdropInputSettings;
- (void)setItem:(id)fp8;

@end

