/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "_UINavigationInteractiveTransitionBaseDelegate-Protocol.h"

@class NSDate, NSTimer, UIImageView, UIScrollView, UIView, _UINavigationInteractiveTransitionBase;

@interface NavigationSnapshotController : _AITFireProbe <UIGestureRecognizerDelegate, _UINavigationInteractiveTransitionBaseDelegate>
{
    UIScrollView *_webContentView;
    UIView *_parentView;
    UIImageView *_leftShadow;
    UIView *_dimmingView;
    UIView *_transitionContainerView;
    UIView *_presentedSnapshot;
    NSTimer *_snapshotExpirationTimer;
    NSTimer *_snapshotDelayDuringLoadTimer;
    NSDate *_startTimeOfDelayDuringLoadTimer;
    NSTimer *_samePageNavigationExpirationTimer;
    NSDate *_startTimeOfSamePageNavigation;
    BOOL _showWebContentAfterNavigationAnimation;
    _UINavigationInteractiveTransitionBase *_backTransitionController;
    _UINavigationInteractiveTransitionBase *_forwardTransitionController;
    id <NavigationSnapshotControllerDelegate> _delegate;
    BOOL _navigationGestureActive;
    BOOL _webContentHidden;
}

- (BOOL)isWebContentHidden;
- (BOOL)isNavigationGestureActive;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)transitionDidComplete:(BOOL)fp8 toPosition:(int)fp12 fromView:(id)fp16 toView:(id)fp20;
- (id)_toViewForTransitionToPosition:(int)fp8;
- (BOOL)interactiveTransition:(id)fp8 gestureRecognizer:(id)fp12 shouldReceiveTouch:(id)fp16;
- (id)gestureRecognizerForInteractiveTransition:(id)fp8 WithTarget:(id)fp12 action:(SEL)fp16;
- (BOOL)interactiveTransition:(id)fp8 gestureRecognizer:(id)fp12 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp16;
- (BOOL)shouldBeginInteractiveTransition:(id)fp8;
- (void)startInteractiveTransition:(id)fp8;
- (void)_invalidateAllSnapshotTimers;
- (void)_invalidateSnapshotExpirationTimer;
- (void)_snapshotExpirationTimerFired:(id)fp8;
- (void)_startSnapshotExpirationTimer;
- (void)_invalidateSnapshotDelayDuringLoadTimer;
- (void)snapshotDocumentDidFinishLoading;
- (void)_snapshotDelayDuringLoadTimerFired:(id)fp8;
- (void)_startSnapshotDelayDuringLoadTimer;
- (BOOL)_shouldStartSnapshotDelayDuringLoadTimer;
- (void)setSnapshot:(id)fp8 forTabDocument:(id)fp12;
- (float)_screenCenterX;
- (void)_showWebContentHidingPresentedSnapshotAnimated:(BOOL)fp8;
- (void)_invalidateSamePageNavigationExpirationTimer;
- (void)_samePageNavigationExpirationTimerFired:(id)fp8;
- (void)_startSamePageNavigationExpirationTimer;
- (void)showWebContentHiddenBySamePageNavigation;
- (void)showWebContentHiddenByNavigationWithDelayHeuristics;
- (void)showWebContentHiddenByNavigationAnimated:(BOOL)fp8;
- (id)_topViewBeforeGestureBegan;
- (id)_snapshotForPosition:(int)fp8;
- (void)_removeNavigationSnapshot:(id)fp8;
- (int)_historyPositionForTransitionController:(id)fp8;
- (void)dealloc;
- (id)initWithSnapshotParentView:(id)fp8 webContentView:(id)fp12 gestureRecognizerView:(id)fp16;

@end

