/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImageView;

@interface NavigationBarReaderButton : _AITFireProbe
{
    UIImageView *_glyphView;
    UIImageView *_glyphKnockoutView;
    BOOL _drawsLightGlyph;
}

- (BOOL)drawsLightGlyph;
- (void)setSelected:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setDrawsLightGlyph:(BOOL)fp8;
- (struct CGSize)visibleSize;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

