/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class FluidProgressView, NSString, NavigationBar;

@interface NavigationBarItem : _AITFireProbe
{
    NavigationBar *_navigationBar;
    BOOL _showsLockIcon;
    BOOL _showsSearchIndicator;
    BOOL _showsStopReloadButtons;
    BOOL _stopReloadButtonShowsStop;
    BOOL _textHasEVCertificateTint;
    BOOL _lockIconHasEVCertificateTint;
    BOOL _readerButtonSelected;
    BOOL _showsReaderButton;
    BOOL _overrideBarStyleForSecurityWarning;
    NSString *_text;
    NSString *_textWhenExpanded;
    unsigned int _startIndexOfTextInExpandedText;
    FluidProgressView *_progressView;
    id _target;
    SEL _reloadAction;
    SEL _stopAction;
}

- (void)setStopAction:(SEL)fp8;
- (SEL)stopAction;
- (void)setReloadAction:(SEL)fp8;
- (SEL)reloadAction;
- (void)setTarget:(id)fp8;
- (id)target;
- (id)progressView;
- (BOOL)overrideBarStyleForSecurityWarning;
- (BOOL)showsReaderButton;
- (BOOL)readerButtonSelected;
- (BOOL)lockIconHasEVCertificateTint;
- (BOOL)textHasEVCertificateTint;
- (BOOL)stopReloadButtonShowsStop;
- (BOOL)showsStopReloadButtons;
- (BOOL)showsSearchIndicator;
- (BOOL)showsLockIcon;
- (unsigned int)startIndexOfTextInExpandedText;
- (id)textWhenExpanded;
- (id)text;
- (void)dealloc;
- (void)_setNavigationBar:(id)fp8;
- (void)setProgressView:(id)fp8;
- (void)setShowsReaderButton:(BOOL)fp8;
- (void)setLockIconHasEVCertificateTint:(BOOL)fp8;
- (void)setTextHasEVCertificateTint:(BOOL)fp8;
- (void)setOverrideBarStyleForSecurityWarning:(BOOL)fp8;
- (void)setReaderButtonSelected:(BOOL)fp8;
- (void)setStopReloadButtonShowsStop:(BOOL)fp8;
- (void)setShowsStopReloadButtons:(BOOL)fp8;
- (void)setShowsSearchIndicator:(BOOL)fp8;
- (void)setShowsLockIcon:(BOOL)fp8;
- (void)setText:(id)fp8 textWhenExpanded:(id)fp12 startIndex:(unsigned int)fp16;
- (id)init;

@end

