/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSString;

@interface OpenInOtherAppActivityViewController : _AITFireProbe
{
    NSString *_filePath;
}

+ (id)_activityItemsForFilePath:(id)fp8 andUTI:(id)fp12;
+ (id)_applicationsForDocumentProxy:(id)fp8;
- (void)setFilePath:(id)fp8;
- (id)filePath;
- (void)_prepareActivity:(id)fp8;
- (void)dealloc;
- (id)initWithFilePath:(id)fp8 andUTI:(id)fp12;

@end

