/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "LSOpenResourceOperationDelegate-Protocol.h"

@class LSApplicationProxy, NSString;

@interface OpenWithAppUIActivity : _AITFireProbe <LSOpenResourceOperationDelegate>
{
    LSApplicationProxy *_appProxy;
    NSString *_filePath;
}

- (void)openResourceOperation:(id)fp8 didFinishCopyingResource:(id)fp12;
- (void)performActivity;
- (BOOL)canPerformWithActivityItems:(id)fp8;
- (id)_activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;
- (id)initWithApplicationIdentifier:(id)fp8 andFilePath:(id)fp12;

@end

