/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSMutableArray, NSOutputStream, NSString;

@interface PageLoadTestRunner : _AITFireProbe
{
    BOOL _started;
    NSMutableArray *_pageLoadArray;
    double _savedDefaultTimeoutInterval;
    NSOutputStream *_logStream;
    NSString *_logFile;
    unsigned int _skipCount;
    BOOL _disableProgressBar;
    BOOL _failFast;
    double _pageTimeout;
    double _pageActionInterval;
    double _pageRestInterval;
    int _cacheClearDirective;
    BOOL _collectHeapStatistics;
    BOOL _checkForWorldLeaks;
    id <PageLoadTestRunnerDelegate> _delegate;
}

+ (CDAnonymousStruct2)heapStatistics;
+ (id)worldLeaksString;
+ (BOOL)closingBrowserWindowsForWorldLeakTest;
+ (void)addLeakToArray:(id)fp8 count:(int)fp12 name:(id)fp16;
- (void)setPageActionInterval:(double)fp8;
- (double)pageActionInterval;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCheckForWorldLeaks:(BOOL)fp8;
- (BOOL)checkForWorldLeaks;
- (void)setCollectHeapStatistics:(BOOL)fp8;
- (BOOL)collectHeapStatistics;
- (void)setCacheClearDirective:(int)fp8;
- (int)cacheClearDirective;
- (void)setPageRestInterval:(double)fp8;
- (double)pageRestInterval;
- (void)setPageTimeout:(double)fp8;
- (double)pageTimeout;
- (void)setFailFast:(BOOL)fp8;
- (BOOL)failFast;
- (void)setDisableProgressBar:(BOOL)fp8;
- (BOOL)disableProgressBar;
- (void)setSkipCount:(unsigned int)fp8;
- (unsigned int)skipCount;
- (void)setLogFile:(id)fp8;
- (id)logFile;
- (BOOL)checkForWorldLeaksNow;
- (void)checkForWorldLeaksSoon;
- (void)closeBrowserWindowsAndFinishCheckingForWorldLeaks;
- (BOOL)finishCheckingForWorldLeaks;
- (void)closeBrowserWindows;
- (void)clearCacheWithURL:(id)fp8;
- (void)log:(id)fp8;
- (void)finishedTestPage:(id)fp8;
- (void)startingTestPage:(id)fp8;
- (void)finishedTestRunner;
- (void)startingTestRunner;
- (id)dismissAlert;
- (void)_handleActionTimer:(id)fp8;
- (BOOL)performActionForPage:(id)fp8;
- (BOOL)startPageAction:(id)fp8;
- (void)finishPage:(id)fp8 stats:(id)fp12 error:(id)fp16;
- (void)_checkRedirect:(id)fp8;
- (void)_pageRestExpired:(id)fp8;
- (void)_pageTimeoutExpired:(id)fp8;
- (id)_pageLoadForTabDocument:(id)fp8;
- (void)finish;
- (void)_startNextPageNow;
- (void)startNextPage;
- (void)start;
- (_Bool)loadTestSuiteFile:(id)fp8;
- (void)removeURLsInRange:(struct _NSRange)fp8;
- (void)addPageURL:(id)fp8;
- (void)setTestOptions:(id)fp8;
- (void)setExistingProperty:(id)fp8 to:(id)fp12;
- (void)dealloc;
- (id)init;

@end

