/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSDate, NSError, NSTimer;

@interface PageLoadTestStatistics : _AITFireProbe
{
    int _framesToLoad;
    int _onloadEventsHandled;
    BOOL _pendingResourceLoad;
    NSTimer *_waitForNewPageLoadEventsTimer;
    NSDate *_firstVisualLayoutDate;
    NSDate *_loadStartDate;
    NSDate *_lastOnloadEventDate;
    NSDate *_mainFrameLoadDate;
    NSDate *_lastResourceLoadDate;
    NSDate *_lastPageLoadEventDate;
    NSError *_loadError;
    id _callbackBlock;
}

+ (void)setRestInterval:(double)fp8;
- (void)setPageLoadTestStatisticsCallbackBlock:(id)fp(null);
- (id)pageLoadTestStatisticsCallbackBlock;
- (void)setPageLoadError:(id)fp8;
- (id)pageLoadError;
- (void)setPageLoadLastPageLoadEventDate:(id)fp8;
- (id)pageLoadLastPageLoadEventDate;
- (void)setPageLoadLastResourceLoadDate:(id)fp8;
- (id)pageLoadLastResourceLoadDate;
- (void)setPageLoadMainFrameLoadDate:(id)fp8;
- (id)pageLoadMainFrameLoadDate;
- (void)setPageLoadLastOnloadEventDate:(id)fp8;
- (id)pageLoadLastOnloadEventDate;
- (void)setPageLoadStartDate:(id)fp8;
- (id)pageLoadStartDate;
- (void)setPageLoadFirstVisualLayoutDate:(id)fp8;
- (id)pageLoadFirstVisualLayoutDate;
- (void)_scheduleWaitForNewPageLoadEventsTimer;
- (void)_cancelWaitForNewPageLoadEventsTimer;
- (BOOL)_pageLoadEventsAreStillPending;
- (void)_pageLoadFinishedForTests;
- (void)_waitForNewPageLoadEventsTimerFired:(id)fp8;
- (void)_maybePageLoadFinishedForTests;
- (void)finishedLoadingFrameWithError:(id)fp8 isMainFrame:(BOOL)fp12;
- (void)startedLoadingFrame:(BOOL)fp8;
- (void)startedPageLoad;
- (void)startedLoadingResources;
- (void)finishedLoadingResources;
- (void)finishedLoadingMainFrame;
- (void)finishedFirstVisualLayout;
- (void)handledOnloadEvents;
- (void)dealloc;
- (id)initWithCallback:(id)fp(null);

@end

