/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BrowserPanel-Protocol.h"

@class BrowserPrintPageRenderer, WebFrame;

@interface PrintBrowserPanel : _AITFireProbe <BrowserPanel>
{
    BrowserPrintPageRenderer *_pageRenderer;
    WebFrame *_webFrame;
}

- (id)printControllerWithBrowserView:(id)fp8 URLString:(id)fp12 pageTitle:(id)fp16 printFooter:(BOOL)fp20;
- (BOOL)ignoresPrivateBrowsingStyle;
- (int)pausesPages;
- (int)panelType;
- (void)dealloc;
- (id)initWithWebFrame:(id)fp8;

@end

