/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIBarButtonItem, UIToolbar;

@interface PrivateBrowsingToolbar : _AITFireProbe
{
    UIToolbar *_leftToolbar;
    UIToolbar *_rightToolbar;
    UIBarButtonItem *_privateBrowsingButton;
}

+ (id)_newToolbarWithItems:(id)fp8;
- (void)dealloc;
- (void)_commonInit;
- (id)initWithFrame:(struct CGRect)fp8 inputViewStyle:(int)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

