/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BackgroundDrawing-Protocol.h"

@class AddressView, NSMutableDictionary, ReaderButton, UIImageView;

@interface ProgressView : _AITFireProbe <BackgroundDrawing>
{
    AddressView *_delegate;
    float _progress;
    BOOL _isShowingProgress;
    BOOL _drawActiveBackground;
    BOOL _usesPrivateBrowsingStyle;
    BOOL _readerButtonPressed;
    ReaderButton *_readerButton;
    UIImageView *_backgroundImageView;
    UIImageView *_progressImageView;
    NSMutableDictionary *_imagesWithReaderText;
    int _readerButtonState;
}

- (int)readerButtonState;
- (id)readerButton;
- (void)drawBackgroundInContext:(struct CGContext *)fp8;
- (void)setDelegate:(id)fp8;
- (void)setUsesPrivateBrowsingStyle:(BOOL)fp8;
- (void)layoutSubviews;
- (void)_updateImageViewGeometry:(id)fp8 forProgress:(float)fp12 flip:(BOOL)fp16;
- (id)_progressImage;
- (id)_backgroundImage;
- (float)readerButtonWidth;
- (id)_imageForReaderButtonState:(int)fp8 withPressedHighlight:(BOOL)fp12 progressFill:(BOOL)fp16;
- (id)_imageNameForReaderButtonState:(int)fp8 withPressedHighlight:(BOOL)fp12 progressFill:(BOOL)fp16;
- (id)_textAttributesForReaderButtonState:(int)fp8;
- (void)setReaderButtonState:(int)fp8;
- (void)_setReaderButtonPressed:(BOOL)fp8;
- (float)progress;
- (void)setProgress:(float)fp8;
- (void)_updateShowsProgress;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

