/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PageLoadTestRunner.h"

@class NSMutableDictionary, NSString;

@interface PurplePageLoadTestRunner : PageLoadTestRunner
{
    NSMutableDictionary *_pptResults;
    NSString *_testName;
    BOOL _showLoadTime;
    BOOL _showFirstVisualLayoutTime;
    BOOL _showRenderTime;
    BOOL _showRenderFps;
}

- (void)setShowRenderFps:(BOOL)fp8;
- (BOOL)showRenderFps;
- (void)setShowRenderTime:(BOOL)fp8;
- (BOOL)showRenderTime;
- (void)setShowFirstVisualLayoutTime:(BOOL)fp8;
- (BOOL)showFirstVisualLayoutTime;
- (void)setShowLoadTime:(BOOL)fp8;
- (BOOL)showLoadTime;
- (void)setTestName:(id)fp8;
- (id)testName;
- (void)collectPPTResults;
- (void)pptResultFor:(id)fp8 measure:(id)fp12 time:(double)fp16;
- (void)pptResultFor:(id)fp8 measure:(id)fp12 value:(double)fp16 units:(id)fp24;
- (void)finishedTestRunner;
- (void)startingTestRunner;
- (void)dealloc;
- (id)initRenderTestWithName:(id)fp8 showRenderTime:(BOOL)fp12 showFPS:(BOOL)fp16;
- (id)initWithTestName:(id)fp8;

@end

