/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "QLContentView-Protocol.h"
#import "UIToolbarDelegate-Protocol.h"

@class QLDocumentInfoView, QuickLookBannerView;

@interface QLContentViewIPhone : _AITFireProbe <QLContentView, UIToolbarDelegate>
{
    QLDocumentInfoView *_documentInfoView;
    QuickLookBannerView *_bannerView;
}

- (int)positionForBar:(id)fp8;
- (void)updateWithQuickLookDocument:(id)fp8;
- (void)showBanner;
- (void)hideBanner;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 quickLookBannerViewDelegate:(id)fp24;

@end

