/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIView<QLContentView>;

@interface QuickLookDocumentView : _AITFireProbe
{
    UIView<QLContentView> *_contentView;
}

- (void)dealloc;
- (void)updateWithQuickLookDocument:(id)fp8;
- (void)showBanner;
- (void)hideBanner;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8 quickLookBannerViewDelegate:(id)fp24;

@end

