/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class LSDocumentProxy, NSString;

@interface QuickLookDocument : _AITFireProbe
{
    LSDocumentProxy *_documentProxy;
    BOOL _needsQuickLookDocumentView;
    NSString *_savedPath;
    NSString *_savedPathWithProperExtension;
    BOOL _shouldDeleteSavedPath;
    BOOL _shouldDeleteSavedPathWithProperExtension;
    NSString *_fileName;
    NSString *_mimeType;
    NSString *_uti;
}

- (void)setUti:(id)fp8;
- (id)uti;
- (void)setMimeType:(id)fp8;
- (id)mimeType;
- (void)setFileName:(id)fp8;
- (id)fileName;
- (void)setSavedPathWithProperExtension:(id)fp8;
- (void)setSavedPath:(id)fp8;
- (id)savedPath;
- (BOOL)needsQuickLookDocumentView;
- (void)setDocumentProxy:(id)fp8;
- (void)addQuickLookPrintSettingsToPrintInfo:(id)fp8;
- (void)setSavedPathWithProperExtension:(id)fp8 shouldDelete:(BOOL)fp12;
- (void)setSavedPath:(id)fp8 shouldDelete:(BOOL)fp12;
- (id)savedPathWithProperExtension;
- (id)documentProxy;
- (void)_deleteSavedPathWithProperExtensionIfNecessary;
- (void)_deleteSavedPathIfNecessary;
- (void)dealloc;
- (id)initWithFileName:(id)fp8 mimeType:(id)fp12 uti:(id)fp16 needsQuickLookDocumentView:(BOOL)fp20;

@end

