/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "QuickLookBannerViewDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegatePrivate-Protocol.h"

@class QuickLookDocumentView, TabDocument, UIDocumentInteractionController;

@interface QuickLookDocumentController : _AITFireProbe <QuickLookBannerViewDelegate, UIDocumentInteractionControllerDelegate, UIDocumentInteractionControllerDelegatePrivate>
{
    QuickLookDocumentView *_documentView;
    TabDocument *_tabDocument;
    UIDocumentInteractionController *_documentInteractionController;
    BOOL _isShowingQuickLookOpenInMenu;
}

- (void)setDocumentView:(id)fp8;
- (id)documentView;
- (void)setDocumentInteractionController:(id)fp8;
- (id)documentInteractionController;
- (id)documentProxyForPreview:(id)fp8 name:(id)fp12 UTI:(id)fp16;
- (void)documentInteractionController:(id)fp8 willBeginSendingToApplication:(id)fp12;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)fp8;
- (void)documentInteractionControllerWillPresentOpenInMenu:(id)fp8;
- (void)openInOtherApplications:(id)fp8;
- (void)openInApplication:(id)fp8;
- (id)_urlForQuickLookDocument;
- (void)dealloc;
- (id)initWithTabDocument:(id)fp8;

@end

