/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class OpenInApplicationBarButtonItem, UIBarButtonItem, UILabel;

@interface QuickLookBannerView : _AITFireProbe
{
    UILabel *_filenameLabel;
    UIBarButtonItem *_flexibleSpaceItem;
    OpenInApplicationBarButtonItem *_openInApplicationItem;
    UIBarButtonItem *_openInOtherApplicationsItem;
}

+ (float)defaultHeight;
- (void)animateOut;
- (void)animateIn;
- (void)_animateTo:(float)fp8;
- (BOOL)updateWithQuickLookDocument:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)_layoutFilenameLabel;
- (void)dealloc;
- (id)quickLookDelegate;
- (void)setQuickLookDelegate:(id)fp8;
- (id)initWithQuickLookBannerViewDelegate:(id)fp8;

@end

