/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "QuickLookBannerViewDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegatePrivate-Protocol.h"
#import "UIToolbarDelegate-Protocol.h"

@class QuickLookBannerView, TabDocument, UIDocumentInteractionController;

@interface QuickLookBannerController : _AITFireProbe <UIToolbarDelegate, QuickLookBannerViewDelegate, UIDocumentInteractionControllerDelegate, UIDocumentInteractionControllerDelegatePrivate>
{
    QuickLookBannerView *_quickLookBannerView;
    UIDocumentInteractionController *_documentInteractionController;
    TabDocument *_tabDocument;
    BOOL _isShowingQuickLookOpenInMenu;
}

- (void)setDocumentInteractionController:(id)fp8;
- (id)documentInteractionController;
- (id)bannerView;
- (id)documentProxyForPreview:(id)fp8 name:(id)fp12 UTI:(id)fp16;
- (id)documentInteractionControllerURLOfDirectoryForUnzippedDocument:(id)fp8;
- (void)documentInteractionController:(id)fp8 willBeginSendingToApplication:(id)fp12;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)fp8;
- (void)documentInteractionControllerWillPresentOpenInMenu:(id)fp8;
- (int)positionForBar:(id)fp8;
- (void)openInOtherApplications:(id)fp8;
- (void)openInApplication:(id)fp8;
- (id)_urlForQuickLookDocument;
- (void)_savePDFDocumentToFileIfNeeded;
- (void)showBannerView;
- (void)hideBannerView;
- (void)_removeBannerViewTimer;
- (void)_addOrRestartBannerViewTimer;
- (void)dealloc;
- (id)initWithTabDocument:(id)fp8;

@end

