/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSString, UILabel;

@interface ReadingListTableViewCell : _AITFireProbe
{
    BOOL _hasImage;
    unsigned int _bookmarkID;
    NSString *_siteName;
    NSString *_previewText;
    UILabel *_siteNameTextLabel;
    NSString *_fetchingStatusText;
}

- (void)setFetchingStatusText:(id)fp8;
- (id)fetchingStatusText;
- (BOOL)hasImage;
- (void)setSiteNameTextLabel:(id)fp8;
- (id)siteNameTextLabel;
- (void)setPreviewText:(id)fp8;
- (id)previewText;
- (void)setSiteName:(id)fp8;
- (id)siteName;
- (unsigned int)bookmarkID;
- (void)_setFetchingStatusTextForBookmark:(id)fp8;
- (void)setBookmark:(id)fp8 isArchiving:(BOOL)fp12;
- (void)setBookmark:(id)fp8;
- (void)dealloc;

@end

