/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class WebBookmark;

@interface ReadingListCompletionItem : _AITFireProbe
{
    WebBookmark *_bookmark;
}

- (void)auditAcceptedCompletionWithRank:(unsigned int)fp8;
- (id)completionTableViewCell;
- (id)completionTableViewCellReuseIdentifier;
- (void)acceptCompletionWithSearchAction:(id)fp(null) goToURLAction:(void)fp8 findOnPageAction:(id)fp(null);
- (void)configureCompletionTableViewCell:(id)fp8;
- (void)dealloc;
- (id)initWithReadingListBookmark:(id)fp8;

@end

