/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImageView;

@interface ReadingListProgressView : _AITFireProbe
{
    double _progress;
    BOOL _usesSmallVersion;
    UIImageView *_glasses;
    UIImageView *_track;
    UIImageView *_fill;
}

- (BOOL)usesSmallVersion;
- (double)progress;
- (struct CGPoint)pressFeedbackPosition;
- (void)setProgress:(double)fp8;
- (void)setUsesSmallVersion:(BOOL)fp8;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)dealloc;
- (void)setToolbarTintColor:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 usesSmallVersion:(BOOL)fp24;

@end

