/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSCache;

@interface ReadingListTableViewCellLayoutManager : _AITFireProbe
{
    NSCache *_textLabelSizeCache;
    NSCache *_detailLabelSizeCache;
    NSCache *_siteNameLabelSizeCache;
}

+ (id)sharedManager;
- (void)layoutSubviewsOfCell:(id)fp8;
- (struct CGSize)_sizeForLabel:(id)fp8 maxSize:(struct CGSize)fp12 usingCache:(id)fp20;
- (void)_getTitleLabelOffsetY:(float *)fp8 domainLabelOffsetY:(float *)fp12 detailLabelOffsetY:(float *)fp16;
- (id)_labelForLayoutMetricsWithFont:(id)fp8 numberOfLines:(int)fp12;
- (struct CGRect)textRectForCell:(id)fp8;
- (id)textLabelForCell:(id)fp8;
- (id)detailTextLabelForCell:(id)fp8;
- (id)_siteNameFont;
- (id)_detailLabelFont;
- (id)_titleLabelFont;
- (id)init;

@end

