/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "BookmarksPanelStateRestoring-Protocol.h"
#import "BookmarksToolbarItemProvider-Protocol.h"
#import "CatalogCategoryViewController-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WebBookmarksClientDelegateProtocol-Protocol.h"

@class NSString, NSTimer, SafariFetcherServerProxy, UIBarButtonItem, UITableView, WebBookmarkCollection, WebBookmarkList, _UIContentUnavailableView;

@interface ReadingListViewController : _AITFireProbe <BookmarksPanelStateRestoring, BookmarksToolbarItemProvider, CatalogCategoryViewController, UITableViewDelegate, UITableViewDataSource, WebBookmarksClientDelegateProtocol>
{
    UITableView *_tableView;
    UIBarButtonItem *_unreadFilterButton;
    WebBookmarkCollection *_collection;
    BOOL _networkIsReachable;
    WebBookmarkList *_readingList;
    SafariFetcherServerProxy *_safariFetcherServerProxy;
    NSString *_archivingBookmarkUUID;
    _UIContentUnavailableView *_explanationView;
    NSTimer *_deletionNotificationTimer;
    BOOL _showingAllBookmarks;
    id <ReadingListViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)showingAllBookmarks;
- (id)safari_tableViewScrollPositionSaveIdentifier;
- (id)safari_tableViewForScrollPositionSaving;
- (void)bookmarksServerProxy:(id)fp8 didStopFetchingReadingListItem:(id)fp12;
- (void)bookmarksServerProxy:(id)fp8 didStartFetchingReadingListItem:(id)fp12;
- (void)bookmarksServerProxyConnectionInvalidated:(id)fp8;
- (void)bookmarksServerProxyDidFinishFetching:(id)fp8;
- (id)collectionType;
- (void)restoreScrollPosition:(float)fp8;
- (float)currentScrollPosition;
- (BOOL)restoreStateWithDictionary:(id)fp8;
- (id)currentStateDictionary;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)_disconnectSafariFetcherServerProxy;
- (void)_connectSafariFetcherServerProxy;
- (void)_postChangeNotification;
- (void)_scheduleDelayedChangeNotification;
- (struct CGSize)preferredContentSize;
- (void)_updatePopoverSize;
- (void)didMarkBookmarkUnreadAtIndex:(unsigned int)fp8;
- (void)didAddNewReadingListBookmark;
- (void)_addReadingListItem;
- (id)bookmarksRightBarButtonItem;
- (id)_unreadFilterButtonTitle;
- (void)_didChangeUnreadFilter;
- (void)_reloadReadingListAndTable;
- (void)_reloadReadingList;
- (void)_networkReachabilityChanged:(id)fp8;
- (id)_bookmarkAtIndexPath:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)_clearExplanationView;
- (void)_showExplanationView;
- (id)bookmarksNavigationController;
- (void)dealloc;
- (id)init;

@end

