/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionProvider.h"

@class NSString;

@interface ReadingListCompletionProvider : CompletionProvider
{
    unsigned int _maxResults;
    NSString *_stringToComplete;
    BOOL _onlyIncludeAvailableOffline;
}

- (BOOL)onlyIncludeAvailableOffline;
- (unsigned int)maximumCachedCompletionCount;
- (void)setStringToComplete:(id)fp8;
- (void)dealloc;
- (id)initWithMaximumNumberOfCompletions:(unsigned int)fp8 onlyIncludeAvailableOffline:(BOOL)fp12;

@end

