/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSMutableArray;

@interface RecentlyClosedTabViewController : _AITFireProbe
{
    NSMutableArray *_recentlyClosedTabs;
    id <RecentlyClosedTabViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (struct CGSize)preferredContentSize;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)removeAllRecentlyClosedTabDocuments;
- (void)removeRecentlyClosedTabDocument:(id)fp8;
- (void)addRecentlyClosedTabDocument:(id)fp8;
- (void)dealloc;
- (id)initWithStyle:(int)fp8;

@end

