/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PurplePageLoadTestRunner.h"

@interface ReplayPagesTestRunner : PurplePageLoadTestRunner
{
    struct __sFILE *_suiteFile;
    unsigned int _attemptCount;
    unsigned int _successCount;
    BOOL _eternal;
}

- (void)setEternal:(BOOL)fp8;
- (BOOL)eternal;
- (void)startNextPage;
- (void)finishedTestPage:(id)fp8;
- (_Bool)loadTestSuiteFile:(id)fp8;
- (void)dealloc;

@end

