/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionProvider.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class NSMutableData, NSObject<OS_dispatch_queue>, NSString;

@interface SearchSuggestionProvider : CompletionProvider <NSURLConnectionDelegate>
{
    struct _CFURLConnection *_suggestionConnection;
    NSMutableData *_suggestionData;
    NSString *_currentSearchString;
    NSString *_userAgentString;
    NSObject<OS_dispatch_queue> *_connectionQueue;
}

- (unsigned int)maximumCachedCompletionCount;
- (id)suggestionStrings;
- (id)suggestionQueryStringForSearchString:(id)fp8;
- (void)dealloc;
- (void)stop;
- (void)setStringToComplete:(id)fp8;
- (void)_cancelAndReleaseConnectionAndData;
- (id)init;

@end

