/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSString, SearchEngineInfo;

@interface SearchQueryBuilder : _AITFireProbe
{
    NSString *queryString;
    SearchEngineInfo *engineInfo;
}

+ (id)searchQueryBuilderWithXWebSearchURL:(id)fp8;
+ (id)searchQueryBuilderWithQuery:(id)fp8;
- (id)searchEngineInfo;
- (BOOL)searchEngineIsDefault;
- (id)queryString;
- (id)searchURL;
- (id)initWithXWebSearchURL:(id)fp8;
- (void)dealloc;
- (id)initWithQueryString:(id)fp8;
- (id)initWithSearchEngineInfo:(id)fp8 queryString:(id)fp12;

@end

