/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "NSURLConnectionDelegate-Protocol.h"
#import "NSURLDownloadDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface SearchEngineController : _AITFireProbe <NSURLConnectionDelegate, NSURLDownloadDelegate>
{
    NSMutableArray *searchEngines;
    unsigned int defaultSearchEngineIndex;
    NSString *_countryCode;
    NSString *_languageCode;
    NSString *_carrierCountryCode;
    NSString *_carrierName;
    NSString *_carrierNetworkCode;
}

+ (id)sharedInstanceIfAvailable;
+ (id)sharedInstance;
+ (void)_initializeSharedInstance;
- (void)setCarrierNetworkCode:(id)fp8;
- (id)carrierNetworkCode;
- (void)setCarrierName:(id)fp8;
- (id)carrierName;
- (void)setCarrierCountryCode:(id)fp8;
- (id)carrierCountryCode;
- (void)setLanguageCode:(id)fp8;
- (id)languageCode;
- (void)setCountryCode:(id)fp8;
- (id)countryCode;
- (id)safeSearchRequestForSearchRequest:(id)fp8;
- (BOOL)isSearchProviderDomainURL:(id)fp8;
- (void)loadSystemProperties;
- (void)setSearchEngineInfoAsDefault:(id)fp8;
- (void)loadFallbackSearchEngines;
- (void)addSpecialSearchEngines;
- (id)engineInfoForScriptName:(id)fp8;
- (id)engineInfoFor:(id)fp8;
- (id)existingEngineInfoFor:(id)fp8;
- (id)defaultSearchEngine;
- (void)setDefaultSearchEngine:(id)fp8;
- (void)readDefaultSearchEngine;
- (id)description;
- (void)parseConfigData:(id)fp8;
- (BOOL)loadLocalConfigPlist:(id)fp8;
- (void)downloadRemoteConfigPlist;
- (void)downloadDidFail:(id)fp8;
- (void)downloadDidFinish:(id)fp8;
- (BOOL)shouldLoadRemoteConfigPlist;
- (void)loadConfigPlist;
- (void)dealloc;
- (void)reloadSearchEngines;
- (void)populateSearchEngines;
- (id)init;

@end

