/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "CompletionItem-Protocol.h"

@class NSString;

@interface SearchSuggestion : _AITFireProbe <CompletionItem>
{
    BOOL _recentSearch;
    BOOL _searchEngineSuggestion;
    BOOL _goesToURL;
    NSString *_string;
}

- (BOOL)goesToURL;
- (id)string;
- (void)auditAcceptedCompletionWithRank:(unsigned int)fp8;
- (id)completionTableViewCell;
- (id)completionTableViewCellReuseIdentifier;
- (void)acceptCompletionWithSearchAction:(id)fp(null) goToURLAction:(void)fp8 findOnPageAction:(id)fp(null);
- (void)configureCompletionTableViewCell:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithSearchEngineSuggestion:(id)fp8;
- (id)initWithRecentSearchString:(id)fp8;
- (id)initWithUserTypedString:(id)fp8;

@end

