/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSURL;

@interface SecurityInfo : _AITFireProbe
{
    NSURL *url;
    int urlSecurityAssessment;
    int urlSecurityProvider;
    BOOL hasWarnedUser;
}

- (void)setURLSecurityProvider:(int)fp8;
- (int)urlSecurityProvider;
- (void)setHasWarnedUser:(BOOL)fp8;
- (BOOL)hasWarnedUser;
- (BOOL)isKnownToBeUnsafe;
- (void)setURLSecurityAssessment:(int)fp8;
- (int)urlSecurityAssessment;
- (void)setAssessedURL:(id)fp8;
- (id)assessedURL;
- (id)description;
- (void)dealloc;

@end

