/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class WebScriptObject;

@interface SetSearchEngineScriptObject : _AITFireProbe
{
    WebScriptObject *_windowObject;
}

- (id)invokeDefaultMethodWithArguments:(id)fp8;
- (void)dealloc;
- (id)initWithWindowObject:(id)fp8;

@end

