/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface SharedDataMigration : _AITFireProbe
{
}

+ (BOOL)migrateThumbnails;
+ (BOOL)migrateRecentSearches;
+ (void)migratePersistentStorageDefaults;
+ (BOOL)_migrateCacheFileFromSubpath:(id)fp8 toSubpath:(id)fp12 ensureIsDirectory:(BOOL)fp16;
+ (id)_userCachesDirectoryPath;

@end

