/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SiteIconDownloadRequestDelegate <NSObject>
- (void)siteIconDownloadRequest:(id)fp8 didComputeIconKeyColor:(id)fp12;
- (void)siteIconDownloadRequest:(id)fp8 didLoadIconData:(id)fp12;
- (void)siteIconDownloadRequestDidFail:(id)fp8;
@end

