/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface SiteIconKeyColorExtractor : _AITFireProbe
{
}

+ (char *)_createRGBAPixelBufferFromImage:(id)fp8;
+ (id)keyColorForIcon:(id)fp8;

@end

