/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface SiteIcon : _AITFireProbe
{
}

+ (id)precompositedDefaultIcon;
+ (id)defaultGlyph;
+ (id)defaultIconKeyColor;
+ (struct CGSize)defaultSize;
+ (id)defaultBackgroundColor;

@end

