/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "SiteIconDownloadRequestDelegate-Protocol.h"

@class NSMutableArray, NSMutableIndexSet, NSMutableSet;

@interface SiteIconDownloader : _AITFireProbe <SiteIconDownloadRequestDelegate>
{
    NSMutableIndexSet *_activeAndPendingBookmarkIdentifiers;
    NSMutableArray *_pendingDownloadRequests;
    NSMutableSet *_activeDownloadRequests;
}

+ (id)sharedSiteIconDownloader;
- (void)siteIconDownloadRequestDidFail:(id)fp8;
- (void)siteIconDownloadRequest:(id)fp8 didComputeIconKeyColor:(id)fp12;
- (void)siteIconDownloadRequest:(id)fp8 didLoadIconData:(id)fp12;
- (void)_updateBookmarkForIconDownloadRequest:(id)fp8 withIconKeyColor:(id)fp12 iconData:(id)fp16;
- (void)_siteIconDownloadRequestDidFinish:(id)fp8;
- (void)cancelAllDownloads;
- (unsigned int)_maximumSimultaneousDownloads;
- (void)_startDownloadRequestIfPossible;
- (void)downloadIconsForBookmark:(id)fp8 withBrowserView:(id)fp12;
- (void)downloadIconsForBookmark:(id)fp8;
- (BOOL)_downloadIsActiveOrPendingForBookmark:(id)fp8;
- (void)dealloc;
- (id)init;

@end

