/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImageView, WebBookmark;

@interface SiteIconView : _AITFireProbe
{
    UIImageView *_glyphView;
    WebBookmark *_bookmark;
}

- (id)bookmark;
- (id)_tintedFolderImage;
- (void)_setGlyph:(id)fp8 withBackgroundColor:(id)fp12;
- (void)_clearGlyph;
- (void)updateBookmarkData;
- (void)_updateBookmarkDataWithIcon:(id)fp8;
- (void)setBookmark:(id)fp8 icon:(id)fp12;
- (void)setBookmark:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;

@end

