/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UIWebViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableData, NSString, NSURL, NSURLConnection, UIWebView;

@interface SiteIconDownloadRequest : _AITFireProbe <UIWebViewDelegate>
{
    NSURL *_mainResourceURL;
    UIWebView *_webView;
    NSString *_userAgentString;
    BOOL _fetchForFavoritesIcon;
    BOOL _paused;
    NSMutableArray *_iconURLs;
    NSURLConnection *_URLConnection;
    NSMutableData *_iconData;
    unsigned int _bookmarkID;
    NSString *_bookmarkAddress;
    id <SiteIconDownloadRequestDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)bookmarkAddress;
- (unsigned int)bookmarkID;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didReceiveAuthenticationChallenge:(id)fp12;
- (void)_processIconDataAndNotifyDelegate;
- (id)_bestImageWithData:(id)fp8 forWidth:(float)fp12;
- (void)_cancelConnectionAndFetchNextIcon;
- (void)_fetchNextIcon;
- (void)setBookmarkFetchedIconData;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (id)uiWebView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;
- (id)uiWebView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (void)_buildIconURLListWithBrowserView:(id)fp8;
- (void)_appendFallbackIconAtPath:(id)fp8;
- (void)_fetchMainResource;
- (void)start;
- (void)cancel;
- (void)dealloc;
- (void)_clearWebView;
- (id)initWithBookmark:(id)fp8 singleResourceURL:(id)fp12;
- (id)initWithBookmark:(id)fp8 browserView:(id)fp12;
- (id)initWithBookmark:(id)fp8;

@end

