/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImage, UIImageView, WBSAutomaticReadingListItem;

@interface SocialLinksTableViewCell : _AITFireProbe
{
    UIImage *_posterImage;
    UIImageView *_serviceImageView;
    WBSAutomaticReadingListItem *_item;
}

+ (float)heightForItem:(id)fp8 inTableView:(id)fp12;
- (id)item;
- (void)setItem:(id)fp8;
- (id)_serviceImage;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setPosterImage:(id)fp8;
- (void)layoutSubviews;
- (struct CGRect)_serviceImageFrame;
- (void)dealloc;

@end

