/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface StoreBannerTracker : _AITFireProbe
{
    NSMutableDictionary *_blockedProducts;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedTracker;
- (void)blockProductBanner:(id)fp8;
- (void)isProductBannerBlocked:(id)fp8 completion:(id)fp(null);
- (void)clear;
- (void)save;
- (void)load;
- (id)filePath;
- (void)dealloc;
- (id)init;

@end

