/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol TabBarDelegate
- (void)tabBar:(id)fp8 closeItem:(id)fp12;
- (void)tabBar:(id)fp8 activateItem:(id)fp12;
- (void)tabBar:(id)fp8 moveItem:(id)fp12 overItem:(id)fp16;
- (void)tabBarAddTab:(id)fp8;
- (void)tabBarShowMoreTabs:(id)fp8;
- (BOOL)tabBar:(id)fp8 canCloseItem:(id)fp12;
- (BOOL)tabBar:(id)fp8 canMoveItem:(id)fp12;
@end

