/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, TabBarItem, UIPanGestureRecognizer;

@interface TabBar : _AITFireProbe <UIGestureRecognizerDelegate>
{
    UIPanGestureRecognizer *_reorderRecognizer;
    struct CGPoint _reorderOrigin;
    struct CGPoint _reorderEffectiveTouchLocation;
    TabBarItem *_floatingItem;
    TabBarItem *_sinkingItem;
    BOOL _shouldShowMoreTabsButton;
    BOOL _showsProgressOnTop;
    BOOL _hidesTitles;
    id <TabBarDelegate> _delegate;
    NSArray *_items;
    unsigned int _barStyle;
}

+ (float)defaultHeight;
- (void)setHidesTitles:(BOOL)fp8;
- (BOOL)hidesTitles;
- (BOOL)showsProgressOnTop;
- (unsigned int)barStyle;
- (BOOL)shouldShowMoreTabsButton;
- (id)items;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (void)setShowsProgressOnTop:(BOOL)fp8;
- (void)_item:(id)fp8 didUpdateFromTitle:(id)fp12 toTitle:(id)fp16;
- (unsigned int)_maximumTruncationIndexForTitle:(id)fp8;
- (struct CGRect)moreTabsPopoverPresentationRect;
- (void)reorder:(id)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)_finishReorderingAnimated:(BOOL)fp8;
- (void)_beginReorderingItem:(id)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (id)_itemForTouch:(id)fp8;
- (id)_itemAtLocation:(struct CGPoint)fp8;
- (void)setItems:(id)fp8 animated:(BOOL)fp12;
- (void)setItems:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)setItems:(id)fp8;
- (void)setShouldShowMoreTabsButton:(BOOL)fp8;
- (void)setBarStyle:(unsigned int)fp8;
- (void)layoutSubviews;
- (void)_layoutIndexes:(id)fp8 ofItems:(id)fp12;
- (unsigned int)_effectiveIndexForIndex:(unsigned int)fp8 ofItems:(id)fp12;
- (struct CGRect)_frameForItemAtIndex:(unsigned int)fp8;
- (unsigned int)itemCountThatFits;
- (void)_layoutItem:(id)fp8 inRect:(struct CGRect)fp12 itemCount:(unsigned int)fp28 seenActiveItemYet:(BOOL)fp32;
- (void)_itemDidPressMoreTabsButton:(id)fp8;
- (void)_itemDidPressCloseButton:(id)fp8;
- (void)_tabButtonPressed;
- (id)initWithFrame:(struct CGRect)fp8;

@end

