/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class FluidProgressView, NSString, TabBar, TabBarItemView;

@interface TabBarItem : _AITFireProbe
{
    TabBarItemView *_view;
    TabBar *_tabBar;
    BOOL _active;
    NSString *_title;
    FluidProgressView *_progressView;
}

- (id)progressView;
- (BOOL)isActive;
- (id)title;
- (void)clearView;
- (void)setProgressView:(id)fp8;
- (void)setActive:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (void)setTabBar:(id)fp8;
- (void)moreTabsButtonPressed;
- (void)closeButtonPressed;
- (BOOL)hasView;
- (id)view;
- (void)dealloc;

@end

