/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface TabDocumentWebBrowserView : _AITFireProbe
{
}

- (struct CGSize)contentSizeForScrollView:(id)fp8;
- (float)heightToKeepVisible;
- (float)minimumVerticalContentOffset;

@end

