/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TiltedTabSnapshotCacheDelegate <NSObject>
- (void)tiltedTabSnapshotCacheDidFinishUpdating:(id)fp8;
- (void)tiltedTabSnapshotCache:(id)fp8 requestSnapshotWithIdentifier:(id)fp12 completion:(id)fp(null);
- (void)tiltedTabSnapshotCache:(id)fp8 didCacheSnapshotWithIdentifier:(id)fp12;
@end

