/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class DimmingButton, GradientView, NSObject<OS_dispatch_queue>, NSString, TiltedTabView, UIImage, UIImageView, UILabel, UIView;

@interface TiltedTabItem : _AITFireProbe
{
    UILabel *_titleLabel;
    BOOL _titleTextNeedsUpdate;
    struct CGSize _titleSize;
    NSObject<OS_dispatch_queue> *_titleMeasurementQueue;
    UIImage *_snapshot;
    UIImageView *_snapshotView;
    BOOL _topBackdropScaled;
    BOOL _contentViewNeedsRemoval;
    BOOL _editing;
    BOOL _reordering;
    BOOL _closing;
    BOOL _finishedClosing;
    NSString *_title;
    NSString *_snapshotIdentifier;
    TiltedTabView *_tiltedTabView;
    UIView *_headerView;
    UIView *_contentView;
    float _topBackdropHeight;
    GradientView *_contentShadowView;
    UIView *_contentClipperView;
    DimmingButton *_closeButton;
    UIView *_borrowedContentView;
    float _borrowedContentScale;
    UIImage *_blankSnapshot;
    UIImage *_snapshotWithInvalidBackdrop;
    unsigned int _indexForLayout;
    unsigned int _countForLayout;
    float _verticalScrollAdjustment;
    struct CGRect _closeButtonHitRect;
}

+ (id)_newContentShadowView;
+ (id)titleFont;
- (void)setVerticalScrollAdjustment:(float)fp8;
- (float)verticalScrollAdjustment;
- (void)setCountForLayout:(unsigned int)fp8;
- (unsigned int)countForLayout;
- (void)setIndexForLayout:(unsigned int)fp8;
- (unsigned int)indexForLayout;
- (void)setFinishedClosing:(BOOL)fp8;
- (BOOL)isFinishedClosing;
- (void)setClosing:(BOOL)fp8;
- (BOOL)isClosing;
- (void)setReordering:(BOOL)fp8;
- (BOOL)isReordering;
- (void)setEditing:(BOOL)fp8;
- (BOOL)isEditing;
- (void)setContentViewNeedsRemoval:(BOOL)fp8;
- (BOOL)contentViewNeedsRemoval;
- (void)setSnapshotWithInvalidBackdrop:(id)fp8;
- (id)snapshotWithInvalidBackdrop;
- (id)blankSnapshot;
- (id)snapshot;
- (float)borrowedContentScale;
- (id)borrowedContentView;
- (void)setCloseButtonHitRect:(struct CGRect)fp8;
- (struct CGRect)closeButtonHitRect;
- (id)closeButton;
- (id)contentClipperView;
- (id)contentShadowView;
- (void)setTopBackdropScaled:(BOOL)fp8;
- (BOOL)topBackdropScaled;
- (void)setTopBackdropHeight:(float)fp8;
- (float)topBackdropHeight;
- (id)contentView;
- (id)headerView;
- (void)setTiltedTabView:(id)fp8;
- (id)tiltedTabView;
- (id)snapshotIdentifier;
- (id)title;
- (void)dealloc;
- (id)titleColor;
- (void)setTitleColor:(id)fp8;
- (void)setTitle:(id)fp8;
- (BOOL)hidesTitle;
- (void)setHidesTitle:(BOOL)fp8;
- (void)setBorrowedContentView:(id)fp8;
- (void)setBorrowedContentScale:(float)fp8;
- (void)_updateBorrowedContentFrame;
- (struct CGRect)contentShadowFrame;
- (void)setBlankSnapshot:(id)fp8;
- (void)setSnapshot:(id)fp8 animated:(BOOL)fp12;
- (void)setSnapshot:(id)fp8;
- (id)cachedContentImage;
- (void)updateClipperView;
- (struct CGRect)contentClipperBounds;
- (struct CGRect)clippedContentFrame;
- (void)updateSnapshotViewAnimated:(BOOL)fp8;
- (id)_snapshotToShow;
- (void)layoutHeaderViewAnimated:(BOOL)fp8 showingTitle:(BOOL)fp12 extraTitleScale:(float)fp16 closeButton:(BOOL)fp20;
- (void)_updateTitleLayout;
- (void)invalidateSnapshot;
- (void)setSnapshotIdentifier:(id)fp8;
- (id)init;

@end

