/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class UIImage;

@interface TiltedTabSnapshotCacheEntry : _AITFireProbe
{
    UIImage *_snapshot;
    int _state;
}

- (void)setState:(int)fp8;
- (int)state;
- (void)setSnapshot:(id)fp8;
- (id)snapshot;
- (void)dealloc;
- (id)init;

@end

