/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

#import "TiltedTabSnapshotCacheDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "ViewReuseManagerDelegate-Protocol.h"
#import "_UIBasicAnimationFactory-Protocol.h"

@class CADisplayLink, CloudTabItemView, GradientView, HighlightRecognizer, NSArray, NSMutableSet, NSTimer, TiltedTabItem, TiltedTabSnapshotCache, UIColor, UIImage, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIScrollView, UITapGestureRecognizer, UIView, ViewReuseManager;

@interface TiltedTabView : _AITFireProbe <UIGestureRecognizerDelegate, UIScrollViewDelegate, TiltedTabSnapshotCacheDelegate, _UIBasicAnimationFactory, ViewReuseManagerDelegate>
{
    BOOL _presented;
    BOOL _sentDidDismissToDelegate;
    BOOL _sentDidPresentToDelegate;
    UIPanGestureRecognizer *_tabCloseRecognizer;
    UILongPressGestureRecognizer *_tabReorderRecognizer;
    UITapGestureRecognizer *_tabSelectionRecognizer;
    UIScrollView *_scrollView;
    BOOL _suppressingScrollViewDidScroll;
    GradientView *_statusBarGradient;
    unsigned int _activeAnimationCount;
    TiltedTabItem *_animatingItem;
    BOOL _startedAnimatingItem;
    UIView *_animatingTopBackdropView;
    TiltedTabItem *_itemToScrollIntoView;
    BOOL _topBackdropViewHidden;
    TiltedTabItem *_interactivelyClosingItem;
    float _interactiveCloseProgress;
    float _interactiveCloseVelocity;
    TiltedTabItem *_onlyHorizontalVelocityItem;
    BOOL _applyVelocityOnlyToHorizontalPosition;
    TiltedTabItem *_pressedItem;
    HighlightRecognizer *_pressRecognizer;
    TiltedTabItem *_interactivelyReorderingItem;
    float _interactiveReorderOffsetDistanceFromTouch;
    float _interactiveReorderOffset;
    BOOL _reorderOffsetNeedsReset;
    CADisplayLink *_reorderScrollDisplayLink;
    float _reorderScrollVelocity;
    float _reorderScrollOffsetError;
    NSArray *_itemsInvolvedInAnimation;
    NSMutableSet *_itemsCurrentlyClosing;
    UIView *_cloudTabContainer;
    NSArray *_cloudTabDevices;
    ViewReuseManager *_cloudTabViewReuseManager;
    struct _NSRange _trackedCloudTabViewRange;
    NSArray *_cloudTabHeaderViews;
    CloudTabItemView *_selectedCloudTabView;
    BOOL _cloudTabsNeedLayout;
    NSTimer *_itemActivationTimer;
    TiltedTabSnapshotCache *_snapshotCache;
    BOOL _flushPendingSnapshots;
    id _flushPendingSnapshotsCompletion;
    BOOL _updatingSnapshotBackdrops;
    UIImage *_snapshotBackdropSource;
    UIImage *_closeButtonImage;
    UIImage *_blankSnapshot;
    UIView *_bottomMaskView;
    id <TiltedTabViewDelegate> _delegate;
    NSArray *_items;
    TiltedTabItem *_itemToActivate;
    UIColor *_titleColor;
}

+ (float)snapshotTopBackdropHeight;
- (id)titleColor;
- (id)itemToActivate;
- (BOOL)isPresented;
- (id)items;
- (id)delegate;
- (void)viewReuseManager:(id)fp8 prepareView:(id)fp12 toRepresentObjectAtIndex:(unsigned int)fp16;
- (void)viewReuseManager:(id)fp8 willRecycleView:(id)fp12;
- (void)_layoutCloudTabViews:(id)fp8 representingItemsInRange:(struct _NSRange)fp12 includingHeaders:(BOOL)fp20 animated:(BOOL)fp24;
- (void)_enumerateCloudTabViews:(id)fp8 representingItemsInRange:(struct _NSRange)fp12 headerLayoutHandler:(id)fp(null) itemLayoutHandler:(void)fp20;
- (struct _NSRange)_visibleCloudTabViewRange;
- (void)_didSelectCloudTabItemView:(id)fp8;
- (void)setCloudTabDevices:(id)fp8;
- (void)tiltedTabSnapshotCacheDidFinishUpdating:(id)fp8;
- (void)tiltedTabSnapshotCache:(id)fp8 didCacheSnapshotWithIdentifier:(id)fp12;
- (void)tiltedTabSnapshotCache:(id)fp8 requestSnapshotWithIdentifier:(id)fp12 completion:(id)fp(null);
- (void)_updateSnapshotsAnimated:(BOOL)fp8;
- (void)_updateBlankSnapshot;
- (void)_postProcessSnapshot:(id)fp8 withCompletion:(id)fp(null);
- (struct CGSize)_requestedSnapshotSize;
- (void)_willSetSnapshotIdentifierForItem:(id)fp8;
- (void)_invalidateSnapshotForItem:(id)fp8;
- (void)finishUpdatingSnapshotBackdrops;
- (void)beginUpdatingSnapshotBackdrops;
- (void)precacheSavedSnapshots;
- (void)flushPendingSnapshotsWithCompletion:(id)fp(null);
- (void)layoutSubviews;
- (void)scrollViewDidScroll:(id)fp8;
- (void)_layoutItemsAnimated:(BOOL)fp8;
- (unsigned int)_selectedCloudTabIndex;
- (float)_baseOffsetForCloudTabViews;
- (float)_baseOffsetForItem:(id)fp8 index:(unsigned int *)fp12 count:(float *)fp16;
- (float)_baseOffsetForItemAtIndex:(unsigned int)fp8 withItemCountForLayout:(float)fp12;
- (float)_interactiveCloseProgressForLayout;
- (float)_cloudTabsContentHeightForItemCount:(float)fp8;
- (float)_cloudTabsTopPaddingForItemCount:(float)fp8;
- (struct CGSize)_contentSizeForItemCount:(float)fp8;
- (float)_spaceBetweenTabsWithCount:(float)fp8;
- (void)_updateReorderAnimationsForItem:(id)fp8 withTimeAdjustment:(double)fp12 tabCount:(float)fp20 createIfNecessary:(BOOL)fp24;
- (void)_updateReorderAnimationBeginTimeForLayer:(id)fp8 withTimeAdjustment:(double)fp12;
- (void)_stopReorderingItem:(id)fp8 withFinalTimeAdjustment:(double)fp12 tabCount:(float)fp20;
- (id)_makeReorderAnimationWithDirection:(int)fp8 springDuration:(float)fp12 tabCount:(float)fp16;
- (void)_updateSpringAnimationForView:(id)fp8 withBounds:(struct CGRect)fp12 animated:(BOOL)fp28;
- (void)_updateSpringAnimationForView:(id)fp8 withFrame:(struct CGRect)fp12 transform:(struct CATransform3D)fp28 zPosition:(float)fp92 opacity:(float)fp96 verticalScrollAdjustment:(float)fp100 animated:(BOOL)fp104;
- (void)_addSpringAnimationWithKeyPath:(id)fp8 toLayer:(id)fp12 fromValue:(id)fp16 toValue:(id)fp20;
- (id)_timingFunctionForAnimation;
- (id)_basicAnimationForView:(id)fp8 withKeyPath:(id)fp12;
- (void)_configureVelocityForSpringAnimation:(id)fp8 withKeyPath:(id)fp12;
- (void)_configureStaticPropertiesForSpringAnimation:(id)fp8;
- (double)_durationForSpringAnimations;
- (float)_velocityForSpringAnimations;
- (void)_updateSpringAnimationForView:(id)fp8 withFrame:(struct CGRect)fp12 verticalScrollAdjustment:(float)fp28 animated:(BOOL)fp32;
- (void)_closeButtonPressed:(id)fp8;
- (void)_updateCloseButtonImageForItem:(id)fp8;
- (void)setTitleColor:(id)fp8;
- (void)setItems:(id)fp8 animated:(BOOL)fp12;
- (void)_updateSnapshotCacheIdentifiers;
- (void)_updateItemsInvolvedInAnimation;
- (void)_resetItem:(id)fp8;
- (BOOL)_shouldContinueAnimatingItem:(id)fp8;
- (void)setItems:(id)fp8;
- (void)setPresented:(BOOL)fp8;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)setPresented:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_updateSnapshotCacheStateForPresented:(BOOL)fp8;
- (void)_finishAnimations;
- (void)_activateItemToActivate;
- (void)_setItemActivationTimer:(id)fp8;
- (void)_sendPresentedStateDidChangeToDelegateIfNeeded;
- (void)_setTopBackdropViewHidden:(BOOL)fp8;
- (void)_attemptToRelinquishBorrowedContentEarly;
- (void)_relinquishBorrowedContent;
- (void)setItemToActivate:(id)fp8;
- (void)_tabSelectionRecognized:(id)fp8;
- (void)_tabReorderRecognized:(id)fp8;
- (void)_resetInteractiveReorderOffsetAtLocation:(struct CGPoint)fp8;
- (void)_updateReorderGesture;
- (void)_reorderScroll:(id)fp8;
- (void)_setReorderScrollVelocity:(float)fp8;
- (void)_tabCloseRecognized:(id)fp8;
- (float)_tabCloseAnimationSlideDistance;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (BOOL)_gestureRecognizer:(id)fp8 shouldInteractWithItem:(id)fp12;
- (void)_tabPressUpdated:(id)fp8;
- (void)_setPressedItem:(id)fp8 animated:(BOOL)fp12;
- (id)_tiltedTabItemForLocation:(struct CGPoint)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct CGRect)_hitRectForItem:(id)fp8;
- (float)_topAreaHeightForTabsWithCount:(float)fp8;
- (float)_scrollingEffectFactorForTabsWithCount:(float)fp8;
- (struct CGRect)_tabLayoutBounds;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

