/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSAttributedString, UIColor;

@interface TopHitCompletionView : _AITFireProbe
{
    NSAttributedString *_attributedText;
    unsigned int _highlightStartIndex;
    UIColor *_highlightColor;
}

- (void)setHighlightColor:(id)fp8;
- (id)highlightColor;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)setAttributedText:(id)fp8 highlightStartIndex:(unsigned int)fp12;

@end

