/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITextFieldDelegate-Protocol.h"

@protocol UnifiedFieldDelegate <UITextFieldDelegate>
- (id)unifiedField:(id)fp8 topHitForText:(id)fp12;
- (BOOL)unifiedField:(id)fp8 shouldWaitForTopHitForText:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithSearch:(id)fp12;
- (void)unifiedField:(id)fp8 didEndEditingWithAddress:(id)fp12;
@end

