/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@interface UniqueAnimationKey : _AITFireProbe
{
    unsigned int _key;
}

- (BOOL)getBytes:(void *)fp8 maxLength:(unsigned int)fp12 usedLength:(unsigned int *)fp16 encoding:(unsigned int)fp20 options:(unsigned int)fp24 range:(struct _NSRange)fp28 remainingRange:(struct _NSRange *)fp36;
- (unsigned short)characterAtIndex:(unsigned int)fp8;
- (unsigned int)length;
- (id)initWithKey:(unsigned int)fp8;

@end

