/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AITFireProbe.h"

@class NSArray, NSCache, NSObject<OS_dispatch_queue>;

@interface URLCompletionDatabase : _AITFireProbe
{
    NSArray *_cloudDevices;
    NSObject<OS_dispatch_queue> *_cloudTabsAccessQueue;
    NSCache *_bookmarksCache;
    int _searchableCollectionsMask;
}

- (void)setSearchableCollectionsMask:(int)fp8;
- (int)searchableCollectionsMask;
- (id)fakeBookmarkMatchDataWithURLString:(id)fp8 title:(id)fp12;
- (void)enumerateMatchDataForTypedStringHint:(id)fp8 withBlock:(id)fp(null);
- (id)_bookmarkCollection;
- (void)_updateCloudDevices:(id)fp8;
- (void)clearBookmarksCache;
- (void)dealloc;
- (id)initWithSearchableCollectionsMask:(int)fp8;

@end

