/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionProvider.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, URLCompletionDatabase, WebBookmarkCollection;

@interface URLCompletionProvider : CompletionProvider
{
    WebBookmarkCollection *_collection;
    NSMutableArray *_completionList;
    unsigned int _maxResults;
    NSString *_currentPrefix;
    BOOL _historyWasModified;
    BOOL _bookmarksWereModified;
    struct _opaque_pthread_mutex_t _prefixMutex;
    unsigned int _urlCompletionBackgroundTaskIdentifier;
    URLCompletionDatabase *_completionDatabase;
    NSObject<OS_dispatch_queue> *_completionQueue;
    BOOL _needScheduleBackgroundTaskOnAppSuspend;
    BOOL _providesTopHits;
}

- (void)setProvidesTopHits:(BOOL)fp8;
- (BOOL)providesTopHits;
- (void)_endURLCompletionBackgroundTask;
- (void)_applicationDidEnterBackground:(id)fp8;
- (void)setStringToComplete:(id)fp8;
- (unsigned int)maximumCachedCompletionCount;
- (void)_doUpdateForPrefix:(id)fp8;
- (void)_bookmarksDidChange:(id)fp8;
- (void)_historyDidChange:(id)fp8;
- (void)dealloc;
- (id)initWithBookmarkCollection:(id)fp8 maxResults:(unsigned int)fp12 searchableCollectionsMask:(int)fp16;

@end

