/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ViewReuseManagerDelegate <NSObject>
- (void)viewReuseManager:(id)fp8 prepareView:(id)fp12 toRepresentObjectAtIndex:(unsigned int)fp16;
- (void)viewReuseManager:(id)fp8 willRecycleView:(id)fp12;
@end

