/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol WBSFluidProgressControllerDelegate
- (void)fluidProgressController:(id)fp8 setProgressToCurrentPosition:(id)fp12;
- (void)fluidProgressControllerFinishProgressBar:(id)fp8 animateFillFade:(BOOL)fp12;
- (void)fluidProgressController:(id)fp8 startFluidProgressBar:(id)fp12 animateFillFade:(BOOL)fp16;
- (void)fluidProgressController:(id)fp8 updateFluidProgressBar:(id)fp12;
@end

