/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PurplePageLoadTestRunner.h"

@interface ZoomTestProcessor : PurplePageLoadTestRunner
{
    int _actionCount;
}

- (BOOL)performActionForTimer:(id)fp8;
- (BOOL)startPageAction:(id)fp8;

@end

