/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioServicesAddSystemSoundCompletion.h"

@interface CKBlankTranscriptController : _AudioServicesAddSystemSoundCompletion
{
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)wantsFullScreenLayout;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

