/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol CKTranscriptComposeDelegate <NSObject>
- (void)transcriptController:(id)fp8 didSelectNewConversation:(id)fp12;
- (BOOL)supportsAttachments;
- (void)showNewMessageCompositionForMessageParts:(id)fp8;
- (void)showForwardedMessageParts:(id)fp8;
- (void)transcriptController:(id)fp8 didSendMessageInConversation:(id)fp12;
- (void)transcriptController:(id)fp8 willSendComposition:(id)fp12 inConversation:(id)fp16;
- (void)didCancelComposition:(id)fp8;
@end

