/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol AVCaptureFileOutputRecordingDelegate <NSObject>
- (void)captureOutput:(id)fp8 didFinishRecordingToOutputFileAtURL:(id)fp12 fromConnections:(id)fp16 error:(id)fp20;
@end

