/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol CNFRegWizardControllerDelegate <NSObject>
- (void)firstRunControllerDidFinish:(id)fp8 finished:(BOOL)fp12;
@end

