/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@interface ConferenceManagementTable : _ABAddressBookBeginExclusiveRead
{
}

- (void)animateDeletionOfRowWithCell:(id)fp8 viaEdge:(unsigned int)fp12;
- (void)completeRowDeletionAnimation;
- (id)initWithFrame:(struct CGRect)fp8;

@end

