/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DialerLCDFieldProtocol <NSObject>
- (void)deleteCharacter;
- (BOOL)highlighted;
- (BOOL)inCallMode;
- (void)setDelegate:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setInCallMode:(BOOL)fp8;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12;
- (id)text;
@end

