/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABNewPersonViewControllerDelegate-Protocol.h"
#import "ABPeoplePickerNavigationControllerDelegate-Protocol.h"
#import "DialerViewDelegate-Protocol.h"
#import "TPDialerKeypadDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class NSString, NSTimer, PHAbstractDialerView, UINavigationController;

@interface DialerController : PhoneViewController <ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate, DialerViewDelegate, UIActionSheetDelegate, TPDialerKeypadDelegate>
{
    PHAbstractDialerView *_dialerView;
    UINavigationController *_newContactNavigationController;
    NSTimer *_deleteTimer;
    NSTimer *_lookupTimer;
    NSString *_lastDialedNumberCache;
    NSString *_myPrefix;
    int _shouldUseMyPrefixAsHint;
    unsigned int _calledNumber:1;
    unsigned int _didDeleteRepeat:1;
    unsigned int _dtmfPlaying;
    BOOL _shouldHideDeleteButtonWhenEmpty;
    int _dialerType;
}

+ (id)defaultPNGName;
+ (BOOL)launchFieldTestIfNeeded:(id)fp8;
+ (void)playDTMFToneForKey:(unsigned char)fp8;
+ (BOOL)shouldStringAutoDial:(id)fp8 givenLastChar:(BOOL)fp12;
+ (void)stopPlayingDTMFTone;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void)_addButtonClicked:(id)fp8;
- (void)_addToExistingContact;
- (void)_addToNewContact;
- (void)_callButtonLongPress;
- (void)_callButtonPressed:(id)fp8;
- (void)_clearDisplayIfNecessary;
- (void)_deleteButtonClicked:(id)fp8;
- (void)_deleteButtonDown:(id)fp8;
- (void)_deleteRepeat;
- (void)_dialVoicemail;
- (void)_dismissNewContactView:(BOOL)fp8;
- (void)_getPersonName:(id *)fp8 personLabel:(id *)fp12 personUID:(int *)fp16 forPhoneNumberString:(id)fp20;
- (void)_handleSIMInsertionOrRemoval;
- (void)_hideNewContactView;
- (id)_myPrefix;
- (void *)_newPersonWithValue:(id)fp8 forMultiValueProperty:(int)fp12;
- (void)_phonePad:(id)fp8 appendString:(id)fp12 suppressClearingDialedNumber:(BOOL)fp16;
- (id)_qualifyNumberIfNecessary:(id)fp8;
- (BOOL)_shouldUseMyPrefixAsHint;
- (void)_showNewContactView;
- (void)_startDeleteTimer;
- (void)_statusBarHeightChanged:(id)fp8;
- (void)_stopDeleteTimer;
- (void)_stopLookupTimer;
- (void)_updateCallButtonEnabledState:(id)fp8;
- (void)_updateCallButtonEnabledState:(id)fp8 updateNameNow:(BOOL)fp12;
- (void)_updateLCDNameLabelWithAMatchingName:(BOOL)fp8;
- (void)_updateLCDNameLabelWithOriginallyPastedString:(id)fp8;
- (void)_updateName;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)applicationDidResume;
- (void)dealloc;
- (int)dialerType;
- (id)dialerView;
- (void)dialerView:(id)fp8 stringWasPasted:(id)fp12;
- (void)dialerViewTextDidChange:(id)fp8;
- (void)didReceiveMemoryWarning;
- (id)initWithDialerType:(int)fp8;
- (BOOL)isShowingDoubleHeightStatusBar;
- (id)lastDialedNumber;
- (void)loadView;
- (void)newPersonViewController:(id)fp8 didCompleteWithNewPerson:(void *)fp12;
- (void)peoplePickerNavigationController:(id)fp8 insertEditorDidConfirm:(BOOL)fp12 forPerson:(void *)fp16;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldShowInsertEditorForPerson:(void *)fp12 insertProperty:(int *)fp16 copyInsertValue:(id *)fp20 copyInsertLabel:(id *)fp24;
- (void)peoplePickerNavigationControllerDidCancel:(id)fp8;
- (void)performCallAction;
- (void)performCharacterAddAction:(id)fp8;
- (void)performDeleteAction;
- (void)phonePad:(id)fp8 appendString:(id)fp12;
- (void)phonePad:(id)fp8 appendString:(id)fp12 playDTMFTone:(BOOL)fp16;
- (void)phonePad:(id)fp8 dialerCharacterButtonWasHeld:(unsigned int)fp12;
- (void)phonePad:(id)fp8 keyDown:(BOOL)fp12;
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;
- (void)phonePad:(id)fp8 replaceLastDigitWithString:(id)fp12;
- (void)phonePadDeleteLastDigit:(id)fp8;
- (void)phonePadDidEndSounds:(id)fp8;
- (void)prepareForSnapshot;
- (void)setDialerType:(int)fp8;
- (void)setLastDialedNumber:(id)fp8;
- (void)setShouldHideDeleteButtonWhenEmpty:(BOOL)fp8;
- (BOOL)shouldHideDeleteButtonWhenEmpty;
- (BOOL)shouldSnapshot;
- (void)starkInCallViewControllerAppearedNotification:(id)fp8;
- (void)unloadView;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

