/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UIButton;

@interface InCallLCDField : _ABAddressBookBeginExclusiveRead
{
    UIButton *_button;
    id _delegate;
    unsigned int _textIsPlaceholder:1;
    unsigned int _buttonIsDelete:1;
}

+ (float)defaultLabelFontSize;
+ (float)defaultTextFontSize;
- (void)_deleteButtonClicked:(id)fp8;
- (float)_labelVInset;
- (void)_removeButton;
- (void)_sendButtonClicked:(id)fp8;
- (void)_showButtonWithTitle:(id)fp8 action:(SEL)fp12;
- (float)_textVInset;
- (void)_updateButton;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (void)setPlaceholderText:(id)fp8 animating:(BOOL)fp12;
- (void)setShowsDeleteButton:(BOOL)fp8;
- (void)setShowsSendButton:(BOOL)fp8;
- (void)setText:(id)fp8;
- (BOOL)showsSendButton;
- (id)text;
- (struct CGRect)textFrame;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (id)unformattedText;

@end

