/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSString, NSTimer, TPLCDTextView, UIButton, UIView;

@interface InCallLCDView : _ABAddressBookBeginExclusiveRead
{
    TPLCDTextView *_labelView2;
    TPLCDTextView *_textView2;
    UIView *_activeIndicator;
    int _activePosition;
    int _conferencePosition;
    TPLCDTextView *_oldLabelView;
    TPLCDTextView *_oldLabelView2;
    TPLCDTextView *_oldTextView;
    TPLCDTextView *_oldTextView2;
    UIView *_oldActiveIndicator;
    UIButton *_conferenceButton;
    NSTimer *_alternatingTimer;
    NSString *_originalLabel;
    NSString *_originalLabel2;
    NSString *_alternateLabel;
    NSString *_alternateLabel2;
    id _delegate;
    unsigned int _ignoreLayout:1;
    unsigned int _animating:1;
    unsigned int _progress:1;
    unsigned int _dimmedText:2;
    unsigned int _canTruncateLabel:2;
    unsigned int _enableFade:1;
    unsigned int _changingForAlternate:1;
    BOOL _callerIsAmbiguous;
}

- (void)_alternate:(id)fp8;
- (void)_cancelScrollingForTextView:(id)fp8;
- (void)_conferenceButtonClicked:(id)fp8;
- (void)_enableScrollingForTextView:(id)fp8 start:(BOOL)fp12;
- (void)_positionActiveCallIndicator;
- (void)_positionConferenceButton;
- (void)_removeAnimationViews;
- (void)_startAlternating;
- (void)_stopAlternating;
- (void)_updateForActivePosition;
- (void)_updateTextAttributes;
- (void)animateCallMergeWithDuration:(float)fp8;
- (void)animateLabel;
- (void)animateToActivePosition:(int)fp8 label:(id)fp12 label2:(id)fp16;
- (BOOL)callerIsAmbiguous;
- (int)conferencePosition;
- (void)dealloc;
- (id)label2;
- (void)layoutSubviews;
- (void)lcdTextViewCompletedScroll:(id)fp8;
- (id)originalLabel;
- (id)originalLabel2;
- (void)performTextFadeWithDuration:(float)fp8 delay:(float)fp12 forView:(id *)fp16 newText:(id)fp20 setter:(SEL)fp24 position:(int)fp28;
- (void)popText;
- (void)removeFromSuperview;
- (void)setActiveIndicatorShowsProgress:(BOOL)fp8;
- (void)setActivePosition:(int)fp8;
- (void)setAlternateLabel2:(id)fp8;
- (void)setAlternateLabel:(id)fp8;
- (void)setCallerIsAmbiguous:(BOOL)fp8;
- (void)setCanTruncateLabel2:(BOOL)fp8;
- (void)setCanTruncateLabel:(BOOL)fp8;
- (void)setConferencePosition:(int)fp8;
- (void)setDelegate:(id)fp8;
- (void)setLabel2:(id)fp8;
- (void)setLabel2:(id)fp8 alternateLabel:(id)fp12;
- (void)setLabel:(id)fp8;
- (void)setLabel:(id)fp8 alternateLabel:(id)fp12;
- (void)setLabelVisible:(BOOL)fp8;
- (void)setSubImage:(id)fp8;
- (void)setText2:(id)fp8;
- (void)setText2:(id)fp8 animating:(BOOL)fp12;
- (void)setText2Dimmed:(BOOL)fp8;
- (void)setText:(id)fp8;
- (void)setText:(id)fp8 animating:(BOOL)fp12;
- (void)setTextChangeFadingEnabled:(BOOL)fp8;
- (void)setTextDimmed:(BOOL)fp8;
- (void)setTextScrolls:(BOOL)fp8;
- (id)text2;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;

@end

