/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneApplication.h"

@class TUCall;

@interface MobilePhoneApplication : PhoneApplication
{
    BOOL _outstandingDecline;
    TUCall *_outstandingDeclineCall;
}

- (void)_handlePhoneAppHeardAboutDecline;
- (void)_incomingCallEnded;
- (BOOL)_isIPad;
- (void)_stopCaringAboutDecline;
- (int)addressBookUIStyle;
- (BOOL)alwaysShowVideoConferenceController;
- (void)applicationDidFinishLaunching:(id)fp8;
- (BOOL)badgesMissedFaceTime;
- (BOOL)badgesMissedFaceTimeAudio;
- (BOOL)badgesMissedTelephonyCalls;
- (BOOL)contentViewCanRotate;
- (void)dealloc;
- (int)defaultAction;
- (BOOL)dialerIsNumericOnly;
- (void)handleResumeEvent:(struct __GSEvent *)fp8;
- (BOOL)outstandingDecline;
- (id)outstandingDeclineCall;
- (void)setOutstandingDecline:(BOOL)fp8;
- (void)setOutstandingDeclineCall:(id)fp8;
- (BOOL)showSplashScreenOnSignin;
- (BOOL)showsFaceTime;
- (BOOL)showsFaceTimeAudio;
- (BOOL)showsFaceTimeAudioFavorites;
- (BOOL)showsFaceTimeAudioRecents;
- (BOOL)showsFaceTimeFavorites;
- (BOOL)showsFaceTimeRecents;
- (BOOL)showsPhoneDialer;
- (BOOL)showsPhoneVoicemail;
- (BOOL)showsTelephonyCalls;
- (BOOL)showsTelephonyFavorites;
- (BOOL)showsTelephonyRecents;
- (BOOL)tabBarCanSlide;
- (BOOL)tabBarFillsScreen;
- (unsigned int)userInterfaceStyle;
- (BOOL)usesBlendModes;
- (int)wizardGlobalAppearanceStyle;

@end

