/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "DialerLCDFieldDelegate-Protocol.h"

@class UIControl, UIView<DialerLCDFieldProtocol>, UIView<TPDialerKeypadProtocol>;

@interface PHAbstractDialerView : _ABAddressBookBeginExclusiveRead <DialerLCDFieldDelegate>
{
    BOOL _inCallMode;
    UIView<DialerLCDFieldProtocol> *_lcdView;
    UIView<TPDialerKeypadProtocol> *_phonePadView;
    id <DialerViewDelegate> _delegate;
    UIControl *_addContactButton;
    UIControl *_callButton;
    UIControl *_deleteButton;
}

- (id)addContactButton;
- (id)callButton;
- (void)dealloc;
- (id)delegate;
- (id)deleteButton;
- (void)dialerField:(id)fp8 stringWasPasted:(id)fp12;
- (void)dialerLCDFieldTextDidChange:(id)fp8;
- (BOOL)inCallMode;
- (id)lcdView;
- (id)phonePadView;
- (void)setAddContactButton:(id)fp8;
- (void)setCallButton:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)setDeleteButton:(id)fp8;
- (void)setInCallMode:(BOOL)fp8;
- (void)setLcdView:(id)fp8;
- (void)setPhonePadView:(id)fp8;

@end

