/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "ABPeoplePickerNavigationControllerDelegate-Protocol.h"
#import "PhoneTabViewController-Protocol.h"

@interface PHAddressBookController : _ABAddressBookBeginExclusiveRead <PhoneTabViewController, ABPeoplePickerNavigationControllerDelegate>
{
    int _abuiStyle;
}

+ (CDAnonymousStruct1)badge;
+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
- (void)_applicationDeactivated;
- (void)_restoreState;
- (void)_saveState;
- (void)_updatePickerBanner:(id)fp8;
- (void)_updatePickerPhoneNumber:(id)fp8;
- (int)abuiStyle;
- (void)applicationWillSuspend;
- (void)dealloc;
- (void)handleURL:(id)fp8;
- (id)initWithStyle:(int)fp8;
- (void)loadView;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (void)peoplePickerNavigationControllerDidCancel:(id)fp8;
- (void)prepareForSnapshot;
- (void)presentViewController:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void *)savedPerson;
- (void)setAbuiStyle:(int)fp8;
- (void)setSavedPerson:(void *)fp8;
- (BOOL)shouldSaveAndRestoreState;
- (BOOL)shouldSnapshot;
- (BOOL)tabBarControllerShouldSelectViewController:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

