/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "AVCaptureFileOutputRecordingDelegate-Protocol.h"

@class AVCaptureConnection, AVCaptureMovieFileOutput, AVCaptureSession, NSError, NSString, NSTimer;

@interface PHAudioRecorder : _ABAddressBookBeginExclusiveRead <AVCaptureFileOutputRecordingDelegate>
{
    AVCaptureSession *_captureSession;
    AVCaptureMovieFileOutput *_captureFileOutput;
    AVCaptureConnection *_captureConnection;
    NSError *_buildCaptureSessionError;
    NSTimer *_updateTimer;
    BOOL _isRecording;
    BOOL _handlingStop;
    NSString *_outputFile;
    id <PHAudioRecorderDelegate> _audioRecorderDelegate;
    double _maxRecordedDuration;
}

- (void)_buildCaptureSessionAndOutputIfNecessary;
- (void)_captureSessionErrored:(id)fp8;
- (void)_captureSessionWasInterrupted:(id)fp8;
- (void)_stopWithError:(id)fp8;
- (void)_updateRecordProgress:(id)fp8;
- (id)audioRecorderDelegate;
- (id)buildCaptureSessionError;
- (id)captureConnection;
- (id)captureFileOutput;
- (void)captureOutput:(id)fp8 didFinishRecordingToOutputFileAtURL:(id)fp12 fromConnections:(id)fp16 error:(id)fp20;
- (id)captureSession;
- (void)dealloc;
- (BOOL)handlingStop;
- (id)init;
- (BOOL)isRecording;
- (double)maxRecordedDuration;
- (id)outputFile;
- (void)setAudioRecorderDelegate:(id)fp8;
- (void)setHandlingStop:(BOOL)fp8;
- (void)setIsRecording:(BOOL)fp8;
- (void)setMaxRecordedDuration:(double)fp8;
- (void)setOutputFile:(id)fp8;
- (void)setUpdateTimer:(id)fp8;
- (BOOL)startWithError:(id *)fp8;
- (void)stop;
- (id)updateTimer;

@end

