/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol PHAudioRecorderDelegate
- (void)audioRecorderContinuedWithFile:(id)fp8 duration:(double)fp12;
- (void)audioRecorderEndedWithFile:(id)fp8 duration:(double)fp12 error:(id)fp20;
- (void)audioRecorderStartedWithFile:(id)fp8;
@end

