/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol PHAudioPlayerDelegate
- (void)startedPlayingWithDataSource:(id)fp8;
- (void)stoppedPlayingWithDataSource:(id)fp8 withError:(id)fp12;
- (void)updateWithElapsedTime:(double)fp8 playableTime:(double)fp16 totalTime:(double)fp24 isPlaying:(BOOL)fp32 isPlayable:(BOOL)fp36 dataSource:(id)fp40;
@end

