/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PHAudioPlayerDataSource-Protocol.h"

@class NSObject<OS_dispatch_queue>, VMVoicemail;

@interface PHAudioPlayerVoicemailDataSource : _ABAddressBookBeginExclusiveRead <PHAudioPlayerDataSource>
{
    VMVoicemail *_voicemail;
    NSObject<OS_dispatch_queue> *_modifyingFileSizeQueue;
    unsigned long long _expectedTotalBytes;
    unsigned long long _availableBytes;
}

- (void)_deregisterForVoicemailNotifications;
- (void)_handleDataAvailable:(id)fp8;
- (void)_handlePlayableDurationChanged:(id)fp8;
- (void)_registerForVoicemailNotifications;
- (id)audioFilePath;
- (unsigned long long)availableBytes;
- (void)dealloc;
- (double)duration;
- (unsigned long long)expectedTotalBytes;
- (BOOL)fullFileAvailable;
- (id)initWithVoicemail:(id)fp8;
- (id)voicemail;

@end

