/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UIView;

@interface PHCellContentView : _ABAddressBookBeginExclusiveRead
{
    UIView *_viewToRender;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)setViewToRender:(id)fp8;
- (id)viewToRender;

@end

