/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class PHConferenceParticipantCellRingButton, UIButton, UILabel;

@interface PHConferenceParticipantCell : _ABAddressBookBeginExclusiveRead
{
    BOOL _shouldShowPrivateButton;
    id <PHConferenceParticipantCellProtocol> _delegate;
    UILabel *_nameLabel;
    UIButton *_endCallButton;
    PHConferenceParticipantCellRingButton *_privateButton;
}

- (void)buttonTapped:(id)fp8;
- (void)dealloc;
- (id)delegate;
- (id)endCallButton;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)makeHeld;
- (id)nameLabel;
- (id)privateButton;
- (void)setDelegate:(id)fp8;
- (void)setEndCallButton:(id)fp8;
- (void)setPrivateButton:(id)fp8;
- (void)setRepresentedCall:(id)fp8;
- (void)setShouldShowPrivateButton:(BOOL)fp8;
- (BOOL)shouldShowPrivateButton;

@end

