/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHHandsetDialerLCDView.h"

@class NSLayoutConstraint, PHTextCycleLabel;

@interface PHEmergencyHandsetDialerLCDView : PHHandsetDialerLCDView
{
    PHTextCycleLabel *_emergencyTitleLabel;
    NSLayoutConstraint *_spacingBetweenNumberLabelAndEmergencyLabel;
}

- (void)_applyLayoutConstraints;
- (void)_updateEmergencyLabel;
- (void)applyLayoutConstraints;
- (void)dealloc;
- (void)deleteCharacter;
- (id)emergencyTitleLabel;
- (id)initWithFrame:(struct CGRect)fp8 forDialerType:(int)fp24;
- (id)lcdColor;
- (id)newAddContactButton;
- (id)newDeleteButton;
- (id)newNameAndLabelView;
- (void)setSpacingBetweenNumberLabelAndEmergencyLabel:(id)fp8;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12 name:(id)fp16 label:(id)fp20;
- (id)spacingBetweenNumberLabelAndEmergencyLabel;

@end

