/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "DialerViewDelegate-Protocol.h"
#import "PhoneBaseViewController-Protocol.h"
#import "TPDialerKeypadDelegate-Protocol.h"

@class NSTimer, PHHandsetDialerLCDView, PHHandsetDialerView, UIButton;

@interface PHEmergencyDialerViewController : _ABAddressBookBeginExclusiveRead <PhoneBaseViewController, TPDialerKeypadDelegate, DialerViewDelegate>
{
    BOOL _inApplicationMode;
    BOOL _callEnding;
    short _currentState;
    PHHandsetDialerLCDView *_lcdView;
    PHHandsetDialerView *_dialerView;
    NSTimer *_callDurationTimer;
    UIButton *_backButton;
    UIButton *_endButton;
}

+ (id)defaultPNGName;
+ (int)statusBarStyle;
+ (int)viewType;
- (id)backButton;
- (void)backButtonTapped:(id)fp8;
- (void)callButtonTapped:(id)fp8;
- (id)callDurationTimer;
- (BOOL)callEnding;
- (void)callStatusChangedNotification:(id)fp8;
- (void)continueCyclingEmergencyTitleLabel;
- (id)currentCallStatusStringForDisplay;
- (short)currentState;
- (void)dealloc;
- (void)deleteButtonTapped:(id)fp8;
- (void)dialEmergencyCall;
- (id)dialerView;
- (id)endButton;
- (void)endButtonTapped:(id)fp8;
- (void)handleURL:(id)fp8;
- (BOOL)inApplicationMode;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)lcdView;
- (void)loadView;
- (void)noteTintColorForBackgroundStyleChanged:(id)fp8;
- (void)phonePad:(id)fp8 appendString:(id)fp12;
- (void)phonePad:(id)fp8 dialerCharacterButtonWasHeld:(unsigned int)fp12;
- (void)phonePad:(id)fp8 keyDown:(BOOL)fp12;
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;
- (void)phonePad:(id)fp8 replaceLastDigitWithString:(id)fp12;
- (void)phonePadDeleteLastDigit:(id)fp8;
- (void)phonePadDidEndSounds:(id)fp8;
- (void)phonePadWillBeginSounds:(id)fp8;
- (void)prepareForSnapshot;
- (void)prepareForTransitionInFromViewType:(int)fp8 animated:(BOOL)fp12;
- (void)prepareToHandleURL:(id)fp8;
- (void)setBackButton:(id)fp8;
- (void)setCallDurationTimer:(id)fp8;
- (void)setCallEnding:(BOOL)fp8;
- (void)setCurrentState:(short)fp8;
- (void)setCurrentState:(short)fp8 animated:(BOOL)fp12;
- (void)setDialerView:(id)fp8;
- (void)setEndButton:(id)fp8;
- (void)setInApplicationMode:(BOOL)fp8;
- (void)setLcdView:(id)fp8;
- (BOOL)shouldDisableEdgeClip;
- (BOOL)shouldSnapshot;
- (void)transitionInFromViewType:(int)fp8 animated:(BOOL)fp12 completionBlock:(id)fp(null);
- (void)updateEmergencyTitleLabelForCallDuration;
- (void)updateViewControllerForOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;

@end

