/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABPeoplePickerNavigationControllerPrivateMemberCellDelegate-Protocol.h"
#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ABFavoritesEntry, ABPeoplePickerNavigationController, NSDictionary, UIActionSheet, UITableView, _UIContentUnavailableView;

@interface PHFavoritesViewController : PhoneViewController <UITableViewDataSource, UITableViewDelegate, ABUnknownPersonViewControllerDelegate, ABPeoplePickerNavigationControllerPrivateMemberCellDelegate, UIActionSheetDelegate>
{
    UITableView *_table;
    _UIContentUnavailableView *_noContentView;
    ABPeoplePickerNavigationController *_peoplePickerController;
    ABFavoritesEntry *_selectedABFavoritesEntry;
    UIActionSheet *_disambiguationSheet;
    NSDictionary *_disambiguationSheetContext;
    unsigned int _suspended:1;
    unsigned int _ignoreFavoritesDidChangeNotification:1;
    unsigned int _postponeTableReloadFromFavoritesChange:1;
    unsigned int _needsTableReloadFromFavoritesChange:1;
}

+ (BOOL)requiresNavigationControllerContainer;
+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
- (void)_addButtonClicked:(id)fp8;
- (void)_addEntryFromPeoplePickerForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 animateView:(id)fp20;
- (void)_addEntryFromPeoplePickerForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 animateView:(id)fp20 favoritesEntryType:(int)fp24;
- (void)_favoritesManagerSignificantChangeNotification:(id)fp8;
- (void)_handleContentSizeCategoryDidChange:(id)fp8;
- (void)_handleFavoritesShowsContactPhotosChanged:(id)fp8;
- (void)_updateContentView;
- (void)_updateNavButtons;
- (int)absoluteIndexOfFilteredIndex:(int)fp8;
- (void)accessoryButtonTapped:(id)fp8 withEvent:(id)fp12;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)buttonTitlesForPossibleFavoriteTypes:(id)fp8;
- (void)dealloc;
- (void)deleteButtonPressedForIndexPath:(id)fp8;
- (void)didReceiveMemoryWarning;
- (void)dismissPeoplePicker;
- (id)init;
- (void)loadView;
- (id)noContentView;
- (void)peoplePickerNavigationController:(id)fp8 insertEditorDidConfirm:(BOOL)fp12 forPerson:(void *)fp16;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldAllowSelectingPersonWithRecordID:(int)fp12;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20 withMemberCell:(id)fp24;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 withLinkedPeople:(struct __CFArray *)fp16 memberCell:(id)fp20;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldShowInsertEditorForPerson:(void *)fp12 insertProperty:(int *)fp16 copyInsertValue:(id *)fp20 copyInsertLabel:(id *)fp24;
- (void)peoplePickerNavigationControllerDidCancel:(id)fp8;
- (id)possibleFavoriteTypesForProperty:(int)fp8;
- (void)restoreState;
- (void)savePreferences;
- (int)selectedIndex;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)shouldSnapshot;
- (void)showCardViewerForPerson:(void *)fp8 withTitle:(id)fp12 animate:(BOOL)fp16;
- (BOOL)showsNoContentView;
- (id)table;
- (void)tableView:(id)fp8 accessoryButtonTappedForRowWithIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canMoveRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 targetIndexPathForMoveFromRowAtIndexPath:(id)fp12 toProposedIndexPath:(id)fp16;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)unknownPersonViewController:(id)fp8 didResolveToPerson:(void *)fp12;
- (void)unloadView;
- (BOOL)usesPersonBasedFavorites;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

