/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UIImage;

@interface PHFavoritesEntry : _ABAddressBookBeginExclusiveRead
{
    UIImage *_thumbnail;
    UIImage *_starkThumbnail;
    BOOL _isPersonImage;
}

+ (BOOL)_usesFlatImages;
+ (id)sharedMonogrammer;
+ (id)sharedStarkMonogrammer;
- (void)dealloc;
- (id)initWithDictionaryRepresentation:(id)fp8 addressBook:(void *)fp12;
- (BOOL)isPersonImage;
- (void)loadStarkThumbnailIfNecessary;
- (void)loadThumbnailIfNecessary;
- (void)setIsPersonImage:(BOOL)fp8;
- (id)starkThumbnail;
- (id)thumbnail;

@end

