/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@interface PHFavoritesManager : _ABAddressBookBeginExclusiveRead
{
}

+ (void)_abFavoritesEntryChangedNotification:(id)fp8;
+ (void)_abfavoritesListChangedNotification:(id)fp8;
+ (void)_clearCachedFavorites;
+ (id)_favoritesWithPredicate:(id)fp8;
+ (void)_ftcServiceAvailabilityDidChangeNotification:(id)fp8;
+ (void)_phoneApplicationAddressBookChangedNotification:(id)fp8;
+ (id)allFavorites;
+ (id)currentFavorites;
+ (BOOL)dial:(id)fp8 withService:(int)fp12 forFavoriteEntry:(id)fp16;
+ (BOOL)dialFavoriteEntry:(id)fp8;
+ (void)initialize;
+ (id)predicateForFaceTimeAudioEntries;
+ (id)predicateForFaceTimeEntries;
+ (id)predicateForTelephonyEntries;
+ (void)recacheIdentitiesSoon;
+ (void)save;
+ (id)starkFavorites;

@end

