/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSString, UILabel;

@interface PHHandsetDialerNameLabelView : _ABAddressBookBeginExclusiveRead
{
    UILabel *_nameAndLabelLabel;
    float _fontSize;
    NSString *_displayedName;
    NSString *_displayedLabel;
}

- (void)dealloc;
- (id)displayedLabel;
- (id)displayedName;
- (float)fontSize;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGSize)intrinsicContentSize;
- (id)nameAndLabelLabel;
- (void)setDisplayedLabel:(id)fp8;
- (void)setDisplayedName:(id)fp8;
- (void)setFontSize:(float)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setNameAndLabelLabel:(id)fp8;
- (void)showName:(id)fp8 label:(id)fp12 animated:(BOOL)fp16;
- (id)textColor;

@end

