/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHAbstractDialerView.h"

#import "TPDialerKeypadDelegate-Protocol.h"

@class NSLayoutConstraint, UIView;

@interface PHHandsetDialerView : PHAbstractDialerView <TPDialerKeypadDelegate>
{
    UIView *_leftBlankView;
    UIView *_rightBlankView;
    UIView *_bottomBlankView;
    UIView *_topBlankView;
    NSLayoutConstraint *_statusBarToLCDViewConstraint;
    NSLayoutConstraint *_callButtonKeypadOffsetConstraint;
}

- (id)bottomBlankView;
- (id)callButtonKeypadOffsetConstraint;
- (void)createConstraints;
- (void)dealloc;
- (id)dialerColor;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)layoutConstraintMetrics;
- (id)leftBlankView;
- (id)newCallButton;
- (id)newLCDView;
- (id)newNumberPadView;
- (id)rightBlankView;
- (void)setBottomBlankView:(id)fp8;
- (void)setCallButtonKeypadOffsetConstraint:(id)fp8;
- (void)setInCallMode:(BOOL)fp8;
- (void)setLeftBlankView:(id)fp8;
- (void)setRightBlankView:(id)fp8;
- (void)setStatusBarToLCDViewConstraint:(id)fp8;
- (void)setTopBlankView:(id)fp8;
- (id)statusBarToLCDViewConstraint;
- (id)topBlankView;
- (void)updateContraintsForStatusBar;

@end

