/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "DialerLCDFieldProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, PHHandsetDialerNameLabelView, UIButton, UILabel, UILongPressGestureRecognizer;

@interface PHHandsetDialerLCDView : _ABAddressBookBeginExclusiveRead <DialerLCDFieldProtocol, UIGestureRecognizerDelegate>
{
    BOOL _addContactButtonVisible;
    BOOL _deleteButtonVisible;
    BOOL _highlighted;
    BOOL _inCallMode;
    int _dialerType;
    UIButton *_deleteButton;
    UIButton *_addContactButton;
    id <DialerLCDFieldDelegate> _delegate;
    PHHandsetDialerNameLabelView *_nameAndLabelView;
    UILabel *_numberLabel;
    UILongPressGestureRecognizer *_longPressRecognizer;
    NSLayoutConstraint *_numberLabelVerticalConstraint;
    NSLayoutConstraint *_nameAndLabelViewConstraint;
    NSArray *_numberLabelHorizontalConstraints;
}

- (void)_displayCallout;
- (void)_makeCalloutVisible:(BOOL)fp8;
- (void)_menuDidHide:(id)fp8;
- (void)_menuWillHide:(id)fp8;
- (void)_requestMakeCutCopyPasteCalloutVisible:(BOOL)fp8;
- (void)_setHighlighted:(BOOL)fp8;
- (id)addContactButton;
- (void)applyLayoutConstraints;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)fp8 withSender:(id)fp12;
- (void)copy:(id)fp8;
- (void)dealloc;
- (id)delegate;
- (id)deleteButton;
- (float)deleteButtonVerticalConstantValue;
- (void)deleteCharacter;
- (int)dialerType;
- (float)frameHeight;
- (id)generateNumberLabelHorizontalConstraints;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)handleLongPress:(id)fp8;
- (BOOL)highlighted;
- (BOOL)inCallMode;
- (id)initWithFrame:(struct CGRect)fp8 forDialerType:(int)fp24;
- (struct CGSize)intrinsicContentSize;
- (id)lcdColor;
- (id)longPressRecognizer;
- (float)nameAndLabelFontSize;
- (id)nameAndLabelView;
- (id)nameAndLabelViewConstraint;
- (id)newAddContactButton;
- (id)newDeleteButton;
- (id)newNameAndLabelView;
- (id)numberLabel;
- (id)numberLabelFont;
- (id)numberLabelHorizontalConstraints;
- (float)numberLabelMaximumFontSize;
- (float)numberLabelMinimumFontSize;
- (float)numberLabelVerticalConstantValue;
- (id)numberLabelVerticalConstraint;
- (void)paste:(id)fp8;
- (BOOL)resignFirstResponder;
- (void)setAddContactButton:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)setDeleteButton:(id)fp8;
- (void)setDialerType:(int)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setInCallMode:(BOOL)fp8;
- (void)setLongPressRecognizer:(id)fp8;
- (void)setName:(id)fp8 numberLabel:(id)fp12;
- (void)setNameAndLabelView:(id)fp8;
- (void)setNameAndLabelViewConstraint:(id)fp8;
- (void)setNumberLabel:(id)fp8;
- (void)setNumberLabelHorizontalConstraints:(id)fp8;
- (void)setNumberLabelVerticalConstraint:(id)fp8;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12 name:(id)fp16 label:(id)fp20;
- (float)spacingBetweenLCDBottomAndNameView;
- (id)text;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)updateAddAndDeleteButtonForText:(id)fp8 name:(id)fp12 animated:(BOOL)fp16;

@end

