/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "UIApplicationDelegate-Protocol.h"

@class CUTWeakReference, NSString, PhoneRootViewController, UIAlertView, UIView, UIViewController<PhoneBaseViewController>, UIWindow;

@interface PhoneApplication : _ABAddressBookBeginExclusiveRead <UIApplicationDelegate>
{
    PhoneRootViewController *_rootController;
    UIWindow *_window;
    UIViewController<PhoneBaseViewController> *_currentController;
    CUTWeakReference *_currentActionSheetWeakReference;
    UIAlertView *_alertView;
    id _alertHandler;
    double _launchTime;
    unsigned int _isDialingCall:1;
    unsigned int _suspendingApplication:1;
    unsigned int _resumingApplication:1;
    unsigned int _applicationResumedViaURL:1;
    NSString *_cachedApplicationBadgeString;
    BOOL _applicationHandlingFaceTimeURL;
    BOOL _alertViewManuallyDisplayed;
    UIView *_alertViewManualBackground;
}

+ (Class)controllerClassForTabViewType:(int)fp8;
+ (id)sharedNumberFormatter;
+ (id)viewControllerForRootViewType:(int)fp8;
+ (id)viewControllerForTabViewType:(int)fp8;
- (BOOL)_activeFaceTimeCallExists;
- (void)_callStatusChanged:(id)fp8;
- (void)_displayedCallsChanged:(id)fp8;
- (void)_faceTimeDismissed:(id)fp8;
- (BOOL)_faceTimeInvitationExists;
- (void)_forceWindowFront;
- (void)_ftcServiceAvailabilityChanged:(id)fp8;
- (void)_handleVoicemailUIStatusChangedNotification:(id)fp8;
- (BOOL)_inFaceTime;
- (void)_initializeUI;
- (void)_localeChangedNotification:(id)fp8;
- (void)_logSwitch;
- (void)_performDialOfNumber:(id)fp8 withCall:(id)fp12;
- (void)_releaseAddressBook;
- (void)_resetCurrentViewController;
- (void)_revertAddressBook;
- (void)_scroll;
- (struct __CTServerConnection *)_serverConnection;
- (void)accessibilitySettingsChangedNotification:(id)fp8;
- (BOOL)activeFaceTimeCallExists;
- (void *)addressBook;
- (int)addressBookUIStyle;
- (id)alertHandler;
- (id)alertView;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)alertViewManualBackground;
- (BOOL)alertViewManuallyDisplayed;
- (BOOL)alwaysShowVideoConferenceController;
- (void)applicationDidEndResumeAnimation;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)applicationDidResume;
- (void)applicationDidResumeForEventsOnly;
- (void)applicationDidResumeFromUnderLock;
- (BOOL)applicationHandlingFaceTimeURL;
- (void)applicationOpenURL:(id)fp8;
- (void)applicationResume:(struct __GSEvent *)fp8;
- (BOOL)applicationResumedViaURL;
- (BOOL)applicationSuspend:(struct __GSEvent *)fp8 settings:(id)fp12;
- (id)applicationTintColor;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationWillSuspendForEventsOnly;
- (BOOL)authorizedToUseAddressBook;
- (int)backdropStyle;
- (BOOL)badgesMissedFaceTime;
- (BOOL)badgesMissedFaceTimeAudio;
- (BOOL)badgesMissedTelephonyCalls;
- (BOOL)callInterruptedAnApplication;
- (void)clearActionSheet;
- (BOOL)contentViewCanRotate;
- (id)currentController;
- (id)currentViewController;
- (void)dealloc;
- (int)defaultAction;
- (BOOL)defaultActionIsFaceTime;
- (BOOL)defaultActionIsFaceTimeAudio;
- (BOOL)defaultActionIsTelephonyCall;
- (BOOL)dialPhoneNumber:(id)fp8;
- (BOOL)dialPhoneNumber:(id)fp8 dialAssist:(BOOL)fp12;
- (BOOL)dialPhoneNumber:(id)fp8 forUID:(int)fp12 dialAssist:(BOOL)fp16;
- (BOOL)dialPhoneNumber:(id)fp8 forUID:(int)fp12 dialAssist:(BOOL)fp16 wasAlreadyAssisted:(BOOL)fp20;
- (BOOL)dialPhoneNumber:(id)fp8 forUID:(int)fp12 service:(int)fp16 dialAssist:(BOOL)fp20 wasAlreadyAssisted:(BOOL)fp24;
- (BOOL)dialVoicemail;
- (BOOL)dialerIsNumericOnly;
- (void)didReceiveMemoryWarning;
- (void)dismissActionSheet;
- (void)displayedCallRemoved:(id)fp8;
- (void)emergencyCallBackModeChangedNotification:(id)fp8;
- (void *)existingAddressBook;
- (BOOL)faceTimeAudioIsAvailable;
- (BOOL)faceTimeInvitationExists;
- (BOOL)faceTimeIsAvailable;
- (void)handleApplicationFinishedSnapshottingNotification:(id)fp8;
- (BOOL)handleDoubleHeightStatusBarTap:(int)fp8;
- (BOOL)handleEvent:(struct __GSEvent *)fp8 withNewEvent:(id)fp12;
- (void)handleResumeEvent:(struct __GSEvent *)fp8;
- (void)handleSuspendEvent:(struct __GSEvent *)fp8;
- (BOOL)inAirplaneMode;
- (BOOL)inCall;
- (BOOL)inFaceTime;
- (BOOL)initiateFaceTimeAudioForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 fanOut:(BOOL)fp20;
- (BOOL)initiateFaceTimeCallForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 fanOut:(BOOL)fp20;
- (BOOL)initiateFaceTimeForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 audioOnly:(BOOL)fp20 fanOut:(BOOL)fp24;
- (BOOL)isAboutToIssueDisconnectOfLastCall;
- (BOOL)isDeviceCapableOfFaceTime;
- (BOOL)isDeviceCapableOfFaceTimeAudio;
- (BOOL)isDeviceCapableOfTelephonyCalls;
- (BOOL)isDisplayingSheet;
- (BOOL)isLowGraphicsPerformanceDevice;
- (BOOL)isMuted;
- (double)launchTime;
- (id)localizedCarrierName;
- (id)nameOfDefaultImageToUpdateAtSuspension;
- (BOOL)openURL:(id)fp8;
- (struct CGRect)phoneViewTabBarContentFrame;
- (void)prepareForDefaultImageSnapshotForScreen:(id)fp8;
- (void)presentActionSheet:(id)fp8;
- (void)presentActionSheet:(id)fp8 fromToolBarItem:(id)fp12;
- (BOOL)promptForTTY;
- (void)promptUpgradeCurrentPhoneCallToFaceTimeIfNecessary;
- (void)requestSuspendAfterLastCall;
- (void)requestSuspendWithTransparencyAfterLastCall;
- (BOOL)resumingApplication;
- (id)rootViewController;
- (BOOL)runTest:(id)fp8 options:(id)fp12;
- (void)setAlertHandler:(id)fp(null);
- (void)setAlertView:(id)fp8;
- (void)setAlertViewManualBackground:(id)fp8;
- (void)setAlertViewManuallyDisplayed:(BOOL)fp8;
- (void)setCurrentController:(id)fp8;
- (void)setIgnoresInteractionEvents:(BOOL)fp8;
- (BOOL)setMuted:(BOOL)fp8;
- (void)setShouldSuspendAfterLastCall:(BOOL)fp8;
- (BOOL)shouldAttemptPhoneCallForService:(int)fp8;
- (BOOL)shouldAttemptPhoneCallForService:(int)fp8 viewController:(id)fp12;
- (BOOL)shouldHangUpOnLock;
- (BOOL)shouldSnapshot;
- (BOOL)shouldSuspendAfterLastCall;
- (BOOL)shouldSuspendAfterVC;
- (void)showAirplaneViewForController:(id)fp8;
- (void)showInitialView;
- (BOOL)showSplashScreenOnSignin;
- (BOOL)showsCallsFromService:(int)fp8;
- (BOOL)showsFaceTime;
- (BOOL)showsFaceTimeAudio;
- (BOOL)showsFaceTimeAudioFavorites;
- (BOOL)showsFaceTimeAudioRecents;
- (BOOL)showsFaceTimeFavorites;
- (BOOL)showsFaceTimeRecents;
- (BOOL)showsPhoneDialer;
- (BOOL)showsPhoneVoicemail;
- (BOOL)showsTelephonyCalls;
- (BOOL)showsTelephonyFavorites;
- (BOOL)showsTelephonyRecents;
- (void)startScrollTest;
- (void)startSwitchTest;
- (int)statusBar:(id)fp8 styleForRequestedStyle:(int)fp12 overrides:(int)fp16;
- (BOOL)suspendingApplication;
- (BOOL)tabBarCanSlide;
- (BOOL)tabBarFillsScreen;
- (BOOL)telephonyCallingIsAvailable;
- (BOOL)toggleMute;
- (id)ttyTitle;
- (void)userDefaultsDidChange:(id)fp8;
- (int)userInterfaceScreenType;
- (unsigned int)userInterfaceStyle;
- (BOOL)usesBlendModes;
- (int)wizardGlobalAppearanceStyle;

@end

