/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PhoneTabViewController-Protocol.h"

@class UIViewController<PhoneTabViewController>;

@interface PhoneNavigationController : _ABAddressBookBeginExclusiveRead <PhoneTabViewController>
{
    UIViewController<PhoneTabViewController> *_rootController;
}

+ (BOOL)_isViewSizeFullScreen:(id)fp8 inWindow:(id)fp12;
+ (CDAnonymousStruct1)badge;
+ (id)defaultPNGName;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void)_updateRootViewController;
- (void)dealloc;
- (void)handleURL:(id)fp8;
- (id)initWithRootViewController:(id)fp8;
- (void)prepareForSnapshot;
- (void)presentViewController:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (id)rootViewController;
- (void)setViewControllers:(id)fp8;
- (BOOL)shouldSnapshot;

@end

