/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PhoneBaseViewController-Protocol.h"

@class DialerController, PHAddressBookController, PHFavoritesViewController, PHRecentsViewController, PHVoicemailNavigationController, PhoneNavigationController;

@interface PhoneTabBarController : _ABAddressBookBeginExclusiveRead <PhoneBaseViewController>
{
    PhoneNavigationController *_favoritesNavigationController;
    PhoneNavigationController *_recentsNavigationController;
    PHFavoritesViewController *_favoritesViewController;
    PHRecentsViewController *_recentsViewController;
    PHAddressBookController *_contactsViewController;
    DialerController *_keypadViewController;
    PHVoicemailNavigationController *_voicemailViewController;
}

+ (id)defaultPNGName;
+ (int)statusBarStyle;
+ (int)viewType;
- (void)_badgeChanged:(id)fp8;
- (void)_popCurrentNavigationControllerToRootViewControllerIfAppropriate;
- (BOOL)_reallyWantsFullScreenLayout;
- (void)_startListeningForBadgeChangedNotifications:(id)fp8;
- (void)_stopListeningForBadgeChangedNotifications:(id)fp8;
- (void)_updateAllBadges:(BOOL)fp8;
- (void)applicationDidResume;
- (id)contactsViewController;
- (int)currentTabViewType;
- (void)dealloc;
- (int)defaultTabViewType;
- (id)favoritesNavigationController;
- (id)favoritesViewController;
- (void)handleURL:(id)fp8;
- (id)init;
- (id)keypadViewController;
- (void)prepareForSnapshot;
- (void)prepareForTransitionInFromViewType:(int)fp8 animated:(BOOL)fp12;
- (void)prepareToHandleURL:(id)fp8;
- (id)recentsNavigationController;
- (id)recentsViewController;
- (void)setContactsViewController:(id)fp8;
- (void)setFavoritesNavigationController:(id)fp8;
- (void)setFavoritesViewController:(id)fp8;
- (void)setKeypadViewController:(id)fp8;
- (void)setRecentsNavigationController:(id)fp8;
- (void)setRecentsViewController:(id)fp8;
- (void)setSelectedViewController:(id)fp8;
- (void)setVoicemailViewController:(id)fp8;
- (BOOL)shouldDisableEdgeClip;
- (BOOL)shouldSnapshot;
- (void)showFavoritesTab:(BOOL)fp8 recentsTab:(BOOL)fp12 contactsTab:(BOOL)fp16 keypadTab:(BOOL)fp20 voicemailTab:(BOOL)fp24;
- (void)switchToTab:(int)fp8;
- (int)tabTypeForViewController:(id)fp8;
- (void)transitionCompleted;
- (void)transitionInFromViewType:(int)fp8 animated:(BOOL)fp12 completionBlock:(id)fp(null);
- (id)viewControllerForTabViewType:(int)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (id)voicemailViewController;

@end

