/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PhoneTabViewController-Protocol.h"

@interface PhoneViewController : _ABAddressBookBeginExclusiveRead <PhoneTabViewController>
{
}

+ (CDAnonymousStruct1)badge;
+ (void)cacheFinishedTabBarIconImage:(id)fp8 finishedSelectedTabBarIconImage:(id)fp12 withTabBarItemName:(id)fp16;
+ (id)defaultPNGName;
+ (void)initializeIconAndTitle:(id)fp8;
+ (BOOL)tabBarIconImageFinished:(id *)fp8 selectedImage:(id *)fp12 forTabBarItemName:(id)fp16;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void)_loadOffsetDefaultForKey:(id)fp8 withScrollView:(id)fp12;
- (void)_prepareForLoadView;
- (void)_saveOffsetDefaultForKey:(id)fp8 withScrollView:(id)fp12;
- (void)handleURL:(id)fp8;
- (id)init;
- (void)prepareForSnapshot;
- (void)savePreferences;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)shouldSnapshot;
- (void)viewWillUnload;

@end

