/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UIImage, UIImageView, UITransitionView, _UIBackdropView;

@interface PhoneDesktopView : _ABAddressBookBeginExclusiveRead
{
    UIImageView *_imageView;
    UIImage *_wallpaperImage;
    UIImage *_queuedImage;
    BOOL _animatingTransition;
    _UIBackdropView *_backdropView;
    UITransitionView *_wallpaperContainer;
}

- (id)backdropView;
- (void)dealloc;
- (double)durationForTransition:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24;
- (BOOL)isAnimatingTransition;
- (void)reallyTransitionToImage:(id)fp8 animated:(BOOL)fp12;
- (void)setBackdropView:(id)fp8;
- (void)setWallpaperContainer:(id)fp8;
- (void)transitionToImage:(id)fp8 animated:(BOOL)fp12;
- (void)transitionToQueuedImage;
- (void)transitionViewDidComplete:(id)fp8 fromView:(id)fp12 toView:(id)fp16;
- (id)wallpaperContainer;

@end

