/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSMutableArray, NSRecursiveLock;

@interface PHRecentsManager : _ABAddressBookBeginExclusiveRead
{
    BOOL _showsFaceTimeCalls;
    BOOL _showsFaceTimeAudioCalls;
    BOOL _showsTelephonyCalls;
    NSMutableArray *calls;
    NSRecursiveLock *callsLock;
}

+ (int)numberOfUnseenMissedCalls;
- (void)applicationDidReceiveMemoryWarningNotification:(id)fp8;
- (void)callHistoryRecordAddedNotification:(struct __CTCall *)fp8;
- (void)callHistorySignificantChangeNotification;
- (id)calls;
- (id)callsLock;
- (id)copyDisplayableCTCalls;
- (id)copyRecentCallsArrayWithCTCalls:(id)fp8;
- (void)dealloc;
- (void)deleteAllCalls;
- (void)deleteCall:(id)fp8;
- (BOOL)dialRecentCall:(id)fp8;
- (void)faceTimeAvailabilityChangedNotification:(id)fp8;
- (void)homeCountryCodeChangedNotification:(id)fp8;
- (id)init;
- (void)markRepresentedCallsAsSeen;
- (void)phoneApplicationAddressBookChangedNotification:(id)fp8;
- (void)phoneApplicationLocaleChangedNotification:(id)fp8;
- (id)recentCalls;
- (BOOL)recentsArray:(id)fp8 representsCTCallsArray:(id)fp12;
- (void)reloadCallsArray;
- (void)reloadCallsArrayIfNecessary;
- (void)setCalls:(id)fp8;
- (void)setCallsLock:(id)fp8;
- (void)setShowsFaceTimeAudioCalls:(BOOL)fp8;
- (void)setShowsFaceTimeCalls:(BOOL)fp8;
- (void)setShowsTelephonyCalls:(BOOL)fp8;
- (BOOL)showsFaceTimeAudioCalls;
- (BOOL)showsFaceTimeCalls;
- (BOOL)showsTelephonyCalls;

@end

