/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHRecentsPersonHeaderView.h"

@interface PHRecentsPersonPhoneHeaderView : PHRecentsPersonHeaderView
{
}

- (id)newSummaryViewForRecentCall:(id)fp8 occurrenceDate:(id)fp12 type:(int)fp16 duration:(double)fp20 category:(int)fp28 dataUsage:(double)fp32;

@end

