/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, PHRecentCall, PHRecentsManager, PHRecentsToggleButton, UITableView;

@interface PHRecentsViewController : PhoneViewController <ABUnknownPersonViewControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_table;
    PHRecentsToggleButton *_toggleButton;
    int _tableFilterMode;
    PHRecentCall *_call;
    unsigned int _isRegisteredForActiveNotifications:1;
    NSArray *indexPathsForMissedCalls;
    NSArray *indexPathsForNormalCalls;
    PHRecentsManager *_recentsManager;
}

+ (CDAnonymousStruct1)badge;
+ (BOOL)requiresNavigationControllerContainer;
+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
- (void)_applicationResumedNotification:(id)fp8;
- (void)_applicationSuspendedNotification:(id)fp8;
- (void)_clearButtonTapped:(id)fp8;
- (void)_filterWasToggled:(id)fp8;
- (void)_handleContentSizeCategoryDidChange:(id)fp8;
- (void)_markAllCallsRead;
- (void)_phoneApplicationDidChangeTabBarSelectionNotification:(id)fp8;
- (void)_recentsManagerCallDeletedNotification:(id)fp8;
- (void)_recentsManagerSignificantChangeNotification:(id)fp8;
- (void)_reloadTableViewAndNavigationBar;
- (void)_significantTimeChangeNotification:(id)fp8;
- (int)_tableFilterMode;
- (void)_updateNavBarButtons;
- (void)accessoryButtonTapped:(id)fp8 withEvent:(id)fp12;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)callAtTableViewIndex:(int)fp8;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)indexPathsForMissedCalls;
- (id)indexPathsForNormalCalls;
- (id)init;
- (void)loadView;
- (id)recentsManager;
- (void)resetCachedIndexes;
- (int)rowCountForCurrentTableMode;
- (void)savePreferences;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setRecentsManager:(id)fp8;
- (void)set_tableFilterMode:(int)fp8;
- (BOOL)shouldSnapshot;
- (void)showCallDetail:(id)fp8 animate:(BOOL)fp12;
- (id)table;
- (void)tableView:(id)fp8 accessoryButtonTappedForRowWithIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableView:(id)fp8 didEndEditingRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)tableView:(id)fp8 willBeginEditingRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)unknownPersonViewController:(id)fp8 didResolveToPerson:(void *)fp12;
- (void)unloadView;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

