/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHRecentCall.h"

@class NSMutableArray;

@interface PHRecentMultiCall : PHRecentCall
{
    NSMutableArray *_callOccurrences;
    NSMutableArray *_underlyingCTCalls;
}

+ (id)callByCoalescing:(id)fp8 withPreviousCall:(id)fp12;
- (id)_callOccurrencesTestDataComplex;
- (id)_callOccurrencesTestDataIncomingAndOutgoing;
- (id)_callOccurrencesTestDataIncomingOnly;
- (id)_callOccurrencesTestDataLongSingle;
- (void)addOccurrence:(id)fp8 type:(int)fp12 category:(int)fp16 duration:(double)fp20 bytesOfDataUsed:(double)fp28;
- (void)addOccurrencesFromArray:(id)fp8;
- (void)addUnderlyingCTCalls:(id)fp8;
- (id)callOccurrences;
- (void)dealloc;
- (void)deleteUnderlyingCTCall;
- (int)numberOfOccurrences;
- (id)occurrenceAtIndex:(int)fp8;
- (BOOL)representsCallAtDate:(id)fp8;
- (id)underlyingCTCalls;

@end

