/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSDate, NSString;

@interface PHRecentCall : _ABAddressBookBeginExclusiveRead
{
    int _category;
    int _type;
    NSString *_destination;
    struct __CFPhoneNumber *_destinationPhoneNumber;
    NSDate *_date;
    double _duration;
    NSString *_compositeName;
    NSString *_destinationLabel;
    NSString *_destinationLocation;
    NSString *_mobileCountryCode;
    NSString *_mobileNetworkCode;
    NSString *_isoCountryCode;
    NSString *_CNAPFirstName;
    NSString *_CNAPSecondNames;
    int _uid;
    void *_addressBookRecord;
    int _identifier;
    unsigned int _destinationIsFormatted:1;
    unsigned int _destinationIsBlocked:1;
    struct __CTCall *_underlyingCTCall;
    int _unreadCount;
    double _bytesOfDataUsed;
}

+ (int)callCategoryForCall:(struct __CTCall *)fp8;
+ (int)callStatusForCall:(struct __CTCall *)fp8;
- (id)_CNAPFirstName;
- (id)_CNAPSecondNames;
- (id)addressBookDestination;
- (void *)addressBookRecord;
- (double)bytesOfDataUsed;
- (id)callOccurrences;
- (id)callerDisplayName;
- (BOOL)canCoalesceWithCall:(id)fp8;
- (int)category;
- (id)compositeName;
- (id)date;
- (void)dealloc;
- (void)deleteUnderlyingCTCall;
- (id)description;
- (id)destination;
- (int)destinationIdentifier;
- (BOOL)destinationIsBlocked;
- (BOOL)destinationIsEmailAddress;
- (id)destinationLabel;
- (id)destinationLocation;
- (struct __CFPhoneNumber *)destinationPhoneNumber;
- (id)destinationStringForDisplay;
- (id)destinationToDialAssisted:(char *)fp8;
- (double)duration;
- (id)formattedDestination;
- (unsigned int)hash;
- (id)init;
- (id)initWithCTCall:(struct __CTCall *)fp8;
- (BOOL)isEqual:(id)fp8;
- (id)isoCountryCode;
- (id)mobileCountryCode;
- (id)mobileNetworkCode;
- (int)numberOfOccurrences;
- (BOOL)representsCallAtDate:(id)fp8;
- (void)setAddressBookRecord:(void *)fp8;
- (void)setBytesOfDataUsed:(double)fp8;
- (void)setCNAPFirstNameAndSecondNamesFromString:(id)fp8;
- (void)setCategory:(int)fp8;
- (void)setDate:(id)fp8;
- (void)setDestination:(id)fp8;
- (void)setDestinationIdentifier:(int)fp8;
- (void)setDestinationIsBlocked:(BOOL)fp8;
- (void)setDestinationLocation:(id)fp8;
- (void)setDestinationPhoneNumber:(struct __CFPhoneNumber *)fp8;
- (void)setDuration:(double)fp8;
- (void)setIsoCountryCode:(id)fp8;
- (void)setMobileCountryCode:(id)fp8;
- (void)setMobileNetworkCode:(id)fp8;
- (void)setType:(int)fp8;
- (void)setUnreadCount:(int)fp8;
- (void)set_CNAPFirstName:(id)fp8;
- (void)set_CNAPSecondNames:(id)fp8;
- (int)type;
- (int)uid;
- (void)uncacheIdentity;
- (id)underlyingCTCalls;
- (int)unreadCount;

@end

