/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class ABFavoritesEntry;

@interface PHStarkFavoritesViewController : PHStarkGenericTableViewController <UIActionSheetDelegate>
{
    ABFavoritesEntry *_selectedFavoriteEntry;
}

- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)allPhoneNumbersForFavoriteEntry:(id)fp8;
- (void)dealloc;
- (float)defaultRowHeight;
- (void)favoritesManagerSignificantChangeNotification:(id)fp8;
- (id)init;
- (void)programmaticallySelectRowAtIndexPath:(id)fp8;
- (id)selectedFavoriteEntry;
- (void)setSelectedFavoriteEntry:(id)fp8;
- (id)subtitleForNoContentBanner;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)titleForNoContentBanner;
- (void)viewDidLoad;

@end

