/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class UIImageView, UILabel;

@interface PHStarkFavoritesTableViewCell : PHStarkGenericTableViewCell
{
    UILabel *_nameLabel;
    UILabel *_phoneNumberTypeLabel;
    UIImageView *_contactImageView;
}

- (id)contactImageView;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)nameLabel;
- (id)phoneNumberTypeLabel;
- (void)setContactImageView:(id)fp8;
- (void)setNameLabel:(id)fp8;
- (void)setPhoneNumberTypeLabel:(id)fp8;
- (void)setRepresentedFavorite:(id)fp8;

@end

