/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericViewController.h"

@class DialerController, UIButton, UIView;

@interface PHStarkInCallKeypadViewController : PHStarkGenericViewController
{
    UIButton *_backButton;
    UIButton *_endButton;
    DialerController *_dialerController;
    UIView *_fakeNavigationBar;
    int _currentHighlightedControlIndex;
}

- (void)_physicalButtonsBegan:(id)fp8 withEvent:(id)fp12;
- (void)_physicalButtonsCancelled:(id)fp8 withEvent:(id)fp12;
- (void)_physicalButtonsEnded:(id)fp8 withEvent:(id)fp12;
- (void)_wheelChangedWithEvent:(id)fp8;
- (id)backButton;
- (void)backButtonTapped:(id)fp8;
- (int)currentHighlightedControlIndex;
- (void)dealloc;
- (id)dialerController;
- (id)endButton;
- (void)endButtonTapped:(id)fp8;
- (id)fakeNavigationBar;
- (void)hardwareControlEventNotification:(id)fp8;
- (void)loadView;
- (void)setBackButton:(id)fp8;
- (void)setCurrentHighlightedControlIndex:(int)fp8;
- (void)setDialerController:(id)fp8;
- (void)setEndButton:(id)fp8;
- (void)setFakeNavigationBar:(id)fp8;

@end

