/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewController.h"

@class PHRecentsManager;

@interface PHStarkRecentsViewController : PHStarkGenericTableViewController
{
    PHRecentsManager *_recentsManager;
}

- (id)badgeString;
- (void)dealloc;
- (float)defaultRowHeight;
- (id)init;
- (void)programmaticallySelectRowAtIndexPath:(id)fp8;
- (id)recentsManager;
- (void)recentsManagerSignificantChangeNotification:(id)fp8;
- (void)setRecentsManager:(id)fp8;
- (id)subtitleForNoContentBanner;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)titleForNoContentBanner;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidLoad;

@end

