/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UIImageView;

@interface PHStarkGenericTableViewCell : _ABAddressBookBeginExclusiveRead
{
    BOOL _showsChevron;
    BOOL _hidesChevronWhenUnhighlighted;
    UIImageView *_chevronImageView;
}

- (id)chevronImageView;
- (void)dealloc;
- (BOOL)hidesChevronWhenUnhighlighted;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)setChevronImageView:(id)fp8;
- (void)setHidesChevronWhenUnhighlighted:(BOOL)fp8;
- (void)setShowsChevron:(BOOL)fp8;
- (BOOL)showsChevron;

@end

