/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class CALayer, UILabel;

@interface PHStarkProgressView : _ABAddressBookBeginExclusiveRead
{
    float _progress;
    UILabel *_elapsedLabel;
    UILabel *_remainingLabel;
    CALayer *_trackLayer;
    CALayer *_indicatorLayer;
}

- (void)dealloc;
- (id)elapsedLabel;
- (id)indicatorLayer;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (float)progress;
- (id)remainingLabel;
- (void)setElapsedLabel:(id)fp8;
- (void)setIndicatorLayer:(id)fp8;
- (void)setProgress:(float)fp8;
- (void)setRemainingLabel:(id)fp8;
- (void)setTrackLayer:(id)fp8;
- (id)trackLayer;

@end

