/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class NSLayoutConstraint, UIDateLabel, UIImageView, UILabel, VMVoicemail;

@interface PHStarkVoicemailTableViewCell : PHStarkGenericTableViewCell
{
    VMVoicemail *_representedVoicemail;
    UILabel *_nameLabel;
    NSLayoutConstraint *_nameLabelBaselineConstraint;
    UILabel *_subtitleLabel;
    UIDateLabel *_dateLabel;
    UIImageView *_unreadIndicatorImageView;
}

- (void)_voicemailFlagsDidChangeNotification:(id)fp8;
- (id)dateLabel;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)nameLabel;
- (id)nameLabelBaselineConstraint;
- (void)prepareForReuse;
- (id)representedVoicemail;
- (void)setDateLabel:(id)fp8;
- (void)setNameLabel:(id)fp8;
- (void)setNameLabelBaselineConstraint:(id)fp8;
- (void)setPendingState:(BOOL)fp8;
- (void)setRepresentedVoicemail:(id)fp8;
- (void)setSubtitleLabel:(id)fp8;
- (void)setSubtitleString:(id)fp8;
- (void)setUnreadIndicatorImageView:(id)fp8;
- (id)subtitleLabel;
- (id)unreadIndicatorImageView;
- (void)updatePendingState;

@end

