/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class NSLayoutConstraint, UIDateLabel, UIImageView, UILabel;

@interface PHStarkRecentsTableViewCell : PHStarkGenericTableViewCell
{
    UILabel *_nameLabel;
    UILabel *_phoneNumberTypeLabel;
    UIDateLabel *_dateLabel;
    NSLayoutConstraint *_nameLabelVerticalLayoutConstraint;
    UIImageView *_outgoingCallIconImageView;
}

- (id)dateLabel;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)nameLabel;
- (id)nameLabelVerticalLayoutConstraint;
- (id)outgoingCallIconImageView;
- (id)phoneNumberTypeLabel;
- (void)setDateLabel:(id)fp8;
- (void)setNameLabel:(id)fp8;
- (void)setNameLabelVerticalLayoutConstraint:(id)fp8;
- (void)setOutgoingCallIconImageView:(id)fp8;
- (void)setPhoneNumberTypeLabel:(id)fp8;
- (void)setRepresentedRecentCall:(id)fp8;
- (void)setShowsOutgoingCallIcon:(BOOL)fp8;

@end

