/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class PHStarkHardwareControlsBroadcaster, PHStarkRootContainerViewController, UIWindow;

@interface PHStarkManager : _ABAddressBookBeginExclusiveRead
{
    PHStarkRootContainerViewController *_containerViewController;
    UIWindow *_starkWindow;
    PHStarkHardwareControlsBroadcaster *_hardwareControlsBroadcaster;
    PHStarkRootContainerViewController *_rootContainerViewController;
}

+ (id)sharedStarkManager;
+ (id)starkScreen;
- (BOOL)activeInterfaceMechanismIsHardware;
- (void)attachStarkToScreen:(id)fp8;
- (id)containerViewController;
- (void)dealloc;
- (id)hardwareControlsBroadcaster;
- (id)init;
- (id)rootContainerViewController;
- (void)screenDidConnectNotification:(id)fp8;
- (void)screenDidDisconnectNotification:(id)fp8;
- (void)screenshotStarkScreen;
- (void)setContainerViewController:(id)fp8;
- (void)setHardwareControlsBroadcaster:(id)fp8;
- (void)setRootContainerViewController:(id)fp8;
- (void)setStarkWindow:(id)fp8;
- (id)starkNavigationController;
- (id)starkWindow;

@end

