/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UILabel;

@interface PHStarkNoContentBannerView : _ABAddressBookBeginExclusiveRead
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setSubtitleLabel:(id)fp8;
- (void)setSubtitleString:(id)fp8;
- (void)setTitleLabel:(id)fp8;
- (void)setTitleString:(id)fp8;
- (id)subtitleLabel;
- (id)subtitleString;
- (id)titleLabel;
- (id)titleString;

@end

