/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@interface PHStaticDialerPad : _ABAddressBookBeginExclusiveRead
{
    int _dialerType;
}

- (id)_highlightedImage;
- (id)_keypadImage;
- (id)_pressedImage;
- (float)_yFudge;
- (int)dialerType;
- (id)initWithDialerType:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGSize)intrinsicContentSize;
- (void)setDialerType:(int)fp8;

@end

