/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PHStarkTelephonyStateMonitorDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, PHStarkTelephonyStateMonitor, UIView, UIViewController;

@interface PHStarkMainMenuContainerViewController : _ABAddressBookBeginExclusiveRead <PHStarkTelephonyStateMonitorDelegate, UITabBarControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_rootViewControllerDictionaries;
    UIView *_centralAreaContainerView;
    UIViewController *_selectedViewController;
    PHStarkTelephonyStateMonitor *_telephonyStateMonitor;
}

- (void)_initializeRootViewControllerDictionaries;
- (id)centralAreaContainerView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (void)loadView;
- (id)navigationItem;
- (id)rootViewControllerDictionaries;
- (id)selectedViewController;
- (void)setCentralAreaContainerView:(id)fp8;
- (void)setRootViewControllerDictionaries:(id)fp8;
- (void)setSelectedViewController:(id)fp8;
- (void)setTelephonyStateMonitor:(id)fp8;
- (BOOL)tabBarController:(id)fp8 shouldSelectViewController:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)telephonyStateDidChangeToState:(int)fp8;
- (id)telephonyStateMonitor;
- (void)viewWillAppear:(BOOL)fp8;

@end

