/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "TPStarkInCallViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class TPStarkInCallViewController, UIView, UIViewController;

@interface PHStarkInCallViewController : _ABAddressBookBeginExclusiveRead <UIGestureRecognizerDelegate, TPStarkInCallViewControllerDelegate, UINavigationControllerDelegate>
{
    BOOL _nextBackDismissesNavController;
    UIViewController *_contactsViewController;
    UIView *_flippyViewContainer;
    TPStarkInCallViewController *_mainInCallViewController;
}

+ (id)latestInCallViewController;
- (BOOL)activePhoneCallExists;
- (void)animateOutIfNecessary;
- (void)backPressed:(id)fp8;
- (void)cancelAddCallViewController:(id)fp8;
- (void)conferencedCallsChangedNotification:(id)fp8;
- (void)dealloc;
- (void)dismissViewControllerAnimated:(BOOL)fp8 completion:(id)fp(null);
- (void)dismissalRequestedFromInCallViewController:(id)fp8;
- (void)displayedCallsChangedNotification:(id)fp8;
- (id)flippyViewContainer;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)hardwareControlEventNotification:(id)fp8;
- (void)incomingCallChangedNotification:(id)fp8;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (void)loadView;
- (id)mainInCallViewController;
- (void)muteStateChangedNotification:(id)fp8;
- (void)navigationController:(id)fp8 willShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)presentAddCallViewControllerRequestedFromInCallViewController:(id)fp8;
- (void)presentKeypadViewControllerRequestedFromInCallViewController:(id)fp8;
- (void)queueUpdateToTPIncallControllerPhoneCalls;
- (void)setFlippyViewContainer:(id)fp8;
- (void)setMainInCallViewController:(id)fp8;
- (void)updateTPInCallControllerPhoneCalls;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;

@end

