/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class UIImageView, UILabel;

@interface PHStarkHardwareMenuTableViewCell : PHStarkGenericTableViewCell
{
    UILabel *_mainLabel;
    UIImageView *_iconImageView;
}

- (void)dealloc;
- (id)iconImageView;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)mainLabel;
- (void)setIconImageView:(id)fp8;
- (void)setMainLabel:(id)fp8;

@end

