/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@interface PHStarkTelephonyStateMonitor : _ABAddressBookBeginExclusiveRead
{
    id <PHStarkTelephonyStateMonitorDelegate> _delegate;
    int _state;
}

- (void)_phoneApplicationDisplayedCallsChangedNotification:(id)fp8;
- (int)currentState;
- (void)dealloc;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)fp8;
- (void)setState:(int)fp8;
- (void)startMonitoringTelephonyState;
- (int)state;
- (void)stopMonitoringTelephonyState;

@end

