/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "DialerLCDFieldProtocol-Protocol.h"

@class UILabel;

@interface PHStarkInCallDialerLCDView : _ABAddressBookBeginExclusiveRead <DialerLCDFieldProtocol>
{
    UILabel *_mainNumberLabel;
}

- (void)dealloc;
- (void)deleteCharacter;
- (BOOL)highlighted;
- (BOOL)inCallMode;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGSize)intrinsicContentSize;
- (id)mainNumberLabel;
- (id)name;
- (void)setDelegate:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setInCallMode:(BOOL)fp8;
- (void)setLabel:(id)fp8;
- (void)setMainNumberLabel:(id)fp8;
- (void)setName:(id)fp8;
- (void)setText:(id)fp8 needsFormat:(BOOL)fp12;
- (id)text;

@end

