/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSArray, NSTimer;

@interface PHTextCycleLabel : _ABAddressBookBeginExclusiveRead
{
    NSArray *_cycleStrings;
    NSTimer *_cycleTimer;
    int _currentCycleStringIndex;
}

- (int)currentCycleStringIndex;
- (id)cycleStrings;
- (id)cycleTimer;
- (void)cycleToNextString;
- (void)dealloc;
- (void)setCurrentCycleStringIndex:(int)fp8;
- (void)setCycleStrings:(id)fp8;
- (void)setCycleTimer:(id)fp8;
- (void)setText:(id)fp8;
- (void)startCyclingStrings;

@end

