/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "MPDetailSliderDelegate-Protocol.h"
#import "PHAudioPlayerDataSource-Protocol.h"
#import "PHAudioPlayerDelegate-Protocol.h"
#import "PHAudioRecorderDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDictionary, NSIndexPath, NSLayoutConstraint, NSTimer, PHAudioPlayer, PHAudioRecorder, PHVoicemailSlider, UIButton, UIProgressView, UITableView, UIView;

@interface PHVoicemailGreetingViewController : _ABAddressBookBeginExclusiveRead <UITableViewDataSource, UITableViewDelegate, PHAudioRecorderDelegate, PHAudioPlayerDelegate, PHAudioPlayerDataSource, MPDetailSliderDelegate>
{
    UITableView *_tableView;
    UIView *_customView;
    UIView *_progressContainer;
    UIButton *_playStopButton;
    UIButton *_recordStopButton;
    PHVoicemailSlider *_slider;
    UIProgressView *_progressView;
    PHAudioRecorder *_greetingRecorder;
    PHAudioPlayer *_greetingPlayer;
    NSTimer *_greetingFetchTimeoutTimer;
    NSTimer *_greetingSaveTimeoutTimer;
    NSLayoutConstraint *_customViewButtonsYConstraint;
    NSLayoutConstraint *_customViewHeightConstraint;
    NSLayoutConstraint *_tableViewHeightConstraint;
    BOOL _hasAttemptedGreetingFetch;
    id _greetingFetchCompletion;
    BOOL _hasRecordedNewGreeting;
    id <PHVoicemailGreetingViewControllerDelegate> _greetingDelegate;
    NSIndexPath *_selectedIndexPath;
    int _greetingAudioState;
    int _greetingUIState;
    NSDictionary *_previousRoute;
    double _newGreetingDuration;
}

- (void)_cancelButtonTapped;
- (void)_greetingFetchBegan:(id)fp8;
- (void)_greetingFetchContinued:(id)fp8;
- (void)_greetingFetchEnded:(id)fp8;
- (void)_greetingFetchTimedOut;
- (void)_greetingSaveCompleted:(id)fp8;
- (void)_greetingSaveTimedOut;
- (void)_handleContentSizeDidChange:(id)fp8;
- (void)_nukeStoredGreetingFile;
- (void)_playStopButtonTapped:(id)fp8 withEvent:(id)fp12;
- (void)_recordStopButtonTapped:(id)fp8 withEvent:(id)fp12;
- (void)_saveButtonTapped;
- (void)_stopListeningForGreetingFetchNotifications;
- (void)_stopListeningForGreetingSaveNotifications;
- (void)_updateFonts;
- (void)_updateForGreetingAudioState;
- (void)_updateForGreetingUIState;
- (void)_updateUI;
- (id)audioFilePath;
- (void)audioRecorderContinuedWithFile:(id)fp8 duration:(double)fp12;
- (void)audioRecorderEndedWithFile:(id)fp8 duration:(double)fp12 error:(id)fp20;
- (void)audioRecorderStartedWithFile:(id)fp8;
- (void)dealloc;
- (void)detailSliderTrackingDidCancel:(id)fp8;
- (void)detailSliderTrackingDidEnd:(id)fp8;
- (void)fetchGreetingInitial:(BOOL)fp8;
- (BOOL)fullFileAvailable;
- (int)greetingAudioState;
- (id)greetingDelegate;
- (id)greetingPlayer;
- (id)greetingRecorder;
- (id)greetingTempFileLocation;
- (int)greetingUIState;
- (BOOL)hasRecordedNewGreeting;
- (id)init;
- (void)loadView;
- (double)newGreetingDuration;
- (id)previousRoute;
- (id)selectedIndexPath;
- (void)setGreetingAudioState:(int)fp8;
- (void)setGreetingDelegate:(id)fp8;
- (void)setGreetingUIState:(int)fp8;
- (void)setHasRecordedNewGreeting:(BOOL)fp8;
- (void)setNewGreetingDuration:(double)fp8;
- (void)setPreviousRoute:(id)fp8;
- (void)setSelectedIndexPath:(id)fp8;
- (void)setSelectedIndexPath:(id)fp8 animated:(BOOL)fp12;
- (void)startedPlayingWithDataSource:(id)fp8;
- (void)stoppedPlayingWithDataSource:(id)fp8 withError:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)updateWithElapsedTime:(double)fp8 playableTime:(double)fp16 totalTime:(double)fp24 isPlaying:(BOOL)fp32 isPlayable:(BOOL)fp36 dataSource:(id)fp40;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

