/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneNavigationController.h"

@class PHVoicemailListViewController, PHVoicemailNoContentViewController, PHVoicemailSetupViewController, TPAlertViewHelper;

@interface PHVoicemailNavigationController : PhoneNavigationController
{
    PHVoicemailListViewController *_inboxViewController;
    PHVoicemailListViewController *_trashViewController;
    PHVoicemailListViewController *_blockedViewController;
    PHVoicemailSetupViewController *_setupViewController;
    PHVoicemailNoContentViewController *_noContentViewController;
    TPAlertViewHelper *_mailboxFullAlertViewHelper;
    BOOL _active;
    BOOL _mailboxRequiresSetupPreviousValue;
    BOOL _sharedServiceIsSubscribedPreviousValue;
}

+ (CDAnonymousStruct1)badge;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void)_checkMailboxUsage;
- (void)_handleActiveNotification:(id)fp8;
- (void)_handleCTIndicatorsVoicemailNotification:(id)fp8;
- (void)_handleMessageWaitingStateChanged:(id)fp8;
- (void)_handleOnlineStateChanged:(id)fp8;
- (void)_handleSetupRequirementChanged:(id)fp8;
- (void)_handleStoreChanged:(id)fp8;
- (void)_handleSuspend:(id)fp8;
- (void)_handleTaskEndedOrCancelled:(id)fp8;
- (void)_invalidateBadge;
- (void)_playVoicemailSound;
- (void)_updateUIState;
- (void)_updateUIStateForce:(BOOL)fp8;
- (void)_voicemailsAdded:(id)fp8;
- (id)blockedViewController;
- (void)dealloc;
- (void)handleURL:(id)fp8;
- (id)inboxViewController;
- (id)init;
- (BOOL)mailboxRequiresSetupPreviousValue;
- (id)noContentViewController;
- (void)setMailboxRequiresSetupPreviousValue:(BOOL)fp8;
- (void)setSharedServiceIsSubscribedPreviousValue:(BOOL)fp8;
- (id)setupViewController;
- (BOOL)sharedServiceIsSubscribedPreviousValue;
- (BOOL)shouldSnapshot;
- (id)trashViewController;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)fp8;

@end

