/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "RadiosPreferencesDelegate-Protocol.h"

@class NSArray, RadiosPreferences, UIButton, UIColor, UILabel, UIView;

@interface PHVoicemailUnavailableCell : _ABAddressBookBeginExclusiveRead <RadiosPreferencesDelegate>
{
    BOOL _showCallVoicemailButton;
    UIColor *_tableViewSeparatorColor;
    UILabel *_voicemailUnavailableLabel;
    UIButton *_callVoicemailButton;
    UIView *_bottomLineView;
    UIView *_topLineView;
    NSArray *_mutableConstraints;
    RadiosPreferences *_radiosPreferences;
}

+ (float)height;
- (void)_handleContentSizeDidChange:(id)fp8;
- (void)_updateCallVoicemailButton;
- (void)_updateFonts;
- (void)airplaneModeChanged;
- (id)bottomLineView;
- (void)callVoicemail;
- (id)callVoicemailButton;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)mutableConstraints;
- (id)radiosPreferences;
- (void)setBottomLineView:(id)fp8;
- (void)setCallVoicemailButton:(id)fp8;
- (void)setMutableConstraints:(id)fp8;
- (void)setRadiosPreferences:(id)fp8;
- (void)setShowCallVoicemailButton:(BOOL)fp8;
- (void)setTableViewSeparatorColor:(id)fp8;
- (void)setTopLineView:(id)fp8;
- (void)setVoicemailUnavailableLabel:(id)fp8;
- (BOOL)showCallVoicemailButton;
- (id)tableViewSeparatorColor;
- (id)topLineView;
- (void)updateConstraints;
- (id)voicemailUnavailableLabel;

@end

