/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class UILabel;

@interface PHVoicemailGreetingCell : _ABAddressBookBeginExclusiveRead
{
    UILabel *_greetingTextLabel;
}

- (void)_handleContentSizeDidChange:(id)fp8;
- (void)_updateFonts;
- (id)greetingTextLabel;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)setGreetingTextLabel:(id)fp8;

@end

