/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class AVController, NSArray, NSDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSString;

@interface PHVoicemailAudioController : _ABAddressBookBeginExclusiveRead
{
    NSString *_category;
    AVController *_avController;
    NSObject<OS_dispatch_queue> *_avControllerQueue;
    NSObject<OS_dispatch_queue> *_pickableRoutesQueue;
    NSObject<OS_dispatch_queue> *_pickedRouteQueue;
    NSArray *_pickableRoutes;
    NSDictionary *_pickedRoute;
    NSDictionary *_forcedPickedRoute;
    BOOL _isRequestingPickableRoutes;
    BOOL _isRequestingPickedRoute;
    unsigned long long _lastPickableRoutesScheduleTime;
    unsigned long long _lastPickedRouteScheduleTime;
    NSNumber *_currentTimeOverride;
}

- (void)_avControllerTimeJumpedAfterReset:(id)fp8;
- (id)_initWithCategory:(id)fp8;
- (void)_mediaServerDied:(id)fp8;
- (void)_pickableRoutesChanged:(id)fp8;
- (id)_pickableRoutesForceNewRequest:(BOOL)fp8;
- (id)_pickedRouteForceNewRequest:(BOOL)fp8;
- (id)avController;
- (double)currentTime;
- (id)currentTimeOverride;
- (void)dealloc;
- (id)initForVoicemail;
- (id)initForVoicemailGreeting;
- (id)pickableRoutes;
- (id)pickedRoute;
- (int)pickedRouteType;
- (id)receiverRoute;
- (void)setCurrentTime:(double)fp8;
- (void)setCurrentTimeOverride:(id)fp8;
- (void)setPickedRoute:(id)fp8;
- (id)speakerRoute;
- (int)typeForRoute:(id)fp8;

@end

