/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class PHVoicemailListViewController<PHVoicemailListViewControllerConcrete>, UILabel;

@interface PHVoicemailFolderCell : _ABAddressBookBeginExclusiveRead
{
    UILabel *_folderLabel;
    UILabel *_countLabel;
    PHVoicemailListViewController<PHVoicemailListViewControllerConcrete> *_viewController;
}

+ (float)height;
- (void)_handleContentSizeDidChange:(id)fp8;
- (void)_handleStoreChanged:(id)fp8;
- (void)_updateCount;
- (void)_updateFonts;
- (void)dealloc;
- (id)deletedText;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)prepareForReuse;
- (void)setViewController:(id)fp8;
- (id)viewController;

@end

