/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

#import "PHVoicemailGreetingViewControllerDelegate-Protocol.h"
#import "TPSetPINViewControllerDelegate-Protocol.h"

@class NSTimer, PHVoicemailNavigationController, PhoneNavigationController;

@interface PHVoicemailSetupViewController : _ABAddressBookBeginExclusiveRead <TPSetPINViewControllerDelegate, PHVoicemailGreetingViewControllerDelegate>
{
    PHVoicemailNavigationController *_navigationController;
    NSTimer *_passwordChangeTimedOutTimer;
    id <PHVoicemailSetupViewControllerDelegate> _voicemailSetupDelegate;
    PhoneNavigationController *_setupPINAndGreetingNavigationController;
}

- (void)_handleVoicemailPasswordChangeTaskNotification:(id)fp8;
- (void)_handleVoicemailPasswordChangeTimedOut;
- (BOOL)_hasValidProvisionalPIN;
- (void)_setupNoContentViewForInitialSetup;
- (void)_voicemailSetupButtonTapped;
- (void)dealloc;
- (id)initWithNavigationController:(id)fp8;
- (void)loadView;
- (id)navigationController;
- (void)reset;
- (void)setNavigationController:(id)fp8;
- (void)setPINViewControllerFinished:(id)fp8 success:(BOOL)fp12 oldPIN:(id)fp16 newPIN:(id)fp20;
- (void)setSetupPINAndGreetingNavigationController:(id)fp8;
- (void)setVoicemailSetupDelegate:(id)fp8;
- (id)setupPINAndGreetingNavigationController;
- (void)voicemailGreetingViewControllerFinished:(id)fp8;
- (id)voicemailSetupDelegate;

@end

