/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class NSArray, PHVoicemailCell, UIControl, UITableView, UIView;

@interface PHVoicemailListMaskView : _ABAddressBookBeginExclusiveRead
{
    char *_dismissFlag;
    UIControl *_topGrayView;
    UIView *_topLineView;
    UIControl *_bottomGrayView;
    UIView *_bottomLineView;
    NSArray *_cellViewConstraints;
    NSArray *_lineConstraints;
    UITableView *_tableView;
    BOOL _showingGrayLayer;
    PHVoicemailCell *_cellToShow;
    id <PHVoicemailListMaskViewDelegate> _listMaskViewDelegate;
}

- (void)_grayViewTouchUpInside:(id)fp8 withEvent:(id)fp12;
- (id)cellToShow;
- (void)dealloc;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 tableView:(id)fp24;
- (void)layoutSubviews;
- (id)listMaskViewDelegate;
- (void)recalculateMaskPosition;
- (void)setCellToShow:(id)fp8;
- (void)setListMaskViewDelegate:(id)fp8;
- (void)setShowingGrayLayer:(BOOL)fp8;
- (BOOL)showingGrayLayer;
- (void)updateConstraints;

@end

