/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHVoicemailListViewController.h"

#import "PHVoicemailGreetingViewControllerDelegate-Protocol.h"
#import "PHVoicemailListViewControllerConcrete-Protocol.h"

@interface PHVoicemailInboxListViewController : PHVoicemailListViewController <PHVoicemailGreetingViewControllerDelegate, PHVoicemailListViewControllerConcrete>
{
}

- (void)_updateGreetingButtonAllowed;
- (id)cellDetailDestructiveActionText;
- (id)childListControllers;
- (void)dealloc;
- (unsigned int)flagsNotToHave;
- (unsigned int)flagsToHave;
- (id)folderName;
- (void)greetingButtonTapped;
- (id)initWithNavigationController:(id)fp8;
- (id)navigationBarText;
- (id)navigationBarTextWithCountFormat;
- (void)performCellDetailDestructiveActionForVoicemail:(id)fp8;
- (void)performTableViewDestructiveActionForVoicemail:(id)fp8;
- (BOOL)popOffIfEmpty;
- (id)tableViewDestructiveActionText;
- (void)voicemailGreetingViewControllerFinished:(id)fp8;
- (void)willShowVoicemails:(id)fp8;

@end

