/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@interface PHVoicemailSlider : _ABAddressBookBeginExclusiveRead
{
}

- (id)_modernThumbImageWithColor:(id)fp8 height:(float)fp12;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)reset;
- (id)timeLabelFontForStyle:(int)fp8;
- (id)timeLabelTextColorForStyle:(int)fp8;
- (float)timeLabelVerticalOffsetForStyle:(int)fp8;

@end

