/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PHVoicemailListViewController.h"

#import "PHVoicemailListViewControllerConcrete-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class UIActionSheet;

@interface PHVoicemailBlockedListViewController : PHVoicemailListViewController <UIActionSheetDelegate, PHVoicemailListViewControllerConcrete>
{
    UIActionSheet *_deleteAllConfirmationActionSheet;
}

- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)cellDetailDestructiveActionText;
- (void)deleteAllTapped;
- (unsigned int)flagsNotToHave;
- (unsigned int)flagsToHave;
- (id)folderName;
- (id)initWithNavigationController:(id)fp8;
- (id)navigationBarText;
- (void)performCellDetailDestructiveActionForVoicemail:(id)fp8;
- (void)performTableViewDestructiveActionForVoicemail:(id)fp8;
- (BOOL)popOffIfEmpty;
- (id)tableViewDestructiveActionText;

@end

