/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "PHVoicemailCellDelegate-Protocol.h"
#import "PHVoicemailListMaskViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, PHVoicemailListMaskView, PHVoicemailNavigationController, UIGestureRecognizer, UITableView, VMVoicemail;

@interface PHVoicemailListViewController : PhoneViewController <PHVoicemailListMaskViewDelegate, ABUnknownPersonViewControllerDelegate, UIGestureRecognizerDelegate, PHVoicemailCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    PHVoicemailNavigationController *_navigationController;
    PHVoicemailListMaskView *_maskView;
    UITableView *_tableView;
    NSObject<OS_dispatch_queue> *_queue;
    int _disableUserInteractionCountLock;
    int _disableUserInteractionCount;
    int _isReloadingTableViewLock;
    BOOL _isReloadingTableView;
    BOOL _shouldReloadTableView;
    NSObject<OS_dispatch_queue> *_initialSetupQueue;
    int _isSettingUpLock;
    BOOL _isSettingUp;
    BOOL _reloadAfterInitialSetup;
    NSObject<OS_dispatch_group> *_loadingGroup;
    NSArray *_voicemails;
    NSArray *_childListViewControllersWithContent;
    BOOL _visible;
    BOOL _showingUnavailableCell;
    NSIndexPath *_detailIndexPath;
    VMVoicemail *_selectedVoicemail;
    UIGestureRecognizer *_navBarGestureRecognizer;
    UIGestureRecognizer *_leftBarButtonItemGestureRecognizer;
    UIGestureRecognizer *_rightBarButtonItemGestureRecognizer;
}

- (void)_disableInteraction;
- (void)_enableInteraction;
- (id)_fetchCurrentChildListViewControllersWithContent;
- (id)_fetchCurrentVoicemails;
- (int)_firstVoicemailOffset;
- (void)_forceCompleteTableViewReloadWithVoicemails:(id)fp8 childListControllersWithContent:(id)fp12 showingUnavailableCell:(BOOL)fp16;
- (void)_handleBackgroundNotification:(id)fp8;
- (void)_handleContentSizeDidChange:(id)fp8;
- (void)_handleNavBarTap:(id)fp8;
- (void)_handleSignificantTimeChange:(id)fp8;
- (void)_handleVoicemailListChanged:(id)fp8;
- (id)_indexPathForItem:(id)fp8 inList:(id)fp12 offset:(int)fp16;
- (id)_indexPathsForItems:(id)fp8 inList:(id)fp12 offset:(int)fp16;
- (void)_performEfficientTableViewReloadWithVoicemails:(id)fp8 childListControllersWithContent:(id)fp12 showingUnavailableCell:(BOOL)fp16;
- (void)_popOffIfNeeded;
- (void)_reloadTableViewIfNecessary;
- (void)_updateTitle;
- (void)_updateUIForMaskViewChange;
- (void)_voicemailUnavailableCellHeightChanged:(id)fp8;
- (id)childListViewControllersWithContent;
- (void)closeVoicemail;
- (id)contentScrollView;
- (void)dealloc;
- (id)detailIndexPath;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (id)initWithNavigationController:(id)fp8;
- (id)leftBarButtonItemGestureRecognizer;
- (void)loadView;
- (void)maskViewWasTappedOutsideOfShownCell:(id)fp8;
- (id)navBarGestureRecognizer;
- (id)navigationController;
- (void)playVoicemail:(id)fp8;
- (id)rightBarButtonItemGestureRecognizer;
- (id)selectedVoicemail;
- (void)setChildListViewControllersWithContent:(id)fp8;
- (void)setDetailIndexPath:(id)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setLeftBarButtonItemGestureRecognizer:(id)fp8;
- (void)setNavBarGestureRecognizer:(id)fp8;
- (void)setNavigationController:(id)fp8;
- (void)setRightBarButtonItemGestureRecognizer:(id)fp8;
- (void)setSelectedVoicemail:(id)fp8;
- (void)setShowingUnavailableCell:(BOOL)fp8;
- (void)setVisible:(BOOL)fp8;
- (void)setVoicemails:(id)fp8;
- (BOOL)shouldBeShown;
- (BOOL)showingUnavailableCell;
- (id)table;
- (void)tableView:(id)fp8 accessoryButtonTappedForRowWithIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canMoveRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableView:(id)fp8 didDeselectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didEndEditingRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willBeginEditingRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)unknownPersonViewController:(id)fp8 didResolveToPerson:(void *)fp12;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)visible;
- (id)voicemails;

@end

