/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookBeginExclusiveRead.h"

@class SixSquareButton;

@interface SixSquareView : _ABAddressBookBeginExclusiveRead
{
    SixSquareButton *_buttons[6];
    id _delegate;
    BOOL _onlyShowsFourButtons;
}

- (void)_buttonClicked:(id)fp8;
- (void)_buttonDown:(id)fp8;
- (void)_buttonHeldDown:(id)fp8;
- (void)_buttonHeldDownShort:(id)fp8;
- (void)_cancelButtonDown:(id)fp8;
- (id)buttonAtPosition:(int)fp8;
- (void)dealloc;
- (void)fadeInButtons;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGSize)intrinsicContentSize;
- (BOOL)onlyShowsFourButtons;
- (void)prepareForFadeIn;
- (void)removeFromSuperview;
- (void)setAllButtonsEnabled:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (void)setOnlyShowsFourButtons:(BOOL)fp8;
- (void)setTitle:(id)fp8 image:(id)fp12 selectedImage:(id)fp16 forPosition:(int)fp20;
- (struct CGSize)totalSize;

@end

