/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol TPSetPINViewControllerDelegate
- (void)setPINViewControllerFinished:(id)fp8 success:(BOOL)fp12 oldPIN:(id)fp16 newPIN:(id)fp20;
@end

